modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.5273715853691101
  - 0.6025961637496948
  - -0.11239458620548248
  - 0.6046621799468994
  - -0.20411133766174316
  - -0.6522759199142456
  - -0.2821546792984009
  - -0.42046919465065
  - -0.5326504111289978
  - 0.44731348752975464
  - 0.28700709342956543
  - 0.12941640615463257
  - 0.5508278012275696
  - 0.3027999699115753
  - 0.18153949081897736
  - 0.06862088292837143
  - 0.20984993875026703
  - 0.1898316740989685
  - 0.1967712938785553
  - 0.37530866265296936
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48053_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48053")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
