modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.8290072679519653
  - 0.0556466206908226
  - 0.83036869764328
  - 2.165196418762207
  - 0.3936508595943451
  - 1.1533148288726807
  - -1.2485287189483643
  - -0.14712843298912048
  - 0.5037609934806824
  - -0.09943510591983795
  - -0.556938648223877
  - 0.0004353414988145232
  - -3.634995222091675
  - 1.7066847085952759
  - 0.5063503384590149
  - 2.630751132965088
  - -0.4168202877044678
  - -0.621340274810791
  - -1.3846886157989502
  - 0.18935689330101013
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48209_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48209")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
