modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.24788817763328552
  - -0.12091946601867676
  - 1.2119752168655396
  - 0.5993716716766357
  - -0.40862536430358887
  - -0.202267587184906
  - -0.011260414496064186
  - -0.005004763603210449
  - 0.21876639127731323
  - -0.010722721926867962
  - 0.07378211617469788
  - 0.003889621701091528
  - 2.7820098400115967
  - 0.5024732351303101
  - 1.158229947090149
  - -0.8353972434997559
  - -0.08972048759460449
  - 0.9007521271705627
  - 0.4130946695804596
  - 0.053579941391944885
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48453_blocks_3_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (agg_sector=="3")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
