modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.29751500487327576
  - -0.3465917408466339
  - -1.1698682308197021
  - -0.12799158692359924
  - -1.013085961341858
  - 0.5065229535102844
  - -0.0031556037720292807
  - -1.275712251663208
  - -0.7755073308944702
  - -0.43114423751831055
  - -0.7283111810684204
  - 0.0021711839362978935
  - 2.3948354721069336
  - 1.280116081237793
  - 2.1750736236572266
  - 1.6058857440948486
  - 1.7880899906158447
  - 1.8944178819656372
  - 1.9587781429290771
  - -0.2729197144508362
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48453_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
