modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.0132924318313599
  - 0.9336536526679993
  - -0.5449571013450623
  - -1.0924699306488037
  - -0.3745180368423462
  - 0.6419084668159485
  - -0.9107235670089722
  - -0.636423647403717
  - -0.5971875190734863
  - 0.2949085533618927
  - -3.1014842987060547
  - 1.998028039932251
  - 1.174943447113037
  - 2.5563433170318604
  - -1.6122416257858276
  - -1.9707653522491455
  - -0.3109896183013916
  - -0.8345255255699158
  - 0.27864211797714233
  - -0.08608046174049377
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48021_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
