modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.5267735719680786
  - -0.7950270771980286
  - 0.0198877714574337
  - 0.4347783923149109
  - -0.7038492560386658
  - -1.5646592378616333
  - -1.0649164915084839
  - -0.8775266408920288
  - -0.6535243988037109
  - 0.45095059275627136
  - -0.34830617904663086
  - 1.5269935131072998
  - 0.5792765617370605
  - 0.3094983696937561
  - 0.19716253876686096
  - 0.42496630549430847
  - 0.8880026936531067
  - 0.9005230069160461
  - 0.8661565184593201
  - 0.39603593945503235
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48491_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
