modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.5967217683792114
  - -0.19137908518314362
  - 0.5457352995872498
  - 0.583164393901825
  - -0.7414703369140625
  - -0.24262255430221558
  - -0.4301915466785431
  - -0.7982146143913269
  - -0.507210373878479
  - 0.57595294713974
  - 2.4318511486053467
  - 0.602664053440094
  - 0.38574960827827454
  - 0.41383230686187744
  - 0.06565313041210175
  - -0.4873240888118744
  - 0.2151302695274353
  - 0.22831423580646515
  - 0.22639352083206177
  - -0.16998116672039032
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48055_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
