modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -2.162122964859009
  - -0.27667367458343506
  - -2.2484543323516846
  - 1.1648668050765991
  - 0.32300907373428345
  - -0.3980242908000946
  - -0.0010696443496271968
  - -1.1674436330795288
  - -0.7142429947853088
  - 0.30436813831329346
  - -0.38190338015556335
  - 0.031095799058675766
  - -2.9209043979644775
  - -1.4425257444381714
  - -2.0410232543945312
  - -1.028699517250061
  - -1.2938451766967773
  - -1.4415862560272217
  - -1.3967502117156982
  - 2.7406303882598877
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48053_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48053")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
