modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.3861754536628723
  - -0.1415749043226242
  - -0.2240685522556305
  - -0.6827405095100403
  - -0.053636662662029266
  - 0.2952275574207306
  - -0.3327929675579071
  - 0.43439242243766785
  - 0.20577090978622437
  - 0.43450281023979187
  - -0.6483155488967896
  - -0.1054791733622551
  - -0.5302473306655884
  - -0.7693593502044678
  - 0.07239636778831482
  - 0.0868152305483818
  - 0.13638652861118317
  - 0.16692134737968445
  - 0.24812562763690948
  - 0.17678269743919373
  - 0.15375515818595886
  - 0.15840736031532288
  - 0.26702117919921875
  - 0.09049353748559952
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48055_blocks_own_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==4)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
