modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.1733279824256897
  - -0.8588126301765442
  - 0.5408244729042053
  - -0.9581868648529053
  - 1.65599524974823
  - 0.6237501502037048
  - 0.3251720666885376
  - 0.9798157215118408
  - 0.3318280279636383
  - -1.4211009740829468
  - -0.756343424320221
  - 0.5407518744468689
  - -1.9369367361068726
  - -0.4091945290565491
  - -0.07505768537521362
  - -0.08899961411952972
  - 0.04592997580766678
  - -0.31704410910606384
  - -0.34754669666290283
  - -0.2362474799156189
  - -0.20352888107299805
  - -0.16684788465499878
  - 0.12947359681129456
  - -0.11158983409404755
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48491_blocks_rent_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==5)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
