modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -1.072511911392212
  - -0.3961101174354553
  - 0.41973885893821716
  - -0.0036836862564086914
  - -0.8057971596717834
  - -0.33995571732521057
  - 0.4599015414714813
  - 0.01747155375778675
  - -0.8996177911758423
  - 0.03499484434723854
  - -0.0008064699359238148
  - -0.6758378744125366
  - -0.26796555519104004
  - -0.053904712200164795
  - 0.41033288836479187
  - 4.67666482925415
  - -0.9721980690956116
  - -2.829437255859375
  - 1.6448469161987305
  - -0.4589211642742157
  - 1.0622899532318115
  - 0.9452746510505676
  - 0.3297553062438965
  - 4.861001491546631
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48453_blocks_own_2p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==3)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
