modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.22807982563972473
  - 2.7745461463928223
  - 1.28996741771698
  - -1.0194473266601562
  - 2.5313491821289062
  - -0.6504939198493958
  - 1.37337064743042
  - 0.5821331739425659
  - -0.7519696354866028
  - -0.4636766016483307
  - -0.28518375754356384
  - 0.9785656929016113
  - -0.5069908499717712
  - 0.6889488101005554
  - -0.9083629846572876
  - 0.003144257701933384
  - -0.4119623005390167
  - 0.5329673290252686
  - -0.7430239319801331
  - 0.4841318726539612
  - 0.16081646084785461
  - 0.28030914068222046
  - 0.2910486161708832
  - 0.14781454205513
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48021_blocks_own_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==4)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
