modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 1.2716702222824097
  - 0.2566453218460083
  - 0.5811663866043091
  - -2.33587646484375
  - 0.887967050075531
  - 0.8926947712898254
  - -0.18596455454826355
  - -0.05965195596218109
  - 0.34743446111679077
  - -0.16215690970420837
  - -0.007176119834184647
  - -0.44687512516975403
  - -1.6689393520355225
  - 1.0270088911056519
  - 0.73435378074646
  - -0.37415367364883423
  - -1.3741669654846191
  - 0.3048781156539917
  - -0.13974270224571228
  - 0.5397499799728394
  - 0.6669504046440125
  - 0.09360897541046143
  - 0.12944364547729492
  - -0.3878055810928345
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48491_blocks_own_1p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==2)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
