modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.5228354334831238
  - -0.7533569931983948
  - 0.5564728379249573
  - -0.0003066793433390558
  - 0.6711854934692383
  - -0.5631024837493896
  - 0.7028014659881592
  - -0.9933251142501831
  - 0.7937455773353577
  - 0.46218279004096985
  - -0.7189797163009644
  - 1.2995909452438354
  - 0.5864012837409973
  - -0.5913169384002686
  - -0.7119918465614319
  - 0.10423453152179718
  - -0.6506444215774536
  - -0.6902373433113098
  - -0.5734441876411438
  - -0.6756147146224976
  - -0.6830676794052124
  - -0.6521320343017578
  - 0.41708236932754517
  - 0.1805960237979889
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48053_blocks_rent_2p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==7)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
