modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.11332842707633972
  - 0.4267548620700836
  - 2.302936553955078
  - -0.002380287041887641
  - 1.0018031597137451
  - 1.9615670442581177
  - -0.919562816619873
  - -0.5661843419075012
  - 0.6192578673362732
  - -0.6036591529846191
  - -0.758571445941925
  - -0.4646780788898468
  - -0.45740440487861633
  - -2.365534782409668
  - -0.6478338837623596
  - -0.023350263014435768
  - 0.17081506550312042
  - 0.35336172580718994
  - -0.5082860589027405
  - 0.559689998626709
  - 0.2800828516483307
  - 0.21325890719890594
  - 0.002260721754282713
  - -0.014032179489731789
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48021_blocks_rent_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==8)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
