modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.348012238740921
  - 0.0487046055495739
  - 0.2568172216415405
  - -0.002515900181606412
  - 0.3875615894794464
  - 0.15581707656383514
  - 0.3138352930545807
  - 0.09259939938783646
  - -0.8552292585372925
  - 0.37629130482673645
  - -0.13453257083892822
  - -0.06963739544153214
  - -0.25905898213386536
  - -0.01926303841173649
  - 0.04597216844558716
  - 6.3429460525512695
  - -1.052123785018921
  - -1.2463010549545288
  - 0.18939246237277985
  - 0.04815506935119629
  - 0.7679631114006042
  - 0.5224961042404175
  - 0.31419268250465393
  - 6.1723456382751465
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48453_blocks_own_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==4)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
