modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -1.3754335641860962
  - -0.8914782404899597
  - 0.1884383261203766
  - -0.0040373122319579124
  - -0.00048158399295061827
  - 1.3603531122207642
  - 1.9775692224502563
  - 0.6466517448425293
  - -0.5500289797782898
  - -1.0968503952026367
  - -1.2057878971099854
  - 0.19449307024478912
  - 0.9922069907188416
  - -1.2457160949707031
  - 0.07432980835437775
  - -0.13581779599189758
  - -0.3457610011100769
  - -0.08932168781757355
  - 0.26435863971710205
  - -0.004029636271297932
  - -0.3963693082332611
  - 0.05094734951853752
  - 0.19980402290821075
  - -0.12820996344089508
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48491_blocks_rent_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==8)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
