modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 1.4864318370819092
  - 0.12113949656486511
  - 0.326492577791214
  - -1.8547890186309814
  - 0.2895848751068115
  - -0.13182216882705688
  - 0.7963192462921143
  - -1.137994647026062
  - -0.6523225903511047
  - 0.4567665755748749
  - -0.007305114064365625
  - 0.4732727110385895
  - 0.9039367437362671
  - 0.15237084031105042
  - -0.21094734966754913
  - -2.299253225326538
  - -0.12460295855998993
  - 1.3688901662826538
  - -0.6593700051307678
  - 0.6051058769226074
  - 0.29332929849624634
  - 0.31644660234451294
  - 0.2015714794397354
  - -2.1255757808685303
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48209_blocks_rent_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==5)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
