modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.3807079792022705
  - -0.12225842475891113
  - 0.35755041241645813
  - -0.001530881505459547
  - 0.4255583882331848
  - 0.10969219356775284
  - 0.21800656616687775
  - -0.14355716109275818
  - -0.11535152047872543
  - 0.3226178288459778
  - -0.0012452546507120132
  - 0.26109200716018677
  - -0.015494955703616142
  - -0.6527970433235168
  - -0.8251129984855652
  - -2.267617702484131
  - 0.4068129062652588
  - 0.7580667734146118
  - 1.0808519124984741
  - 0.6410330533981323
  - -1.4770903587341309
  - -2.1037118434906006
  - 0.004873954690992832
  - 3.495208740234375
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48453_blocks_own_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==1)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
