modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.5177758932113647
  - 0.3600747883319855
  - 1.087546944618225
  - -0.6542766690254211
  - 2.8705086708068848
  - -0.6021541953086853
  - 1.4063574075698853
  - -1.192415714263916
  - 0.644580066204071
  - -0.6830036640167236
  - -0.8796156644821167
  - 0.4062328338623047
  - -0.6765207648277283
  - -1.7102049589157104
  - -1.6557074785232544
  - 0.3892378509044647
  - -0.05421113595366478
  - 0.7046543955802917
  - -0.3275330662727356
  - 0.7146627306938171
  - 0.4109847843647003
  - 0.4251094162464142
  - 0.3497627377510071
  - 0.32813772559165955
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48021_blocks_rent_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==5)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
