modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.994581401348114
  - 0.241788849234581
  - 0.04752175509929657
  - -0.0004012160934507847
  - 2.139305591583252
  - 2.5069007873535156
  - 0.11912445724010468
  - 0.9778766632080078
  - 0.33987244963645935
  - -1.36537504196167
  - -0.19214841723442078
  - -0.4182230234146118
  - -0.4947819709777832
  - -0.45956888794898987
  - -0.21205665171146393
  - -0.3994861841201782
  - 0.59952312707901
  - 0.6695592999458313
  - 0.34992700815200806
  - 0.22558768093585968
  - -0.022576652467250824
  - 0.07153437286615372
  - 0.29608476161956787
  - -0.4235120117664337
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48491_blocks_own_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==1)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
