modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.8029704093933105
  - -0.9003366231918335
  - 1.4948961734771729
  - -0.002028260612860322
  - 0.4320204555988312
  - 1.3988040685653687
  - -1.0908411741256714
  - -0.3364047706127167
  - -1.3086743354797363
  - 0.6429982781410217
  - -0.3157232999801636
  - 0.41998571157455444
  - 0.3268742859363556
  - 0.018782855942845345
  - -1.3387433290481567
  - -0.2439279407262802
  - -1.2227660417556763
  - 0.3820172846317291
  - 0.4979819655418396
  - 0.3212558627128601
  - 0.3101915121078491
  - 0.28865280747413635
  - 0.024168534204363823
  - -0.11388690769672394
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48209_blocks_rent_1p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==6)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
