modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.6682252287864685
  - 0.5481891632080078
  - 0.356082022190094
  - -2.0038223266601562
  - -0.12301387637853622
  - 0.17700256407260895
  - -1.5046403408050537
  - 0.2683298587799072
  - -0.5711929202079773
  - 0.7246514558792114
  - -0.5311444401741028
  - -0.5836530923843384
  - -0.0384959951043129
  - -2.090665578842163
  - 1.7003366947174072
  - -0.14176438748836517
  - 0.49122270941734314
  - -0.8880690336227417
  - -0.6210162043571472
  - -0.9210389256477356
  - -0.8039467930793762
  - -0.9427318572998047
  - 0.24487465620040894
  - -1.589494228363037
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48021_blocks_own_2p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==3)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
