modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.6487652659416199
  - 0.8758348226547241
  - -0.7604963183403015
  - -1.691678762435913
  - -0.7035936117172241
  - 0.1788613200187683
  - -0.3715756833553314
  - 1.4679495096206665
  - -0.39411935210227966
  - -0.8175958395004272
  - -1.0621150732040405
  - 0.5201786160469055
  - -0.08771391957998276
  - 0.2623688578605652
  - 0.34424740076065063
  - 0.5512256026268005
  - 0.5084826946258545
  - 0.8024980425834656
  - 0.5717827677726746
  - 0.7573620676994324
  - 0.753113865852356
  - 0.772463321685791
  - 0.30215516686439514
  - 0.7758384346961975
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48055_blocks_rent_2p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==7)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
