modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 1.0819662809371948
  - 0.77580726146698
  - 0.3543485105037689
  - -0.006775596644729376
  - 0.21280217170715332
  - -0.08430935442447662
  - 0.04127645120024681
  - -0.4904552698135376
  - -0.702458381652832
  - 0.299602746963501
  - -0.10660373419523239
  - -0.6957587599754333
  - -0.4413222670555115
  - 0.10095592588186264
  - -1.051505208015442
  - -1.4611787796020508
  - 1.1092641353607178
  - 0.6995934247970581
  - -0.0600956566631794
  - -0.27771928906440735
  - -0.17920345067977905
  - -0.3174835443496704
  - 0.2773117125034332
  - -1.6013023853302002
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48209_blocks_own_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==4)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
