modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.8986814618110657
  - -0.07928092777729034
  - -1.1614410877227783
  - -0.0016460081096738577
  - 0.9987146854400635
  - 1.5123584270477295
  - -0.19269175827503204
  - -0.8779959678649902
  - 0.05442366003990173
  - 1.4838752746582031
  - -0.03261541575193405
  - -0.7315220236778259
  - -0.9107211828231812
  - 0.4098168909549713
  - 1.3240506649017334
  - -0.40427276492118835
  - 1.2374721765518188
  - -0.21803081035614014
  - -1.3908772468566895
  - 0.10385762155056
  - -0.1493995040655136
  - -0.2822476327419281
  - 0.7813608050346375
  - -0.9136610627174377
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48053_blocks_rent_1p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==5)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
