modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.17673267424106598
  - -0.9885612726211548
  - 1.1234097480773926
  - -0.00021645730885211378
  - 1.392397403717041
  - -0.5340390801429749
  - -2.005666971206665
  - 1.453744649887085
  - 0.06804349273443222
  - 1.6702311038970947
  - -1.0254157781600952
  - 0.5849490761756897
  - -0.6970577836036682
  - -2.6618032455444336
  - 0.19709601998329163
  - -0.051955074071884155
  - 0.052680063992738724
  - -0.18367435038089752
  - 0.2103244811296463
  - -0.0942753404378891
  - -0.015267353504896164
  - -0.04433753341436386
  - 0.2597195506095886
  - -0.24974291026592255
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48055_blocks_own_1p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==2)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
