modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.5838689804077148
  - 1.7293736934661865
  - -0.8286888599395752
  - -2.092665433883667
  - -1.5575288534164429
  - 0.8497724533081055
  - -0.0235088262706995
  - -2.242516279220581
  - -0.6550880074501038
  - 1.9691258668899536
  - -0.15061639249324799
  - -0.1680314540863037
  - -0.593018114566803
  - -0.956068754196167
  - 0.41941195726394653
  - -0.11808468401432037
  - 0.5524723529815674
  - -0.42748671770095825
  - -0.4436091482639313
  - -0.1433345079421997
  - -0.08552395552396774
  - -0.14228709042072296
  - 0.15741559863090515
  - -0.16127978265285492
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48021_blocks_rent_1p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==6)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
