modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.27977633476257324
  - -0.0821809396147728
  - 1.1539561748504639
  - -0.07029839605093002
  - -0.09340318292379379
  - -0.20733511447906494
  - -0.0417671874165535
  - -0.3467261493206024
  - 0.6293666958808899
  - 0.6416937112808228
  - -0.004621435422450304
  - -0.6086530089378357
  - -0.05610045790672302
  - -0.03498318791389465
  - 1.0508671998977661
  - 3.4447450637817383
  - 1.1759899854660034
  - -0.18296456336975098
  - 0.22112691402435303
  - 0.5281405448913574
  - 0.842202365398407
  - 0.3334667682647705
  - 0.24250788986682892
  - 2.4445583820343018
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48453_blocks_rent_2p_54less_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==7)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
