modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -1.092607021331787
  - 0.5056250095367432
  - -0.16278648376464844
  - -1.8928766250610352
  - -0.5794477462768555
  - 1.1193907260894775
  - -1.3678339719772339
  - 0.8485375046730042
  - 0.2741398215293884
  - 0.8339310884475708
  - -1.69834303855896
  - -0.41200771927833557
  - 0.02765037678182125
  - 0.713748574256897
  - 2.5301249027252197
  - -2.001055955886841
  - 1.7911053895950317
  - -0.36925241351127625
  - -0.2741774916648865
  - -0.00639315415173769
  - -0.1167406216263771
  - -0.09409971535205841
  - 0.09443147480487823
  - -2.13326096534729
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: hlcm_48209_blocks_rent_2p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==8)
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
