modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.4355927109718323
  - -0.02370762825012207
  - 0.3623991012573242
  - 1.3498216503649019e-05
  - -0.011666769161820412
  - 0.04339059069752693
  - 0.6399607062339783
  - 0.8321440815925598
  - -0.1738406866788864
  - -0.17688269913196564
  - -0.3111102879047394
  - -0.5052757859230042
  - 0.18934141099452972
  - -0.47956398129463196
  - -0.10169396549463272
  - 0.12514232099056244
  - -0.2238837629556656
  - -0.18545310199260712
  - -0.32248371839523315
  - -0.23105324804782867
  - -0.21787331998348236
  - -0.2371339350938797
  - 0.3123459815979004
  - 0.22762168943881989
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: rdplcm_48053_blocks_mf_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "48053")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & ((building_type=="mf_own")
    | (building_type=="mf_rent"))
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
