modelmanager_version: 0.2.dev9

saved_object:
    filters: 
    - age > 15
    - student == 1
    fitted_parameters:
    - 1.28
    - 2.39
    - 3.18
    - 0.399
    - 0.783
    - -1.1
    - -1.0
    - -1.12
    model_expression: stop ~ agebin2 + agebin3 + agebin4 + employbin1
        + employbin2 + marital1 + marital4 + 1
    name: education
    out_column: stop
    out_filters:
    - age > 15
    - student == 1
    out_tables: persons
    out_transform: null
    out_value_false: 0
    out_value_true: 1
    tables: persons
    summary_table: null
    tags: []
    template: BinaryLogitStep
    template_version: 0.2.dev9