modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.49871665239334106
  - -1.2500293254852295
  - -0.3154495358467102
  - 1.6115528345108032
  - 0.5254605412483215
  - -0.3744031488895416
  - -0.4767293632030487
  - -0.3101186454296112
  - 0.2914807200431824
  - 0.3167281150817871
  - -0.28433704376220703
  - 0.6974717378616333
  - 0.2821330726146698
  - 0.5190898776054382
  - 0.03714535012841225
  - 0.29801177978515625
  - 0.18562299013137817
  - 0.1770799607038498
  - 0.19746147096157074
  - -0.3805912137031555
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48055_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
