modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.2614213228225708
  - -0.657467782497406
  - 0.8542090654373169
  - 0.7142924070358276
  - 1.1101794242858887
  - -0.22327746450901031
  - -0.0012398280669003725
  - -0.01942707598209381
  - -0.5057288408279419
  - 0.6780809760093689
  - -0.053514473140239716
  - 0.00184193579480052
  - -1.0022326707839966
  - 0.40880489349365234
  - 1.4229252338409424
  - 0.9149288535118103
  - 1.439393401145935
  - 1.1232105493545532
  - 1.0319336652755737
  - -1.0086591243743896
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48491_blocks_3_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48491")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (agg_sector=="3")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
