modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48209")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48209") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12323448398185513
    - 0.6663421590785539
    - 0.17910075350196736
    - -9.64613908637951e-06
    - -0.030013723907020895
    - 0.9349093367015718
    - 0.17043867153136896
    - 0.3092018868022302
    - 0.27007681338046674
    - 0.12537653663238418
    - 0.5764055772480228
    - -0.08874797091820585
    - -0.22723870916847463
    - 0.06644384718902473
    - -0.2272239202283223
    - -0.0326485933517406
    - 1.0270822830750366
    - 2.1916631154416044
    - 0.7032994790942614
    - -2.876540370790903
    - -0.07450892063864566
    - -2.616874099826739
    - 2.1609092654326405
    - -0.24586456189267533
    - -5.31889794709819
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48209_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,410\nModel:\
        \         Multinomial Logit   Df Residuals:              1,385\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.153\nTime:          \
        \            01:37   Pseudo R-bar-squ.:         0.149\nAIC:              \
        \    11,054.109   Log-Likelihood:       -5,502.054\nBIC:                 \
        \ 11,185.392   LL-Null:              -6,493.290\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1232     0.002   -52.893     0.000\
        \             \nst_bg_mean_age_of_head                    0.6663     0.068\
        \     9.847     0.000             \nst_bg_mean_children                  \
        \     0.1791     0.055     3.241     0.001             \nst_bg_mean_year_built\
        \                    -0.0000     0.075    -0.000     1.000             \n\
        st_bg_median_value_13_acs                -0.0300     0.076    -0.397     0.691\
        \             \nst_bg_prop_hh_rent                        0.9349     0.117\
        \     7.998     0.000             \nst_bg_prop_units_sf                  \
        \     0.1704     0.064     2.668     0.008             \nst_bg_ratio_households_to_units\
        \           0.3092     0.089     3.478     0.001             \nst_bg_total_units\
        \                         0.2701     0.053     5.116     0.000           \
        \  \nst_density_jobs_90pct_plus                0.1254     0.027     4.665\
        \     0.000             \nst_density_units_90pct_plus               0.5764\
        \     0.023    25.565     0.000             \nst_pred_built_out_sf       \
        \              -0.0887     0.052    -1.713     0.087             \nst_pred_rich_owned_antique\
        \               -0.2272     0.100    -2.274     0.023             \nst_tracts_income_segment_1_hh\
        \             0.0664     0.032     2.098     0.036             \nst_tracts_income_segment_6_hh\
        \            -0.2272     0.096    -2.372     0.018             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.0326     0.114    -0.287     0.774             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     1.0271     0.871     1.179     0.238             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           2.1917     2.323     0.944     0.345             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.7033     0.584     1.205     0.228             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -2.8765     0.957    -3.006     0.003             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.0745     0.467    -0.160     0.873             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -2.6169     2.441    -1.072     0.284             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           2.1609     1.791     1.207     0.228             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.2459     0.199    -1.237     0.216             \nst_zones_total_units_sum_10_min_sov_c\
        \    -5.3189     0.902    -5.895     0.000             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
