modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48491")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48491") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15106308440154662
    - -0.5204636933253199
    - -0.34516495564189226
    - -0.019872575693802907
    - -0.5091143772868805
    - -0.37603723604589717
    - 0.020552868918353766
    - 0.3446047423721032
    - 0.17681799817696633
    - 0.00867646661664549
    - 0.2023089697889876
    - 0.026236547219704698
    - 0.09402984915679136
    - -0.029089306604465938
    - -0.0596031770186309
    - 0.17470596201816985
    - 0.7676305436663792
    - -1.6940498095456025
    - -0.18024331351448658
    - 0.06271889904142212
    - -0.38028096599943256
    - -0.3995046524346768
    - 1.4468701658930934
    - -0.49084610177644045
    - -1.02178388534632
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48491_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          6,482\nModel:\
        \         Multinomial Logit   Df Residuals:              6,457\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.124\nTime:          \
        \            00:15   Pseudo R-bar-squ.:         0.124\nAIC:              \
        \    52,324.687   Log-Likelihood:      -26,137.344\nBIC:                 \
        \ 52,494.107   LL-Null:             -29,850.713\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1511     0.001   -105.206    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.5205   \
        \  0.031    -16.965     0.000             \nst_bg_mean_children          \
        \            -0.3452     0.025    -14.040     0.000             \nst_bg_mean_year_built\
        \                    -0.0199     0.022     -0.923     0.356             \n\
        st_bg_median_value_13_acs                -0.5091     0.043    -11.897    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.3760   \
        \  0.042     -8.983     0.000             \nst_bg_prop_units_sf          \
        \             0.0206     0.039      0.526     0.599             \nst_bg_ratio_households_to_units\
        \           0.3446     0.039      8.876     0.000             \nst_bg_total_units\
        \                         0.1768     0.024      7.272     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0087     0.013      0.658\
        \     0.511             \nst_density_units_90pct_plus               0.2023\
        \     0.010     20.421     0.000             \nst_pred_built_out_sf      \
        \                0.0262     0.009      3.047     0.002             \nst_pred_rich_owned_antique\
        \                0.0940     0.013      7.364     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0291     0.039     -0.754     0.451             \nst_tracts_income_segment_6_hh\
        \            -0.0596     0.029     -2.072     0.038             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.1747     0.046      3.787     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.7676     0.102      7.489     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -1.6940     0.211     -8.022     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \          -0.1802     0.100     -1.810     0.070             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.0627     0.021      2.955     0.003             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.3803     0.149     -2.544     0.011             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.3995     0.242     -1.651     0.099             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           1.4469     0.356      4.066     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.4908     0.081     -6.088     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -1.0218     0.134     -7.600     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
