modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15610328711342955
    - 0.6364677503987911
    - -0.21151149339275516
    - -0.1330476214596584
    - 0.05057371319158737
    - 0.8465605972687077
    - -0.21086571015602518
    - 0.12249804101552589
    - 0.10919776331459591
    - 0.2807383486971115
    - 0.7213950912185582
    - -0.15143672354340618
    - -0.22374432519832443
    - 0.0049842840930184994
    - 0.03233384811374267
    - -0.13386691834155293
    - 0.0005870500224444105
    - 0.13051911137547087
    - 0.06992628351067245
    - 0.06209984963552113
    - 0.07976300041422764
    - -0.26275090785830646
    - -0.3105649835386304
    - 0.16057766571688073
    - -0.42255421247046554
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         19,147\nModel:\
        \         Multinomial Logit   Df Residuals:             19,122\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.305\nTime:          \
        \            01:20   Pseudo R-bar-squ.:         0.305\nAIC:              \
        \   122,645.461   Log-Likelihood:      -61,297.731\nBIC:                 122,841.959\
        \   LL-Null:             -88,175.194\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1561     0.001   -136.815    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.6365   \
        \  0.013     48.023     0.000             \nst_bg_mean_children          \
        \            -0.2115     0.010    -20.154     0.000             \nst_bg_mean_year_built\
        \                    -0.1330     0.016     -8.551     0.000             \n\
        st_bg_median_value_13_acs                 0.0506     0.010      5.065    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.8466   \
        \  0.022     37.912     0.000             \nst_bg_prop_units_sf          \
        \            -0.2109     0.020    -10.379     0.000             \nst_bg_ratio_households_to_units\
        \           0.1225     0.014      8.607     0.000             \nst_bg_total_units\
        \                         0.1092     0.010     10.611     0.000          \
        \   \nst_density_jobs_90pct_plus                0.2807     0.005     51.370\
        \     0.000             \nst_density_units_90pct_plus               0.7214\
        \     0.006    126.786     0.000             \nst_pred_built_out_sf      \
        \               -0.1514     0.014    -10.771     0.000             \nst_pred_rich_owned_antique\
        \               -0.2237     0.039     -5.773     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0050     0.008      0.592     0.554             \nst_tracts_income_segment_6_hh\
        \             0.0323     0.014      2.345     0.019             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.1339     0.022     -6.220     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.0006     0.028      0.021     0.983             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           0.1305     0.025      5.121     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.0699     0.017      4.096     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.0621     0.014      4.598     0.000             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.0798     0.041      1.947     0.052             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.2628     0.053     -4.969     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.3106     0.037     -8.298     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      0.1606     0.027      5.907     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.4226     0.042    -10.081     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
