modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48209")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48209") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.11426390768301925
    - 0.10480248439556757
    - -0.18745578816146397
    - 0.06070394615377678
    - -0.2267340927448884
    - -0.5806043431003275
    - -0.18153440963569464
    - 0.10498898441816769
    - 0.13428811311671573
    - -0.017865158201281754
    - 0.21354582102369732
    - 0.052604788029827446
    - -0.04213749189607281
    - 0.172017550064362
    - -0.3390581399117849
    - 0.4612746629116216
    - 2.607221774574722
    - -5.823728158506953
    - -0.22525993755124082
    - 0.14242984091916028
    - -2.892646207677357
    - -0.8636877384669166
    - 6.7122292038456965
    - -0.4772629214905923
    - -6.852702965960226
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48209_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,336\nModel:\
        \         Multinomial Logit   Df Residuals:              2,311\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.105\nTime:          \
        \            00:14   Pseudo R-bar-squ.:         0.103\nAIC:              \
        \    19,308.326   Log-Likelihood:       -9,629.163\nBIC:                 \
        \ 19,452.231   LL-Null:             -10,757.678\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1143     0.002   -64.323     0.000\
        \             \nst_bg_mean_age_of_head                    0.1048     0.055\
        \     1.906     0.057             \nst_bg_mean_children                  \
        \    -0.1875     0.043    -4.319     0.000             \nst_bg_mean_year_built\
        \                     0.0607     0.060     1.011     0.312             \n\
        st_bg_median_value_13_acs                -0.2267     0.059    -3.813     0.000\
        \             \nst_bg_prop_hh_rent                       -0.5806     0.078\
        \    -7.431     0.000             \nst_bg_prop_units_sf                  \
        \    -0.1815     0.043    -4.269     0.000             \nst_bg_ratio_households_to_units\
        \           0.1050     0.063     1.656     0.098             \nst_bg_total_units\
        \                         0.1343     0.040     3.386     0.001           \
        \  \nst_density_jobs_90pct_plus               -0.0179     0.029    -0.613\
        \     0.540             \nst_density_units_90pct_plus               0.2135\
        \     0.023     9.298     0.000             \nst_pred_built_out_sf       \
        \               0.0526     0.026     2.027     0.043             \nst_pred_rich_owned_antique\
        \               -0.0421     0.031    -1.360     0.174             \nst_tracts_income_segment_1_hh\
        \             0.1720     0.029     5.876     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.3391     0.063    -5.412     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.4613     0.087     5.328     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     2.6072     0.612     4.258     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -5.8237     2.129    -2.735     0.006             \nst_zones_jobs_1_sum_5_min_sov_c\
        \          -0.2253     0.472    -0.477     0.633             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.1424     0.793     0.180     0.858             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -2.8926     0.452    -6.401     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.8637     2.670    -0.323     0.746             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           6.7122     2.074     3.236     0.001             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.4773     0.134    -3.571     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -6.8527     0.701    -9.771     0.000             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
