modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48491")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48491") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1883991852084186
    - -0.32022470445019363
    - -0.2891429881026064
    - 0.005662976813785968
    - -0.3067474203185254
    - 0.601134216861011
    - -0.1521141503815953
    - 0.2892586461596677
    - 0.07451427752649763
    - 0.22086725637221907
    - 0.6023810511358454
    - -0.20827739437227835
    - -0.12120367500601108
    - -0.26998241911326615
    - 0.15304067625651901
    - -0.08461940513051046
    - 1.1922610606237796
    - -1.3964932184749879
    - 0.2936457491622285
    - 0.03631678590748234
    - -0.38055607964924293
    - -0.06795534449863172
    - -0.19106490227047565
    - -0.5311310345298008
    - -1.3911957988927113
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48491_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          9,489\nModel:\
        \         Multinomial Logit   Df Residuals:              9,464\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.402\nTime:          \
        \            01:17   Pseudo R-bar-squ.:         0.401\nAIC:              \
        \    52,342.810   Log-Likelihood:      -26,146.405\nBIC:                 \
        \ 52,521.757   LL-Null:             -43,698.460\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1884     0.002   -123.744    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.3202   \
        \  0.034     -9.367     0.000             \nst_bg_mean_children          \
        \            -0.2891     0.023    -12.609     0.000             \nst_bg_mean_year_built\
        \                     0.0057     0.023      0.245     0.806             \n\
        st_bg_median_value_13_acs                -0.3067     0.042     -7.251    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.6011   \
        \  0.037     16.056     0.000             \nst_bg_prop_units_sf          \
        \            -0.1521     0.034     -4.455     0.000             \nst_bg_ratio_households_to_units\
        \           0.2893     0.023     12.793     0.000             \nst_bg_total_units\
        \                         0.0745     0.017      4.262     0.000          \
        \   \nst_density_jobs_90pct_plus                0.2209     0.008     27.170\
        \     0.000             \nst_density_units_90pct_plus               0.6024\
        \     0.008     79.570     0.000             \nst_pred_built_out_sf      \
        \               -0.2083     0.014    -15.215     0.000             \nst_pred_rich_owned_antique\
        \               -0.1212     0.055     -2.204     0.028             \nst_tracts_income_segment_1_hh\
        \            -0.2700     0.035     -7.769     0.000             \nst_tracts_income_segment_6_hh\
        \             0.1530     0.031      4.967     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.0846     0.048     -1.758     0.079             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     1.1923     0.117     10.205     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -1.3965     0.193     -7.232     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.2936     0.078      3.761     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.0363     0.022      1.639     0.101             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.3806     0.129     -2.957     0.003             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.0680     0.222     -0.305     0.760             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.1911     0.320     -0.596     0.551             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.5311     0.073     -7.258     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -1.3912     0.133    -10.461     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
