modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48021")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48021") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.13343523508078745
    - -0.3712226755250261
    - -0.06931475671343462
    - 0.04953369924100344
    - -0.2994887498488277
    - -0.3467462456933384
    - 0.322003184469477
    - 0.26152459028776326
    - 0.13220269308641855
    - -0.19080807649512066
    - 0.248053664477067
    - -3.0649751658910023
    - -0.014953717324245377
    - -0.21032374308917337
    - -0.5590345513103604
    - -0.49148489363700276
    - 7.3615829827883195
    - 4.064314066998142
    - 0.23789482717027632
    - 15.965735352953692
    - -5.721746353539468
    - 11.450091287671336
    - -21.8897399604432
    - -2.1059113271720165
    - -12.757778002749061
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48021_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,252\nModel:\
        \         Multinomial Logit   Df Residuals:              1,227\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.099\nTime:          \
        \            00:13   Pseudo R-bar-squ.:         0.095\nAIC:              \
        \    10,434.096   Log-Likelihood:       -5,192.048\nBIC:                 \
        \ 10,562.409   LL-Null:              -5,765.673\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1334     0.002   -73.563    \
        \ 0.000             \nst_bg_mean_age_of_head                    -0.3712  \
        \   0.177    -2.098     0.036             \nst_bg_mean_children          \
        \             -0.0693     0.093    -0.749     0.454             \nst_bg_mean_year_built\
        \                      0.0495     0.069     0.722     0.471             \n\
        st_bg_median_value_13_acs                 -0.2995     0.175    -1.710    \
        \ 0.087             \nst_bg_prop_hh_rent                        -0.3467  \
        \   0.267    -1.298     0.194             \nst_bg_prop_units_sf          \
        \              0.3220     0.066     4.886     0.000             \nst_bg_ratio_households_to_units\
        \            0.2615     0.093     2.814     0.005             \nst_bg_total_units\
        \                          0.1322     0.084     1.576     0.115          \
        \   \nst_density_jobs_90pct_plus                -0.1908     0.067    -2.865\
        \     0.004             \nst_density_units_90pct_plus                0.2481\
        \     0.062     3.984     0.000             \nst_pred_built_out_sf       \
        \               -3.0650    25.216    -0.122     0.903             \nst_pred_rich_owned_antique\
        \                -0.0150     0.031    -0.478     0.633             \nst_tracts_income_segment_1_hh\
        \             -0.2103     0.170    -1.238     0.216             \nst_tracts_income_segment_6_hh\
        \             -0.5590     0.206    -2.715     0.007             \nst_zones_density_units_ave_5_min_sov_c\
        \    -0.4915     0.351    -1.402     0.161             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      7.3616     4.608     1.598     0.110             \nst_zones_jobs_0_sum_5_min_sov_c\
        \            4.0643    31.486     0.129     0.897             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            0.2379     2.036     0.117     0.907             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           15.9657    13.463     1.186     0.236             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -5.7217     7.298    -0.784     0.433             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           11.4501    27.262     0.420     0.674             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -21.8897    11.931    -1.835     0.067             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -2.1059     1.377    -1.530     0.126             \nst_zones_total_units_sum_10_min_sov_c\
        \    -12.7578     3.996    -3.193     0.001             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
