modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48491")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48491") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.19576457971689118
    - 0.503547572920151
    - -0.14480189165838753
    - 0.02588415880526859
    - -0.2726754168432313
    - 0.8576779947499261
    - -0.2631611552046341
    - 0.34487046320420117
    - 0.08249372951838282
    - 0.23887805912756516
    - 0.6070798717709692
    - -0.21637820217055484
    - -0.10279463127195111
    - -0.1571904413350394
    - 0.2540218094507853
    - 0.3385032612964029
    - 0.6736214016610826
    - -1.1135076209715316
    - 0.6614165654084896
    - -0.09244170970029704
    - -0.15635621832783742
    - 1.7336387602547845
    - -3.0723203003071933
    - -0.0939321138630218
    - -1.2267180531483775
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48491_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          6,046\nModel:\
        \         Multinomial Logit   Df Residuals:              6,021\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.345\nTime:          \
        \            01:21   Pseudo R-bar-squ.:         0.344\nAIC:              \
        \    36,550.225   Log-Likelihood:      -18,250.112\nBIC:                 \
        \ 36,717.904   LL-Null:             -27,842.859\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1958     0.002   -105.825    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.5035   \
        \  0.032     15.854     0.000             \nst_bg_mean_children          \
        \            -0.1448     0.030     -4.802     0.000             \nst_bg_mean_year_built\
        \                     0.0259     0.024      1.087     0.277             \n\
        st_bg_median_value_13_acs                -0.2727     0.051     -5.337    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.8577   \
        \  0.045     19.241     0.000             \nst_bg_prop_units_sf          \
        \            -0.2632     0.042     -6.320     0.000             \nst_bg_ratio_households_to_units\
        \           0.3449     0.031     11.028     0.000             \nst_bg_total_units\
        \                         0.0825     0.022      3.703     0.000          \
        \   \nst_density_jobs_90pct_plus                0.2389     0.010     23.756\
        \     0.000             \nst_density_units_90pct_plus               0.6071\
        \     0.010     62.247     0.000             \nst_pred_built_out_sf      \
        \               -0.2164     0.017    -12.857     0.000             \nst_pred_rich_owned_antique\
        \               -0.1028     0.043     -2.415     0.016             \nst_tracts_income_segment_1_hh\
        \            -0.1572     0.043     -3.688     0.000             \nst_tracts_income_segment_6_hh\
        \             0.2540     0.042      6.010     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.3385     0.054      6.288     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.6736     0.157      4.296     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -1.1135     0.217     -5.135     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.6614     0.104      6.365     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -0.0924     0.030     -3.104     0.002             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.1564     0.174     -0.901     0.368             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           1.7336     0.284      6.105     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -3.0723     0.408     -7.538     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.0939     0.088     -1.065     0.287             \nst_zones_total_units_sum_10_min_sov_c\
        \    -1.2267     0.183     -6.717     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
