modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48021")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48021") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.13965944133072922
    - 0.5530462596384813
    - 0.10917190326929659
    - -0.033994982422763366
    - 0.47258529361852475
    - 1.9197944341442643
    - 0.11788722834803565
    - 0.7394258514264063
    - -0.0374212449283427
    - -0.09207258814795276
    - 0.6401956974485985
    - 0.04587498954214454
    - -0.20452865700497252
    - -0.02732039242104611
    - -0.29821193748900027
    - -0.32918784286271535
    - -1.0612018536856953
    - -38.82353459389208
    - 5.284528051537281
    - 8.719213247266351
    - -3.634450114982033
    - 31.863147545062038
    - -63.07760181619138
    - -1.8215227009397863
    - -14.379717150359912
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48021_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            666\nModel:\
        \         Multinomial Logit   Df Residuals:                641\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.151\nTime:          \
        \            01:35   Pseudo R-bar-squ.:         0.143\nAIC:              \
        \     5,256.161   Log-Likelihood:       -2,603.081\nBIC:                 \
        \  5,368.694   LL-Null:              -3,067.043\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1397     0.003   -49.845    \
        \ 0.000             \nst_bg_mean_age_of_head                     0.5530  \
        \   0.292     1.895     0.058             \nst_bg_mean_children          \
        \              0.1092     0.155     0.706     0.480             \nst_bg_mean_year_built\
        \                     -0.0340     0.088    -0.385     0.700             \n\
        st_bg_median_value_13_acs                  0.4726     0.226     2.092    \
        \ 0.036             \nst_bg_prop_hh_rent                         1.9198  \
        \   0.417     4.608     0.000             \nst_bg_prop_units_sf          \
        \              0.1179     0.090     1.311     0.190             \nst_bg_ratio_households_to_units\
        \            0.7394     0.148     5.008     0.000             \nst_bg_total_units\
        \                         -0.0374     0.137    -0.274     0.784          \
        \   \nst_density_jobs_90pct_plus                -0.0921     0.066    -1.405\
        \     0.160             \nst_density_units_90pct_plus                0.6402\
        \     0.046    13.798     0.000             \nst_pred_built_out_sf       \
        \                0.0459     0.234     0.196     0.844             \nst_pred_rich_owned_antique\
        \                -0.2045     0.098    -2.094     0.036             \nst_tracts_income_segment_1_hh\
        \             -0.0273     0.274    -0.100     0.921             \nst_tracts_income_segment_6_hh\
        \             -0.2982     0.288    -1.036     0.300             \nst_zones_density_units_ave_5_min_sov_c\
        \    -0.3292     0.520    -0.634     0.526             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     -1.0612     6.073    -0.175     0.861             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -38.8235    52.593    -0.738     0.460             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            5.2845     1.543     3.424     0.001             \nst_zones_jobs_2_sum_5_min_sov_c\
        \            8.7192    20.285     0.430     0.667             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -3.6345    11.716    -0.310     0.756             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           31.8631    41.735     0.763     0.445             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -63.0776    15.478    -4.075     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -1.8215     2.066    -0.881     0.378             \nst_zones_total_units_sum_10_min_sov_c\
        \    -14.3797     6.161    -2.334     0.020             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
