modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48053")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48053") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1489157470583542
    - 0.3045392270400328
    - 0.8124722917176572
    - 0.014633824364185975
    - -0.04977513908557809
    - 1.4021721533695368
    - 0.2990275418175893
    - -0.2984658592633172
    - 2.2215219892177616
    - -0.11880385138992981
    - 0.5699817222963925
    - -0.05382428290316719
    - -0.1969518186452684
    - -0.438791781242126
    - -0.9032028687480416
    - 1.7754369862072819
    - -19.480224781843752
    - -53.51395441980968
    - -1.478158459984103
    - -17.21057697016658
    - -19.40579619946991
    - 43.11369197510618
    - 15.77064154331576
    - 16.560636566952322
    - -25.188516591550147
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48053_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,017\nModel:\
        \         Multinomial Logit   Df Residuals:              1,992\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.218\nTime:          \
        \            01:25   Pseudo R-bar-squ.:         0.216\nAIC:              \
        \    14,573.679   Log-Likelihood:       -7,261.839\nBIC:                 \
        \ 14,713.913   LL-Null:              -9,288.628\n=============================================================================================\n\
        \                                             coef   std err          z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1489     0.001   -110.309   \
        \  0.000             \nst_bg_mean_age_of_head                     0.3045 \
        \    0.138      2.211     0.027             \nst_bg_mean_children        \
        \                0.8125     0.120      6.761     0.000             \nst_bg_mean_year_built\
        \                      0.0146     0.113      0.129     0.897             \n\
        st_bg_median_value_13_acs                 -0.0498     0.137     -0.364   \
        \  0.716             \nst_bg_prop_hh_rent                         1.4022 \
        \    0.145      9.646     0.000             \nst_bg_prop_units_sf        \
        \                0.2990     0.118      2.535     0.011             \nst_bg_ratio_households_to_units\
        \           -0.2985     0.051     -5.885     0.000             \nst_bg_total_units\
        \                          2.2215     0.211     10.505     0.000         \
        \    \nst_density_jobs_90pct_plus                -0.1188     0.034     -3.528\
        \     0.000             \nst_density_units_90pct_plus                0.5700\
        \     0.030     19.143     0.000             \nst_pred_built_out_sf      \
        \                -0.0538     0.081     -0.662     0.508             \nst_pred_rich_owned_antique\
        \                -0.1970     0.096     -2.048     0.041             \nst_tracts_income_segment_1_hh\
        \             -0.4388     0.074     -5.891     0.000             \nst_tracts_income_segment_6_hh\
        \             -0.9032     0.175     -5.168     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \     1.7754     0.262      6.766     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \    -19.4802     5.127     -3.800     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -53.5140     6.943     -7.708     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -1.4782     1.787     -0.827     0.408             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -17.2106     5.757     -2.990     0.003             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -19.4058     5.982     -3.244     0.001             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           43.1137    17.209      2.505     0.012             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           15.7706    13.868      1.137     0.255             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      16.5606     5.409      3.062     0.002             \nst_zones_total_units_sum_10_min_sov_c\
        \    -25.1885     6.747     -3.733     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
