modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48209")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48209") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15338809009127483
    - -0.00587670213028411
    - -0.273235294323375
    - 0.1783724505749179
    - 0.07920493874502144
    - 0.5100970892023361
    - 0.10154327287590113
    - 0.15864799815082273
    - -0.0401161990902849
    - 0.19225879912674965
    - 0.6882844283951212
    - -0.31180982768276405
    - -0.21837797816671836
    - 0.11204658932497724
    - -0.022133804662625427
    - -0.03444121528951152
    - -2.9425295304895953
    - 5.0853490302283095
    - -0.7405752088719508
    - 2.2191663690473455
    - -0.5883561588564675
    - -1.709077800719045
    - 0.5293596877191935
    - -0.16173905854615275
    - -3.8440920143730986
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48209_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          4,446\nModel:\
        \         Multinomial Logit   Df Residuals:              4,421\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.344\nTime:          \
        \            01:15   Pseudo R-bar-squ.:         0.342\nAIC:              \
        \    26,926.735   Log-Likelihood:      -13,438.368\nBIC:                 \
        \ 27,086.729   LL-Null:             -20,474.587\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1534     0.002   -90.920     0.000\
        \             \nst_bg_mean_age_of_head                   -0.0059     0.036\
        \    -0.162     0.872             \nst_bg_mean_children                  \
        \    -0.2732     0.038    -7.128     0.000             \nst_bg_mean_year_built\
        \                     0.1784     0.049     3.671     0.000             \n\
        st_bg_median_value_13_acs                 0.0792     0.058     1.358     0.175\
        \             \nst_bg_prop_hh_rent                        0.5101     0.063\
        \     8.157     0.000             \nst_bg_prop_units_sf                  \
        \     0.1015     0.036     2.843     0.004             \nst_bg_ratio_households_to_units\
        \           0.1586     0.056     2.855     0.004             \nst_bg_total_units\
        \                        -0.0401     0.030    -1.354     0.176           \
        \  \nst_density_jobs_90pct_plus                0.1923     0.014    14.211\
        \     0.000             \nst_density_units_90pct_plus               0.6883\
        \     0.013    53.150     0.000             \nst_pred_built_out_sf       \
        \              -0.3118     0.054    -5.819     0.000             \nst_pred_rich_owned_antique\
        \               -0.2184     0.068    -3.213     0.001             \nst_tracts_income_segment_1_hh\
        \             0.1120     0.016     7.194     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.0221     0.064    -0.345     0.730             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.0344     0.063    -0.546     0.585             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \    -2.9425     0.842    -3.496     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           5.0853     1.559     3.262     0.001             \nst_zones_jobs_1_sum_5_min_sov_c\
        \          -0.7406     0.390    -1.901     0.057             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           2.2192     0.716     3.100     0.002             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.5884     0.281    -2.091     0.036             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -1.7091     1.400    -1.221     0.222             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           0.5294     0.991     0.534     0.593             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.1617     0.173    -0.935     0.350             \nst_zones_total_units_sum_10_min_sov_c\
        \    -3.8441     0.677    -5.679     0.000             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
