modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48055") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.10516890843320385
    - -0.8067110574277974
    - 0.04715287993264391
    - 0.4078603705284044
    - 0.569015320560502
    - -0.8972698854607911
    - 0.8247986454242224
    - 0.11386410289891333
    - 1.0457913221539006
    - -0.17304222315147338
    - 0.190569299951288
    - 0.16769643201647247
    - -0.10575384795386468
    - -0.2586109472698032
    - -3.7982789011249403
    - 1.25962389551514
    - 31.585679900101482
    - -460.40126732906685
    - -44.653465748301
    - 9.515048613207764
    - -63.33110136623603
    - 403.80398195899727
    - 78.58799686065453
    - -3.9024023665915055
    - -22.10971524057214
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48055_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            466\nModel:\
        \         Multinomial Logit   Df Residuals:                441\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.129\nTime:          \
        \            00:14   Pseudo R-bar-squ.:         0.117\nAIC:              \
        \     3,790.441   Log-Likelihood:       -1,870.221\nBIC:                 \
        \  3,894.046   LL-Null:              -2,146.009\n=============================================================================================\n\
        \                                              coef   std err         z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov     -0.1052     0.003   -30.626   \
        \  0.000             \nst_bg_mean_age_of_head                     -0.8067\
        \     0.237    -3.409     0.001             \nst_bg_mean_children        \
        \                 0.0472     0.224     0.211     0.833             \nst_bg_mean_year_built\
        \                       0.4079     0.180     2.265     0.024             \n\
        st_bg_median_value_13_acs                   0.5690     0.453     1.256   \
        \  0.209             \nst_bg_prop_hh_rent                         -0.8973\
        \     0.357    -2.512     0.012             \nst_bg_prop_units_sf        \
        \                 0.8248     0.159     5.173     0.000             \nst_bg_ratio_households_to_units\
        \             0.1139     0.262     0.435     0.664             \nst_bg_total_units\
        \                           1.0458     0.216     4.847     0.000         \
        \    \nst_density_jobs_90pct_plus                 -0.1730     0.092    -1.874\
        \     0.061             \nst_density_units_90pct_plus                 0.1906\
        \     0.083     2.297     0.022             \nst_pred_built_out_sf       \
        \                 0.1677     0.113     1.478     0.140             \nst_pred_rich_owned_antique\
        \                 -0.1058     0.073    -1.443     0.149             \nst_tracts_income_segment_1_hh\
        \              -0.2586     0.222    -1.166     0.244             \nst_tracts_income_segment_6_hh\
        \              -3.7983     0.557    -6.816     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \      1.2596     0.547     2.304     0.021             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      31.5857    13.320     2.371     0.018             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -460.4013    81.741    -5.632     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -44.6535     5.549    -8.048     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \             9.5150     9.775     0.973     0.330             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -63.3311    10.290    -6.154     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           403.8040    70.826     5.701     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \            78.5880    24.235     3.243     0.001             \nst_zones_total_jobs_sum_20_min_sov_c\
        \       -3.9024     1.830    -2.133     0.033             \nst_zones_total_units_sum_10_min_sov_c\
        \     -22.1097     4.091    -5.404     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
