modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.21929638885296185
    - -0.18523191987995632
    - 0.043760337994021285
    - -0.08565485366605982
    - -0.09412964606372176
    - 0.636986016521776
    - 0.04295018281210868
    - -0.036113622897199014
    - 0.11381936524649526
    - 0.16968518387990025
    - 0.5857139066892163
    - -0.03132294446596093
    - -0.13549451205074164
    - 0.05829787649595822
    - 0.03055496061149213
    - -0.19341390211426202
    - 0.12341020054686022
    - 0.16710079553903204
    - 0.08432786964077504
    - 0.040246661408039154
    - 0.09600952216140447
    - -0.024058334805921056
    - -0.7256733548467541
    - -0.22682355240024285
    - -0.44980564634034814
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         100,789\nModel:\
        \         Multinomial Logit   Df Residuals:             100,764\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-10-29   Pseudo R-squ.:              0.291\nTime:       \
        \               01:33   Pseudo R-bar-squ.:          0.291\nAIC:          \
        \       657,799.373   Log-Likelihood:      -328,874.687\nBIC:            \
        \     658,037.393   LL-Null:             -464,150.498\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.2193     0.001   -413.219    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1852   \
        \  0.007    -24.933     0.000             \nst_bg_mean_children          \
        \             0.0438     0.004     11.775     0.000             \nst_bg_mean_year_built\
        \                    -0.0857     0.006    -13.423     0.000             \n\
        st_bg_median_value_13_acs                -0.0941     0.005    -17.841    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.6370   \
        \  0.010     63.999     0.000             \nst_bg_prop_units_sf          \
        \             0.0430     0.008      5.105     0.000             \nst_bg_ratio_households_to_units\
        \          -0.0361     0.006     -6.157     0.000             \nst_bg_total_units\
        \                         0.1138     0.004     26.928     0.000          \
        \   \nst_density_jobs_90pct_plus                0.1697     0.002     68.738\
        \     0.000             \nst_density_units_90pct_plus               0.5857\
        \     0.002    251.147     0.000             \nst_pred_built_out_sf      \
        \               -0.0313     0.004     -7.099     0.000             \nst_pred_rich_owned_antique\
        \               -0.1355     0.012    -11.426     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0583     0.003     21.331     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0306     0.006      5.043     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.1934     0.009    -22.137     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.1234     0.013      9.447     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           0.1671     0.012     14.205     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.0843     0.008     10.831     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.0402     0.006      6.579     0.000             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.0960     0.018      5.283     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.0241     0.025     -0.947     0.343             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.7257     0.018    -40.678     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.2268     0.012    -19.488     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.4498     0.018    -25.484     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
