modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.11395213677470005
    - 0.3125223902498666
    - -0.0518286169713024
    - -0.1270298776266928
    - -0.013192402612658001
    - -0.2920370237477192
    - -0.17840040252292058
    - 0.18452778937166534
    - 0.10545818316552391
    - -0.05368224926522617
    - 0.19719760476283657
    - 0.0181767667029325
    - 0.016511381456548055
    - -0.014136591496358701
    - 0.03473007905255702
    - 0.03830375862332061
    - 0.11979326630688876
    - 0.11729214304621383
    - 0.13898292337731158
    - 0.002121594091969661
    - 0.03416035941466286
    - -0.3637370628340734
    - -0.23943195957018937
    - -0.08660418301756426
    - -0.19497744954126056
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          65,452\nModel:\
        \         Multinomial Logit   Df Residuals:              65,427\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-10-29   Pseudo R-squ.:              0.074\nTime:       \
        \               01:10   Pseudo R-bar-squ.:          0.074\nAIC:          \
        \       558,153.108   Log-Likelihood:      -279,051.554\nBIC:            \
        \     558,380.334   LL-Null:             -301,417.599\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1140     0.000   -281.848    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3125   \
        \  0.009     35.345     0.000             \nst_bg_mean_children          \
        \            -0.0518     0.005     -9.830     0.000             \nst_bg_mean_year_built\
        \                    -0.1270     0.008    -15.505     0.000             \n\
        st_bg_median_value_13_acs                -0.0132     0.005     -2.706    \
        \ 0.007             \nst_bg_prop_hh_rent                       -0.2920   \
        \  0.012    -25.236     0.000             \nst_bg_prop_units_sf          \
        \            -0.1784     0.009    -19.420     0.000             \nst_bg_ratio_households_to_units\
        \           0.1845     0.008     23.105     0.000             \nst_bg_total_units\
        \                         0.1055     0.005     22.147     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0537     0.004    -12.846\
        \     0.000             \nst_density_units_90pct_plus               0.1972\
        \     0.003     62.431     0.000             \nst_pred_built_out_sf      \
        \                0.0182     0.003      5.420     0.000             \nst_pred_rich_owned_antique\
        \                0.0165     0.003      4.820     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0141     0.007     -2.035     0.042             \nst_tracts_income_segment_6_hh\
        \             0.0347     0.005      6.631     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.0383     0.010      3.804     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.1198     0.014      8.393     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           0.1173     0.016      7.150     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.1390     0.010     13.310     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           0.0021     0.007      0.319     0.750             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.0342     0.026      1.321     0.186             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.3637     0.032    -11.257     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.2394     0.025     -9.760     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.0866     0.011     -8.123     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.1950     0.020     -9.772     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
