modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48053")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48053") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12205076729925672
    - -0.467493269656746
    - -0.01736420178065078
    - 0.2893042446228849
    - 0.47450977354428936
    - -0.6895531812164746
    - -0.03920468912428971
    - -0.07759836728324589
    - 1.2188528648621535
    - -0.050258598000157126
    - 0.08979577029162797
    - 0.02064569987199039
    - 0.04232482351831576
    - -0.02853693959645599
    - -0.5107691552966537
    - 2.8502054756982997
    - -22.46162630566251
    - -33.939535401661736
    - -6.3720798288802944
    - 1.6918828559177355
    - -31.17053681342144
    - 60.40136149382746
    - 14.441179786210174
    - 19.411647825306485
    - -17.432312474775813
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48053_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,914\nModel:\
        \         Multinomial Logit   Df Residuals:              1,889\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.074\nTime:          \
        \            00:19   Pseudo R-bar-squ.:         0.072\nAIC:              \
        \    16,366.675   Log-Likelihood:       -8,158.338\nBIC:                 \
        \ 16,505.599   LL-Null:              -8,814.296\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1221     0.002   -74.453    \
        \ 0.000             \nst_bg_mean_age_of_head                    -0.4675  \
        \   0.153    -3.061     0.002             \nst_bg_mean_children          \
        \             -0.0174     0.108    -0.161     0.872             \nst_bg_mean_year_built\
        \                      0.2893     0.126     2.297     0.022             \n\
        st_bg_median_value_13_acs                  0.4745     0.150     3.158    \
        \ 0.002             \nst_bg_prop_hh_rent                        -0.6896  \
        \   0.173    -3.981     0.000             \nst_bg_prop_units_sf          \
        \             -0.0392     0.098    -0.401     0.689             \nst_bg_ratio_households_to_units\
        \           -0.0776     0.046    -1.699     0.089             \nst_bg_total_units\
        \                          1.2189     0.209     5.821     0.000          \
        \   \nst_density_jobs_90pct_plus                -0.0503     0.040    -1.258\
        \     0.208             \nst_density_units_90pct_plus                0.0898\
        \     0.070     1.281     0.200             \nst_pred_built_out_sf       \
        \                0.0206     0.061     0.337     0.736             \nst_pred_rich_owned_antique\
        \                 0.0423     0.024     1.786     0.074             \nst_tracts_income_segment_1_hh\
        \             -0.0285     0.068    -0.419     0.675             \nst_tracts_income_segment_6_hh\
        \             -0.5108     0.177    -2.893     0.004             \nst_zones_density_units_ave_5_min_sov_c\
        \     2.8502     0.254    11.237     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \    -22.4616     6.066    -3.703     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -33.9395     8.637    -3.929     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -6.3721     1.809    -3.522     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \            1.6919     7.103     0.238     0.812             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -31.1705     7.087    -4.398     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           60.4014    15.359     3.933     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           14.4412    12.286     1.175     0.240             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      19.4116     4.832     4.017     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -17.4323     6.102    -2.857     0.004             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
