modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48491")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48491") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.14093161659186462
    - 0.34689760492550364
    - -0.15296815305964023
    - 0.12771373783140502
    - -0.5645188222594307
    - -0.13347450092954294
    - -0.05037056790845704
    - 0.4111036093570869
    - 0.11047165338547177
    - -0.001913902252314743
    - 0.19817818755230604
    - 0.05004679318832032
    - 0.07496944608440757
    - 0.00777221389231459
    - 0.00865149907018705
    - 0.3000275587905004
    - 0.3761579377259531
    - -0.6498599269054419
    - 0.3326096274467691
    - -0.06784420140242772
    - 0.3363386954294969
    - -0.0473051031948422
    - 0.020656002605595476
    - -0.04797911375752637
    - -0.8199032919865007
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48491_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48491") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48491") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         10,814\nModel:\
        \         Multinomial Logit   Df Residuals:             10,789\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.092\nTime:          \
        \            00:22   Pseudo R-bar-squ.:         0.091\nAIC:              \
        \    90,507.281   Log-Likelihood:      -45,228.641\nBIC:                 \
        \ 90,689.496   LL-Null:             -49,800.310\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1409     0.001   -133.186    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3469   \
        \  0.021     16.526     0.000             \nst_bg_mean_children          \
        \            -0.1530     0.021     -7.339     0.000             \nst_bg_mean_year_built\
        \                     0.1277     0.015      8.415     0.000             \n\
        st_bg_median_value_13_acs                -0.5645     0.032    -17.560    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.1335   \
        \  0.032     -4.140     0.000             \nst_bg_prop_units_sf          \
        \            -0.0504     0.029     -1.711     0.087             \nst_bg_ratio_households_to_units\
        \           0.4111     0.034     12.270     0.000             \nst_bg_total_units\
        \                         0.1105     0.020      5.649     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0019     0.011     -0.175\
        \     0.861             \nst_density_units_90pct_plus               0.1982\
        \     0.008     23.439     0.000             \nst_pred_built_out_sf      \
        \                0.0500     0.007      7.590     0.000             \nst_pred_rich_owned_antique\
        \                0.0750     0.010      7.463     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0078     0.028      0.277     0.782             \nst_tracts_income_segment_6_hh\
        \             0.0087     0.025      0.347     0.729             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.3000     0.032      9.486     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.3762     0.091      4.151     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -0.6499     0.163     -3.979     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.3326     0.084      3.967     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -0.0678     0.019     -3.610     0.000             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.3363     0.134      2.514     0.012             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.0473     0.207     -0.228     0.820             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           0.0207     0.295      0.070     0.944             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.0480     0.066     -0.726     0.468             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.8199     0.114     -7.180     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
