modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48021")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48021") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.14137746295872164
    - -0.040783127683197404
    - 0.028046803297934825
    - 0.15650874218513827
    - -0.34007646403431474
    - 0.16037896518124994
    - -0.017132279798756755
    - 0.4848658475650741
    - 0.021827040142398238
    - -0.19132806389366142
    - 0.15998364145847319
    - -0.014199314480454714
    - 0.029111016083144665
    - -0.279093945340606
    - -0.2402219517299196
    - 0.043162098187054944
    - 2.899340936075791
    - -32.46629310063991
    - 2.464311583047518
    - 15.752358571043667
    - -3.9328051054361652
    - 15.019869492678838
    - -33.806876205167256
    - -0.9824845292678177
    - -14.909204956993406
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48021_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          9,258\nModel:\
        \         Multinomial Logit   Df Residuals:              9,233\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.133\nTime:          \
        \            00:32   Pseudo R-bar-squ.:         0.133\nAIC:              \
        \    73,938.255   Log-Likelihood:      -36,944.127\nBIC:                 \
        \ 74,116.586   LL-Null:             -42,634.666\n=============================================================================================\n\
        \                                             coef   std err          z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1414     0.001   -175.339   \
        \  0.000             \nst_bg_mean_age_of_head                    -0.0408 \
        \    0.065     -0.627     0.531             \nst_bg_mean_children        \
        \                0.0280     0.029      0.951     0.342             \nst_bg_mean_year_built\
        \                      0.1565     0.026      5.931     0.000             \n\
        st_bg_median_value_13_acs                 -0.3401     0.066     -5.119   \
        \  0.000             \nst_bg_prop_hh_rent                         0.1604 \
        \    0.092      1.738     0.082             \nst_bg_prop_units_sf        \
        \               -0.0171     0.023     -0.743     0.458             \nst_bg_ratio_households_to_units\
        \            0.4849     0.034     14.146     0.000             \nst_bg_total_units\
        \                          0.0218     0.027      0.813     0.417         \
        \    \nst_density_jobs_90pct_plus                -0.1913     0.027     -7.064\
        \     0.000             \nst_density_units_90pct_plus                0.1600\
        \     0.024      6.564     0.000             \nst_pred_built_out_sf      \
        \                -0.0142     0.089     -0.159     0.874             \nst_pred_rich_owned_antique\
        \                 0.0291     0.011      2.743     0.006             \nst_tracts_income_segment_1_hh\
        \             -0.2791     0.061     -4.548     0.000             \nst_tracts_income_segment_6_hh\
        \             -0.2402     0.065     -3.719     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \     0.0432     0.114      0.378     0.705             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      2.8993     1.506      1.926     0.054             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -32.4663    11.847     -2.741     0.006             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            2.4643     0.381      6.471     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           15.7524     5.087      3.097     0.002             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -3.9328     2.536     -1.551     0.121             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           15.0199     9.005      1.668     0.095             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -33.8069     3.776     -8.954     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -0.9825     0.495     -1.986     0.047             \nst_zones_total_units_sum_10_min_sov_c\
        \    -14.9092     1.256    -11.872     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
