modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48053")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48053") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1631784668759662
    - 0.7990240827881334
    - -0.3103333116021541
    - 0.8163550072820901
    - -0.1852218707464921
    - 1.4259940538195537
    - -0.3223609236018979
    - 0.1986421079813144
    - 0.03720235242199902
    - 0.024645938749406484
    - 0.788319001922703
    - -0.15586969351161953
    - -12.334032672163202
    - -0.24254674049144861
    - 0.35092698778033127
    - 0.2985983109011715
    - -5.536739322916987
    - -24.74984893854763
    - 1.649640652264732
    - 14.891081269999026
    - 8.094168225078331
    - -34.30295957898193
    - 14.022384891517166
    - -5.687170341287581
    - 19.355668255835536
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48053_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            985\nModel:\
        \         Multinomial Logit   Df Residuals:                960\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.213\nTime:          \
        \            01:18   Pseudo R-bar-squ.:         0.207\nAIC:              \
        \     7,191.207   Log-Likelihood:       -3,570.604\nBIC:                 \
        \  7,313.523   LL-Null:              -4,536.093\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1632     0.003   -57.891    \
        \ 0.000             \nst_bg_mean_age_of_head                     0.7990  \
        \   0.252     3.175     0.001             \nst_bg_mean_children          \
        \             -0.3103     0.183    -1.699     0.089             \nst_bg_mean_year_built\
        \                      0.8164     0.206     3.971     0.000             \n\
        st_bg_median_value_13_acs                 -0.1852     0.277    -0.668    \
        \ 0.504             \nst_bg_prop_hh_rent                         1.4260  \
        \   0.228     6.245     0.000             \nst_bg_prop_units_sf          \
        \             -0.3224     0.172    -1.871     0.061             \nst_bg_ratio_households_to_units\
        \            0.1986     0.075     2.632     0.008             \nst_bg_total_units\
        \                          0.0372     0.356     0.104     0.917          \
        \   \nst_density_jobs_90pct_plus                 0.0246     0.037     0.675\
        \     0.500             \nst_density_units_90pct_plus                0.7883\
        \     0.035    22.812     0.000             \nst_pred_built_out_sf       \
        \               -0.1559     0.125    -1.250     0.211             \nst_pred_rich_owned_antique\
        \               -12.3340    99.406    -0.124     0.901             \nst_tracts_income_segment_1_hh\
        \             -0.2425     0.096    -2.525     0.012             \nst_tracts_income_segment_6_hh\
        \              0.3509     0.316     1.111     0.267             \nst_zones_density_units_ave_5_min_sov_c\
        \     0.2986     0.396     0.754     0.451             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     -5.5367    13.289    -0.417     0.677             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -24.7498    10.114    -2.447     0.014             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            1.6496     2.733     0.604     0.546             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           14.8911     9.936     1.499     0.134             \nst_zones_jobs_3_sum_5_min_sov_c\
        \            8.0942     9.917     0.816     0.414             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -34.3030    24.037    -1.427     0.154             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           14.0224    21.276     0.659     0.510             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -5.6872     8.011    -0.710     0.478             \nst_zones_total_units_sum_10_min_sov_c\
        \     19.3557    10.342     1.872     0.061             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
