modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48021")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48021") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12214124467370459
    - 0.5239908001231484
    - 0.13773215865096802
    - 0.11305470604470058
    - -0.39788490958354567
    - 0.08476367031359715
    - 0.03720644531422901
    - 0.730822727173528
    - 0.07006108936988932
    - -0.25162884838038013
    - 0.08088807513753674
    - -0.07685415498917132
    - 0.04571786369663685
    - -0.14794336108188225
    - -0.17388169543479406
    - 0.10933043470767269
    - 1.5778674578295984
    - -22.055946154711513
    - 2.376417685466581
    - 3.5661523441923144
    - 1.6252538569286048
    - 20.38839947735326
    - -39.431399903070314
    - -0.9242209644072882
    - -13.901686412781466
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48021_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,114\nModel:\
        \         Multinomial Logit   Df Residuals:              7,089\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.097\nTime:          \
        \            00:58   Pseudo R-bar-squ.:         0.096\nAIC:              \
        \    59,222.486   Log-Likelihood:      -29,586.243\nBIC:                 \
        \ 59,394.232   LL-Null:             -32,761.181\n=============================================================================================\n\
        \                                             coef   std err          z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1221     0.001   -161.043   \
        \  0.000             \nst_bg_mean_age_of_head                     0.5240 \
        \    0.077      6.817     0.000             \nst_bg_mean_children        \
        \                0.1377     0.033      4.177     0.000             \nst_bg_mean_year_built\
        \                      0.1131     0.030      3.761     0.000             \n\
        st_bg_median_value_13_acs                 -0.3979     0.073     -5.417   \
        \  0.000             \nst_bg_prop_hh_rent                         0.0848 \
        \    0.102      0.832     0.405             \nst_bg_prop_units_sf        \
        \                0.0372     0.027      1.378     0.168             \nst_bg_ratio_households_to_units\
        \            0.7308     0.037     19.855     0.000             \nst_bg_total_units\
        \                          0.0701     0.032      2.198     0.028         \
        \    \nst_density_jobs_90pct_plus                -0.2516     0.034     -7.340\
        \     0.000             \nst_density_units_90pct_plus                0.0809\
        \     0.031      2.618     0.009             \nst_pred_built_out_sf      \
        \                -0.0769     0.118     -0.652     0.515             \nst_pred_rich_owned_antique\
        \                 0.0457     0.010      4.702     0.000             \nst_tracts_income_segment_1_hh\
        \             -0.1479     0.069     -2.135     0.033             \nst_tracts_income_segment_6_hh\
        \             -0.1739     0.074     -2.365     0.018             \nst_zones_density_units_ave_5_min_sov_c\
        \     0.1093     0.128      0.854     0.393             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      1.5779     1.780      0.886     0.375             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -22.0559    13.478     -1.636     0.102             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            2.3764     0.431      5.519     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \            3.5662     5.838      0.611     0.541             \nst_zones_jobs_3_sum_5_min_sov_c\
        \            1.6253     2.789      0.583     0.560             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           20.3884    10.047      2.029     0.042             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -39.4314     4.274     -9.227     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -0.9242     0.568     -1.628     0.104             \nst_zones_total_units_sum_10_min_sov_c\
        \    -13.9017     1.510     -9.206     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
