modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48053")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48053") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1610535080345026
    - -1.104463139062278
    - 0.14765371781707964
    - 0.6274973435839375
    - 0.45466456846755093
    - 0.22274164108682581
    - 0.9688597283562703
    - -0.052334164494982315
    - 0.9529785902693892
    - -0.056574329424318004
    - 0.8368801496328476
    - -0.38959534004274265
    - -14.38295546608111
    - -0.00019180598293151396
    - 1.178000892456214
    - 1.6420029055890106
    - -76.68887066231429
    - 9.073262462424243
    - -7.741378123223204
    - 51.71777490845643
    - -24.139077977186556
    - 101.54970202159562
    - -79.12949276210342
    - -11.65945004647363
    - 23.137206785936794
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48053_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            502\nModel:\
        \         Multinomial Logit   Df Residuals:                477\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.272\nTime:          \
        \            01:13   Pseudo R-bar-squ.:         0.261\nAIC:              \
        \     3,416.516   Log-Likelihood:       -1,683.258\nBIC:                 \
        \  3,521.981   LL-Null:              -2,311.795\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1611     0.003   -55.892    \
        \ 0.000             \nst_bg_mean_age_of_head                    -1.1045  \
        \   0.403    -2.741     0.006             \nst_bg_mean_children          \
        \              0.1477     0.292     0.505     0.614             \nst_bg_mean_year_built\
        \                      0.6275     0.266     2.362     0.018             \n\
        st_bg_median_value_13_acs                  0.4547     0.373     1.217    \
        \ 0.223             \nst_bg_prop_hh_rent                         0.2227  \
        \   0.347     0.642     0.521             \nst_bg_prop_units_sf          \
        \              0.9689     0.286     3.382     0.001             \nst_bg_ratio_households_to_units\
        \           -0.0523     0.093    -0.563     0.573             \nst_bg_total_units\
        \                          0.9530     0.475     2.007     0.045          \
        \   \nst_density_jobs_90pct_plus                -0.0566     0.054    -1.049\
        \     0.294             \nst_density_units_90pct_plus                0.8369\
        \     0.047    17.643     0.000             \nst_pred_built_out_sf       \
        \               -0.3896     0.244    -1.598     0.110             \nst_pred_rich_owned_antique\
        \               -14.3830   135.190    -0.106     0.915             \nst_tracts_income_segment_1_hh\
        \             -0.0002     0.154    -0.001     0.999             \nst_tracts_income_segment_6_hh\
        \              1.1780     0.496     2.376     0.018             \nst_zones_density_units_ave_5_min_sov_c\
        \     1.6420     0.644     2.548     0.011             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \    -76.6889    18.948    -4.047     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \            9.0733    16.426     0.552     0.581             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -7.7414     3.930    -1.970     0.049             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           51.7178    15.704     3.293     0.001             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -24.1391    15.316    -1.576     0.115             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          101.5497    38.103     2.665     0.008             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -79.1295    34.627    -2.285     0.022             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -11.6595    12.938    -0.901     0.367             \nst_zones_total_units_sum_10_min_sov_c\
        \     23.1372    15.636     1.480     0.139             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
