modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48021")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48021") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.16122926272212082
    - 0.13323989492103688
    - 0.141664597683752
    - 0.1360683595294597
    - -0.3668598216124688
    - 1.230463819199036
    - 0.23664403761253175
    - 0.3381102325017769
    - 0.02306622636531114
    - -0.11350309799346459
    - 0.5665646038910506
    - -0.007298217317371757
    - -1.5502197966680513
    - -0.5371880448608495
    - -0.009449885299114905
    - -0.1958163234492127
    - 4.038058575352194
    - -59.906872299994134
    - 0.4429061184441132
    - 24.787129857223842
    - -8.344188482647443
    - 28.68453925108202
    - -23.68990548387356
    - -1.3281620346160026
    - -12.757551094409624
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48021_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48021") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48021") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,969\nModel:\
        \         Multinomial Logit   Df Residuals:              2,944\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.170\nTime:          \
        \            01:24   Pseudo R-bar-squ.:         0.168\nAIC:              \
        \    22,754.772   Log-Likelihood:      -11,352.386\nBIC:                 \
        \ 22,904.672   LL-Null:             -13,672.750\n=============================================================================================\n\
        \                                             coef   std err          z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1612     0.001   -114.360   \
        \  0.000             \nst_bg_mean_age_of_head                     0.1332 \
        \    0.133      0.998     0.318             \nst_bg_mean_children        \
        \                0.1417     0.072      1.979     0.048             \nst_bg_mean_year_built\
        \                      0.1361     0.042      3.238     0.001             \n\
        st_bg_median_value_13_acs                 -0.3669     0.120     -3.068   \
        \  0.002             \nst_bg_prop_hh_rent                         1.2305 \
        \    0.179      6.883     0.000             \nst_bg_prop_units_sf        \
        \                0.2366     0.040      5.918     0.000             \nst_bg_ratio_households_to_units\
        \            0.3381     0.070      4.847     0.000             \nst_bg_total_units\
        \                          0.0231     0.051      0.454     0.650         \
        \    \nst_density_jobs_90pct_plus                -0.1135     0.033     -3.473\
        \     0.001             \nst_density_units_90pct_plus                0.5666\
        \     0.024     23.734     0.000             \nst_pred_built_out_sf      \
        \                -0.0073     0.136     -0.054     0.957             \nst_pred_rich_owned_antique\
        \                -1.5502    43.233     -0.036     0.971             \nst_tracts_income_segment_1_hh\
        \             -0.5372     0.128     -4.197     0.000             \nst_tracts_income_segment_6_hh\
        \             -0.0094     0.156     -0.061     0.952             \nst_zones_density_units_ave_5_min_sov_c\
        \    -0.1958     0.229     -0.855     0.392             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      4.0381     2.920      1.383     0.167             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -59.9069    22.789     -2.629     0.009             \nst_zones_jobs_1_sum_5_min_sov_c\
        \            0.4429     1.303      0.340     0.734             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           24.7871     9.201      2.694     0.007             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -8.3442     5.601     -1.490     0.136             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           28.6845    20.859      1.375     0.169             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -23.6899     7.279     -3.254     0.001             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -1.3282     0.871     -1.526     0.127             \nst_zones_total_units_sum_10_min_sov_c\
        \    -12.7576     2.618     -4.874     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
