modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48055") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.16876309958421737
    - -0.48316280377443144
    - 0.13466367139992647
    - 0.7197506923493525
    - -0.7004516925281963
    - -0.2536408634986121
    - 0.6517226919073962
    - -0.28575732935463066
    - 0.4651351197724254
    - 0.036078614446201716
    - 0.4983554403534133
    - -0.13681424248998375
    - -1.6838850692683234
    - 0.569987450413053
    - -1.5647227968390858
    - -0.041366296889577686
    - 43.51687062216018
    - -205.22743269626878
    - -23.380627628861472
    - -11.521432982955451
    - -37.32869520612544
    - 234.14834979163848
    - 36.62449645162526
    - -3.911539757887721
    - -14.08977611016099
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48055_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            473\nModel:\
        \         Multinomial Logit   Df Residuals:                448\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.179\nTime:          \
        \            01:36   Pseudo R-bar-squ.:         0.168\nAIC:              \
        \     3,626.228   Log-Likelihood:       -1,788.114\nBIC:                 \
        \  3,730.206   LL-Null:              -2,178.245\n=============================================================================================\n\
        \                                              coef   std err         z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov     -0.1688     0.004   -43.247   \
        \  0.000             \nst_bg_mean_age_of_head                     -0.4832\
        \     0.227    -2.127     0.033             \nst_bg_mean_children        \
        \                 0.1347     0.244     0.553     0.581             \nst_bg_mean_year_built\
        \                       0.7198     0.215     3.353     0.001             \n\
        st_bg_median_value_13_acs                  -0.7005     0.476    -1.473   \
        \  0.141             \nst_bg_prop_hh_rent                         -0.2536\
        \     0.481    -0.527     0.598             \nst_bg_prop_units_sf        \
        \                 0.6517     0.149     4.389     0.000             \nst_bg_ratio_households_to_units\
        \            -0.2858     0.322    -0.887     0.375             \nst_bg_total_units\
        \                           0.4651     0.191     2.433     0.015         \
        \    \nst_density_jobs_90pct_plus                  0.0361     0.073     0.492\
        \     0.622             \nst_density_units_90pct_plus                 0.4984\
        \     0.053     9.361     0.000             \nst_pred_built_out_sf       \
        \                -0.1368     0.180    -0.759     0.448             \nst_pred_rich_owned_antique\
        \                 -1.6839   207.510    -0.008     0.994             \nst_tracts_income_segment_1_hh\
        \               0.5700     0.245     2.322     0.020             \nst_tracts_income_segment_6_hh\
        \              -1.5647     0.639    -2.449     0.014             \nst_zones_density_units_ave_5_min_sov_c\
        \     -0.0414     0.625    -0.066     0.947             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \      43.5169    19.948     2.181     0.029             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -205.2274    83.347    -2.462     0.014             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -23.3806     7.933    -2.947     0.003             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           -11.5214     9.359    -1.231     0.218             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -37.3287    11.642    -3.206     0.001             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           234.1483    79.168     2.958     0.003             \nst_zones_jobs_5_sum_5_min_sov_c\
        \            36.6245    25.077     1.460     0.144             \nst_zones_total_jobs_sum_20_min_sov_c\
        \       -3.9115     1.953    -2.003     0.045             \nst_zones_total_units_sum_10_min_sov_c\
        \     -14.0898     3.485    -4.042     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
