modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48209")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48209") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.09947881195979671
    - 0.7942984965987329
    - -0.14477880712633545
    - 0.15166627504692007
    - 0.14650600588627552
    - 0.9423529826183379
    - -0.05933627576092777
    - 0.2638128763910845
    - -0.007436939604418875
    - 0.19679650875289448
    - 0.6939454196433127
    - -0.06432480740256379
    - -1.464942492701246
    - 0.07511213313823357
    - -0.05777916169901126
    - 0.1261710446076131
    - -1.1239352104428937
    - 1.9914147435140965
    - -0.6747633172656575
    - 1.5823205640232931
    - -0.7561745740989336
    - -1.6198976945310348
    - 1.592128258807993
    - 0.2325058672715272
    - -2.191037957550415
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48209_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48209") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48209") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,138\nModel:\
        \         Multinomial Logit   Df Residuals:              2,113\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.228\nTime:          \
        \            01:20   Pseudo R-bar-squ.:         0.225\nAIC:              \
        \    15,261.549   Log-Likelihood:       -7,605.774\nBIC:                 \
        \ 15,403.239   LL-Null:              -9,845.854\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.0995     0.002   -49.086     0.000\
        \             \nst_bg_mean_age_of_head                    0.7943     0.053\
        \    15.019     0.000             \nst_bg_mean_children                  \
        \    -0.1448     0.050    -2.910     0.004             \nst_bg_mean_year_built\
        \                     0.1517     0.068     2.225     0.026             \n\
        st_bg_median_value_13_acs                 0.1465     0.072     2.042     0.041\
        \             \nst_bg_prop_hh_rent                        0.9424     0.101\
        \     9.314     0.000             \nst_bg_prop_units_sf                  \
        \    -0.0593     0.054    -1.098     0.272             \nst_bg_ratio_households_to_units\
        \           0.2638     0.068     3.898     0.000             \nst_bg_total_units\
        \                        -0.0074     0.043    -0.175     0.861           \
        \  \nst_density_jobs_90pct_plus                0.1968     0.020     9.622\
        \     0.000             \nst_density_units_90pct_plus               0.6939\
        \     0.020    34.299     0.000             \nst_pred_built_out_sf       \
        \              -0.0643     0.050    -1.276     0.202             \nst_pred_rich_owned_antique\
        \               -1.4649    15.200    -0.096     0.923             \nst_tracts_income_segment_1_hh\
        \             0.0751     0.027     2.794     0.005             \nst_tracts_income_segment_6_hh\
        \            -0.0578     0.087    -0.667     0.505             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.1262     0.100     1.266     0.206             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \    -1.1239     0.930    -1.209     0.227             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           1.9914     3.551     0.561     0.575             \nst_zones_jobs_1_sum_5_min_sov_c\
        \          -0.6748     0.847    -0.796     0.426             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           1.5823     1.783     0.887     0.375             \nst_zones_jobs_3_sum_5_min_sov_c\
        \          -0.7562     0.638    -1.185     0.236             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -1.6199     1.968    -0.823     0.410             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           1.5921     1.392     1.144     0.253             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      0.2325     0.204     1.139     0.254             \nst_zones_total_units_sum_10_min_sov_c\
        \    -2.1910     0.844    -2.595     0.009             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
