modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1914171473819165
    - -0.08274745662728081
    - -0.3331560325127931
    - -0.16936759908460794
    - 0.05629756559462568
    - 0.574771633914408
    - -0.1554728519709156
    - 0.011322043334296795
    - 0.14497950276399357
    - 0.2331548585156068
    - 0.7393241757319571
    - -0.14705837640952987
    - -0.22161047432408812
    - -0.007414409906454189
    - 0.036221820626262884
    - -0.18507323770790973
    - 0.05391055883453609
    - 0.15640983531739472
    - 0.14634204414174423
    - -0.00770047786320471
    - 0.10576409131509008
    - -0.12555751992086234
    - -0.596571793215857
    - 0.13826997884544343
    - -0.6052045522440884
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          59,648\nModel:\
        \         Multinomial Logit   Df Residuals:              59,623\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-10-29   Pseudo R-squ.:              0.367\nTime:       \
        \               01:17   Pseudo R-bar-squ.:          0.367\nAIC:          \
        \       347,975.006   Log-Likelihood:      -173,962.503\nBIC:            \
        \     348,199.912   LL-Null:             -274,689.191\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1914     0.001   -283.492    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.0827   \
        \  0.010     -8.688     0.000             \nst_bg_mean_children          \
        \            -0.3332     0.006    -52.148     0.000             \nst_bg_mean_year_built\
        \                    -0.1694     0.008    -20.025     0.000             \n\
        st_bg_median_value_13_acs                 0.0563     0.006      9.382    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5748   \
        \  0.014     42.192     0.000             \nst_bg_prop_units_sf          \
        \            -0.1555     0.012    -12.843     0.000             \nst_bg_ratio_households_to_units\
        \           0.0113     0.008      1.420     0.156             \nst_bg_total_units\
        \                         0.1450     0.006     25.544     0.000          \
        \   \nst_density_jobs_90pct_plus                0.2332     0.003     75.722\
        \     0.000             \nst_density_units_90pct_plus               0.7393\
        \     0.003    221.161     0.000             \nst_pred_built_out_sf      \
        \               -0.1471     0.009    -16.951     0.000             \nst_pred_rich_owned_antique\
        \               -0.2216     0.025     -9.025     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0074     0.004     -2.068     0.039             \nst_tracts_income_segment_6_hh\
        \             0.0362     0.008      4.547     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.1851     0.012    -15.428     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.0539     0.016      3.295     0.001             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           0.1564     0.014     11.080     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.1463     0.010     14.892     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -0.0077     0.009     -0.855     0.393             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.1058     0.024      4.480     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.1256     0.030     -4.138     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.5966     0.021    -28.021     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      0.1383     0.017      7.924     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.6052     0.024    -25.063     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
