modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48055") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.10495696774533839
    - 0.2080101359710059
    - -0.2006026625343875
    - 0.3978107370490074
    - -0.20953135080949253
    - -0.34736555094713123
    - 0.34938664311494444
    - 0.2133939137796795
    - 0.9634984748833917
    - -0.20890345632730895
    - 0.16934741466464484
    - -0.20622085878245697
    - 0.02808621762552168
    - 0.1667686146732208
    - -2.148901414514319
    - 0.33183596926429726
    - 1.8283113686681223
    - -206.6783793252853
    - -18.267758663334284
    - -23.226423686904333
    - -24.55156456035311
    - 235.9308658949833
    - 21.91536476728964
    - 1.7530801894567045
    - -6.62637285178468
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48055_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48055") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,354\nModel:\
        \         Multinomial Logit   Df Residuals:              1,329\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.088\nTime:          \
        \            00:20   Pseudo R-bar-squ.:         0.084\nAIC:              \
        \    11,418.472   Log-Likelihood:       -5,684.236\nBIC:                 \
        \ 11,548.743   LL-Null:              -6,235.400\n=============================================================================================\n\
        \                                              coef   std err         z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov     -0.1050     0.002   -49.060   \
        \  0.000             \nst_bg_mean_age_of_head                      0.2080\
        \     0.124     1.684     0.092             \nst_bg_mean_children        \
        \                -0.2006     0.152    -1.322     0.186             \nst_bg_mean_year_built\
        \                       0.3978     0.103     3.874     0.000             \n\
        st_bg_median_value_13_acs                  -0.2095     0.280    -0.748   \
        \  0.454             \nst_bg_prop_hh_rent                         -0.3474\
        \     0.196    -1.773     0.076             \nst_bg_prop_units_sf        \
        \                 0.3494     0.092     3.779     0.000             \nst_bg_ratio_households_to_units\
        \             0.2134     0.139     1.533     0.125             \nst_bg_total_units\
        \                           0.9635     0.117     8.202     0.000         \
        \    \nst_density_jobs_90pct_plus                 -0.2089     0.052    -4.053\
        \     0.000             \nst_density_units_90pct_plus                 0.1693\
        \     0.049     3.479     0.001             \nst_pred_built_out_sf       \
        \                -0.2062     0.123    -1.681     0.093             \nst_pred_rich_owned_antique\
        \                  0.0281     0.024     1.185     0.236             \nst_tracts_income_segment_1_hh\
        \               0.1668     0.119     1.401     0.161             \nst_tracts_income_segment_6_hh\
        \              -2.1489     0.298    -7.200     0.000             \nst_zones_density_units_ave_5_min_sov_c\
        \      0.3318     0.333     0.996     0.319             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \       1.8283     8.034     0.228     0.820             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -206.6784    44.996    -4.593     0.000             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -18.2678     2.973    -6.146     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           -23.2264     6.141    -3.782     0.000             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           -24.5516     5.531    -4.439     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \           235.9309    36.570     6.451     0.000             \nst_zones_jobs_5_sum_5_min_sov_c\
        \            21.9154    12.008     1.825     0.068             \nst_zones_total_jobs_sum_20_min_sov_c\
        \        1.7531     1.041     1.684     0.092             \nst_zones_total_units_sum_10_min_sov_c\
        \      -6.6264     2.416    -2.743     0.006             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
