modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48053")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48053") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15407411273350724
    - 1.0641563190821393
    - 0.22787044150947347
    - 0.3373758765939806
    - -1.2677810527410613
    - 1.4760138275581147
    - 0.42710767089055995
    - -0.0425683687124983
    - 0.8271931347038517
    - 0.09897167427766151
    - 0.6098395404177541
    - -0.04344768369528985
    - -1.8200306827101596
    - -0.5171433610471662
    - -0.07244266560504443
    - 0.938637960132077
    - 33.38734542464745
    - -12.091313002642217
    - -3.0098028108896493
    - -4.965989593570133
    - 33.81871610443177
    - -20.781618309603452
    - -9.884077135083297
    - -0.2758978983173573
    - -5.784418738141966
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48053_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48053") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48053") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            588\nModel:\
        \         Multinomial Logit   Df Residuals:                563\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.200\nTime:          \
        \            01:36   Pseudo R-bar-squ.:         0.191\nAIC:              \
        \     4,381.842   Log-Likelihood:       -2,165.921\nBIC:                 \
        \  4,491.261   LL-Null:              -2,707.840\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov    -0.1541     0.003   -54.983    \
        \ 0.000             \nst_bg_mean_age_of_head                     1.0642  \
        \   0.309     3.447     0.001             \nst_bg_mean_children          \
        \              0.2279     0.249     0.915     0.360             \nst_bg_mean_year_built\
        \                      0.3374     0.241     1.401     0.161             \n\
        st_bg_median_value_13_acs                 -1.2678     0.364    -3.483    \
        \ 0.000             \nst_bg_prop_hh_rent                         1.4760  \
        \   0.273     5.410     0.000             \nst_bg_prop_units_sf          \
        \              0.4271     0.241     1.769     0.077             \nst_bg_ratio_households_to_units\
        \           -0.0426     0.103    -0.413     0.679             \nst_bg_total_units\
        \                          0.8272     0.410     2.016     0.044          \
        \   \nst_density_jobs_90pct_plus                 0.0990     0.049     2.029\
        \     0.042             \nst_density_units_90pct_plus                0.6098\
        \     0.055    11.128     0.000             \nst_pred_built_out_sf       \
        \               -0.0434     0.124    -0.351     0.726             \nst_pred_rich_owned_antique\
        \                -1.8200   137.661    -0.013     0.989             \nst_tracts_income_segment_1_hh\
        \             -0.5171     0.132    -3.920     0.000             \nst_tracts_income_segment_6_hh\
        \             -0.0724     0.429    -0.169     0.866             \nst_zones_density_units_ave_5_min_sov_c\
        \     0.9386     0.447     2.099     0.036             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     33.3873    16.928     1.972     0.049             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -12.0913    13.881    -0.871     0.384             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           -3.0098     3.760    -0.801     0.423             \nst_zones_jobs_2_sum_5_min_sov_c\
        \           -4.9660    11.949    -0.416     0.678             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           33.8187    10.310     3.280     0.001             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -20.7816    29.958    -0.694     0.488             \nst_zones_jobs_5_sum_5_min_sov_c\
        \           -9.8841    28.206    -0.350     0.726             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      -0.2759    10.555    -0.026     0.979             \nst_zones_total_units_sum_10_min_sov_c\
        \     -5.7844    13.910    -0.416     0.678             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
