modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12267652437904303
    - 0.35249844069189656
    - -0.24233201818024372
    - -0.20979533388904315
    - -0.042415195030603085
    - -0.3508795106369707
    - -0.2990637485681981
    - 0.20321136096838174
    - 0.14017753745671876
    - 0.052984942658368325
    - 0.3186464978090432
    - 0.02551213967848254
    - -0.0012822494284779329
    - -0.0071460408678344755
    - 0.016244853147489052
    - 0.11056562286327468
    - 0.09736530415839612
    - -0.008017867269780304
    - 0.13771432380365736
    - -0.031741228229650004
    - 0.0034748347849270296
    - -0.1410011932258598
    - -0.19727272041578878
    - 0.12223642675521204
    - -0.19823666224975345
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          25,914\nModel:\
        \         Multinomial Logit   Df Residuals:              25,889\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-10-29   Pseudo R-squ.:              0.080\nTime:       \
        \               00:21   Pseudo R-bar-squ.:          0.079\nAIC:          \
        \       219,733.365   Log-Likelihood:      -109,841.683\nBIC:            \
        \     219,937.429   LL-Null:             -119,338.380\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1227     0.001   -157.776    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3525   \
        \  0.013     28.198     0.000             \nst_bg_mean_children          \
        \            -0.2423     0.009    -27.439     0.000             \nst_bg_mean_year_built\
        \                    -0.2098     0.013    -16.770     0.000             \n\
        st_bg_median_value_13_acs                -0.0424     0.008     -5.170    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.3509   \
        \  0.017    -20.150     0.000             \nst_bg_prop_units_sf          \
        \            -0.2991     0.014    -21.276     0.000             \nst_bg_ratio_households_to_units\
        \           0.2032     0.012     16.493     0.000             \nst_bg_total_units\
        \                         0.1402     0.008     17.991     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0530     0.006      9.572\
        \     0.000             \nst_density_units_90pct_plus               0.3186\
        \     0.005     70.502     0.000             \nst_pred_built_out_sf      \
        \                0.0255     0.005      4.681     0.000             \nst_pred_rich_owned_antique\
        \               -0.0013     0.006     -0.201     0.841             \nst_tracts_income_segment_1_hh\
        \            -0.0071     0.010     -0.705     0.481             \nst_tracts_income_segment_6_hh\
        \             0.0162     0.009      1.783     0.075             \nst_zones_density_units_ave_5_min_sov_c\
        \    0.1106     0.017      6.678     0.000             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.0974     0.022      4.414     0.000             \nst_zones_jobs_0_sum_5_min_sov_c\
        \          -0.0080     0.023     -0.356     0.722             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.1377     0.015      9.069     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -0.0317     0.011     -2.932     0.003             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.0035     0.037      0.095     0.925             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.1410     0.046     -3.035     0.002             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.1973     0.033     -5.917     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \      0.1222     0.018      6.672     0.000             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.1982     0.032     -6.133     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
