modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "48453")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "48453") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.18256320925978642
    - 0.4818886094240608
    - 0.030557043788061025
    - -0.1479255212870683
    - -0.052784222954761505
    - 0.9038005419129683
    - 0.06777282988653138
    - 0.0425372487731811
    - 0.11226024613151266
    - 0.19076609248284807
    - 0.5685407111955235
    - 0.01014862987148689
    - -0.104972834111218
    - -0.021833186883851035
    - 0.03758390826290544
    - -0.011430580579132928
    - 0.04930976627032541
    - 0.06525509591905046
    - 0.09777349335107904
    - -0.0013407230876742247
    - 0.4111108902139102
    - -0.1278631331300359
    - -0.7748764901911385
    - -0.09730217923399917
    - -0.37549512190590395
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_c_school: min
            sov_c_work: min
        rename_cols:
            sov_c_school: min_school_sov
            sov_c_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c +
        st_zones_income_6_hh_sum_10_min_sov_c + st_zones_jobs_0_sum_5_min_sov_c +
        st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c + st_zones_jobs_3_sum_5_min_sov_c
        + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c + st_zones_total_jobs_sum_20_min_sov_c
        + st_zones_total_units_sum_10_min_sov_c - 1
    name: hlcm_48453_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "48453") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         12,185\nModel:\
        \         Multinomial Logit   Df Residuals:             12,160\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-10-29   Pseudo R-squ.:             0.234\nTime:          \
        \            01:37   Pseudo R-bar-squ.:         0.233\nAIC:              \
        \    86,060.598   Log-Likelihood:      -43,005.299\nBIC:                 \
        \ 86,245.797   LL-Null:             -56,113.999\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1826     0.001   -133.031    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.4819   \
        \  0.018     26.103     0.000             \nst_bg_mean_children          \
        \             0.0306     0.011      2.814     0.005             \nst_bg_mean_year_built\
        \                    -0.1479     0.019     -7.900     0.000             \n\
        st_bg_median_value_13_acs                -0.0528     0.014     -3.749    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.9038   \
        \  0.027     33.005     0.000             \nst_bg_prop_units_sf          \
        \             0.0678     0.023      2.897     0.004             \nst_bg_ratio_households_to_units\
        \           0.0425     0.018      2.422     0.015             \nst_bg_total_units\
        \                         0.1123     0.013      8.706     0.000          \
        \   \nst_density_jobs_90pct_plus                0.1908     0.007     26.976\
        \     0.000             \nst_density_units_90pct_plus               0.5685\
        \     0.007     87.451     0.000             \nst_pred_built_out_sf      \
        \                0.0101     0.011      0.928     0.353             \nst_pred_rich_owned_antique\
        \               -0.1050     0.027     -3.950     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0218     0.011     -1.903     0.057             \nst_tracts_income_segment_6_hh\
        \             0.0376     0.018      2.133     0.033             \nst_zones_density_units_ave_5_min_sov_c\
        \   -0.0114     0.026     -0.439     0.661             \nst_zones_income_6_hh_sum_10_min_sov_c\
        \     0.0493     0.036      1.381     0.167             \nst_zones_jobs_0_sum_5_min_sov_c\
        \           0.0653     0.033      1.972     0.049             \nst_zones_jobs_1_sum_5_min_sov_c\
        \           0.0978     0.021      4.615     0.000             \nst_zones_jobs_2_sum_5_min_sov_c\
        \          -0.0013     0.018     -0.073     0.942             \nst_zones_jobs_3_sum_5_min_sov_c\
        \           0.4111     0.050      8.273     0.000             \nst_zones_jobs_4_sum_5_min_sov_c\
        \          -0.1279     0.069     -1.847     0.065             \nst_zones_jobs_5_sum_5_min_sov_c\
        \          -0.7749     0.051    -15.311     0.000             \nst_zones_total_jobs_sum_20_min_sov_c\
        \     -0.0973     0.033     -2.946     0.003             \nst_zones_total_units_sum_10_min_sov_c\
        \    -0.3755     0.051     -7.297     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
