modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.19992613792419434
  - -0.14844338595867157
  - 0.17825542390346527
  - 0.001241086283698678
  - -0.15447038412094116
  - -0.02878139540553093
  - 0.24631989002227783
  - -0.08164405077695847
  - -0.3722479045391083
  - 0.32107266783714294
  - -0.001231357455253601
  - -0.6386637687683105
  - -0.0816720575094223
  - -0.01978108286857605
  - 0.17782169580459595
  - 2.309680461883545
  - -0.5900602340698242
  - -1.631880760192871
  - 0.4953623414039612
  - 1.146653175354004
  - 0.2111797332763672
  - 0.04276897385716438
  - 0.2938348650932312
  - 2.0966172218322754
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c + st_zones_total_units_sum_10_min_sov_c
    - 1
  name: rdplcm_48453_blocks_sf_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & ((building_type=="sf_own")
    | (building_type=="sf_rent"))
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
