output_indicators:
    layers:
        blocks: [sum_acres,
                 total_hh,
                 total_jobs,
                 total_units,
                 density_hh,
                 density_jobs,
                 density_units,
                 hh_sum_2000_l,
                 jobs_sum_2000_l,
                 units_sum_2000_l,
                 density_hh_ave_2000_l,
                 density_jobs_ave_2000_l,
                 density_units_ave_2000_l,
                 income_ave_2000_l,
                 home_value_ave_2000_l,
                 home_rent_ave_2000_l,
                 prop_units_own_ave_2000_l,
                 prop_units_rent_ave_2000_l,
                 prop_units_sf_ave_2000_l,
                 prop_units_mf_ave_2000_l,
                 prop_units_new_ave_2000_l,
                 ratio_households_to_units,
                 ratio_jobs_to_units,
                 residential_unit_capacity,
                 employment_capacity,
                 du_spaces,
                 job_spaces,
                 du_spaces_acre,
                 job_spaces_acre]
        blockgroups: [sum_acres,
                      total_hh,
                      total_jobs,
                      total_units,
                      density_hh,
                      density_jobs,
                      density_units,
                      mean_income,
                      mean_hh_size,
                      mean_age_of_head,
                      hh_own,
                      hh_rent,
                      units_own,
                      units_rent,
                      units_mf,
                      units_sf,
                      jobs_0,
                      jobs_1,
                      jobs_2,
                      jobs_3,
                      jobs_4,
                      jobs_5]
        tracts: [sum_acres,
                 total_hh,
                 total_jobs,
                 total_units,
                 density_hh,
                 density_jobs,
                 density_units,
                 mean_income,
                 mean_hh_size,
                 mean_age_of_head,
                 hh_own,
                 hh_rent,
                 units_own,
                 units_rent,
                 units_sf,
                 units_mf,
                 jobs_0,
                 jobs_1,
                 jobs_2,
                 jobs_3,
                 jobs_4,
                 jobs_5,
                 units_mf,
                 units_sf,
                 vacant_residential_units,
                 vacant_job_spaces,
                 vacant_du_spaces,
                 hh_sim_growth_year,
                 jobs_sim_growth_year,
                 units_sim_growth_year,
                 hh_obs_growth_13_18_nc,
                 units_obs_growth_13_18_nc,
                 jobs_obs_growth_10_17_nc]
        county: [total_hh,
                 total_persons,
                 total_jobs,
                 total_units,
                 mean_income,
                 mean_home_value,
                 mean_home_rent]
    downloads:
        blocks: [sum_acres,
                 total_hh,
                 total_jobs,
                 total_units,
                 total_persons,
                 children,
                 persons_65plus,
                 density_hh,
                 density_jobs,
                 density_units,
                 hh_sum_2000_l,
                 jobs_sum_2000_l,
                 units_sum_2000_l,
                 density_hh_ave_2000_l,
                 density_jobs_ave_2000_l,
                 density_units_ave_2000_l,
                 income_ave_2000_l,
                 home_value_ave_2000_l,
                 home_rent_ave_2000_l,
                 prop_units_own_ave_2000_l,
                 prop_units_rent_ave_2000_l,
                 prop_units_sf_ave_2000_l,
                 prop_units_mf_ave_2000_l,
                 prop_units_new_ave_2000_l,
                 ratio_households_to_units,
                 ratio_jobs_to_units]
        blockgroups: [sum_acres,
                      total_hh,
                      total_jobs,
                      total_units,
                      density_hh,
                      density_jobs,
                      density_units,
                      income_segment_1_hh,
                      income_segment_6_hh,
                      mean_income,
                      mean_hh_size,
                      mean_age_of_head,
                      hh_own,
                      hh_rent,
                      units_own,
                      units_rent,
                      units_mf,
                      units_sf,
                      units_mf_own,
                      units_sf_own,
                      units_mf_rent,
                      units_sf_rent,
                      jobs_0,
                      jobs_1,
                      jobs_2,
                      jobs_3,
                      jobs_4,
                      jobs_5
                      prop_jobs_0,
                      prop_jobs_1,
                      prop_jobs_2,
                      prop_jobs_3,
                      prop_jobs_4,
                      prop_jobs_5,
                      total_jobs_sum_5_km_pandana,
                      total_units_sum_5_km_pandana,
                      total_hh_sum_5_km_pandana,
                      density_jobs_ave_5_km_pandana,
                      density_units_ave_5_km_pandana,
                      density_hh_ave_5_km_pandana,
                      home_rent_ave_5_km_pandana,
                      home_value_ave_5_km_pandana]
        tracts: [sum_acres,
                 total_hh,
                 total_persons,
                 total_jobs,
                 total_units,
                 density_hh,
                 density_jobs,
                 density_units,
                 income_segment_1_hh,
                 income_segment_6_hh,
                 mean_income,
                 mean_hh_size,
                 mean_age_of_head,
                 hh_own,
                 hh_rent,
                 units_own,
                 units_rent,
                 units_sf,
                 units_mf,
                 units_mf_own,
                 units_sf_own,
                 units_mf_rent,
                 units_sf_rent,
                 jobs_0,
                 jobs_1,
                 jobs_2,
                 jobs_3,
                 jobs_4,
                 jobs_5,
                 prop_jobs_0,
                 prop_jobs_1,
                 prop_jobs_2,
                 prop_jobs_3,
                 prop_jobs_4,
                 prop_jobs_5,
                 prop_hh_rent,
                 prop_units_mf,
                 units_mf,
                 units_sf,
                 vacant_residential_units,
                 vacant_job_spaces,
                 vacant_du_spaces,
                 hh_sim_growth_year,
                 jobs_sim_growth_year,
                 units_sim_growth_year,
                 hh_prop_sim_growth_year,
                 jobs_prop_sim_growth_year,
                 units_prop_sim_growth_year,
                 jobs_obs_growth_10_17,
                 jobs_sim_growth_10_17,
                 jobs_prop_obs_growth_10_17,
                 jobs_prop_sim_growth_10_17,
                 hh_obs_growth_13_18,
                 hh_sim_growth_13_18,
                 hh_prop_obs_growth_13_18,
                 hh_prop_sim_growth_13_18,
                 units_obs_growth_13_18,
                 units_sim_growth_13_18,
                 units_prop_obs_growth_13_18,
                 units_prop_sim_growth_13_18,
                 jobs_prop_obs_growth_17_18,
                 jobs_prop_sim_growth_17_18,
                 hh_prop_obs_growth_18_19,
                 hh_prop_sim_growth_18_19,
                 units_prop_obs_growth_18_19,
                 units_prop_sim_growth_18_19,
                 jobs_obs_growth_10_17_nc,
                 hh_obs_growth_13_18_nc,
                 units_obs_growth_13_18_nc,
                 jobs_prop_obs_growth_10_17_nc,
                 hh_prop_obs_growth_13_18_nc,
                 units_prop_obs_growth_13_18_nc,
                 jobs_prop_obs_growth_17_18_nc,
                 hh_prop_obs_growth_18_19_nc,
                 units_prop_obs_growth_18_19_nc]
        county: [total_hh,
                 total_persons,
                 total_jobs,
                 total_units,
                 mean_income,
                 mean_home_value,
                 mean_home_rent]
output_charts:
    geography_large: county_id
    geography_small: tract_id
    variables:
      base_run_charts:
        sum:
            pie_charts: []
            bar_charts_totals: [total_hh, total_persons, total_jobs, total_units]
            bar_charts: [prop_hh_rent, prop_units_mf]
            bar_charts_n_largest: []
            bar_charts_proportions: {}
            histograms: []
            scatters: {}
        mean:
            pie_charts: []
            bar_charts: [mean_age_of_head, mean_income]
            bar_charts_n_largest: []
            bar_charts_proportions: {}
            histograms: []
            scatters: {}
        calibration_scatters:
            {jobs_prop_sim_growth_10_17: [jobs_prop_obs_growth_10_17, jobs_prop_obs_growth_10_17_nc],
             hh_prop_sim_growth_13_18: [hh_prop_obs_growth_13_18, hh_prop_obs_growth_13_18_nc],
             units_prop_sim_growth_13_18: [units_prop_obs_growth_13_18, units_prop_obs_growth_13_18_nc],
             jobs_prop_sim_growth_17_18: [jobs_prop_obs_growth_17_18, jobs_prop_obs_growth_17_18_nc],
             hh_prop_sim_growth_18_19: [hh_prop_obs_growth_18_19, hh_prop_obs_growth_18_19_nc],
             units_prop_sim_growth_18_19: [units_prop_obs_growth_18_19, units_prop_obs_growth_18_19_nc]}
      forecasting_charts:
        sum:
            pie_charts: [hh_sim_growth_year, jobs_sim_growth_year, units_sim_growth_year]
            bar_charts_totals: [total_hh, total_persons, total_jobs, total_units]
            bar_charts: [prop_hh_rent, prop_units_mf]
            bar_charts_n_largest: [vacant_job_spaces, vacant_residential_units, vacant_du_spaces, total_jobs, total_hh, total_units]
            bar_charts_proportions: {jobs: [agg_sector], households: [tenure], residential_units: [building_type]}
            histograms: [vacant_job_spaces, vacant_residential_units, vacant_du_spaces]
            scatters: {}
        mean:
            pie_charts: []
            bar_charts: [mean_age_of_head, mean_income]
            bar_charts_n_largest: [mean_income]
            bar_charts_proportions: {}
            histograms: []
            scatters: {}
        custom_charts:
          jobs: []
          households: []

variable_definitions:
  base_dict:
    {total:
       {hh: Total households,
        jobs: Total jobs,
        units: Total units,
        persons: Total persons,
       },
     sum:
       {acres: Total area (acres),
        persons: Total persons,
        workers: Total workers,
        cars: Total vehicles,
        recent_mover: Households that moved within last 5 yrs
       },
     mean:
       {x: Mean x coordinate,
        y: Mean y coordinate,
        income: Mean household annual income,
        hh_size: Mean household size,
        workers: Mean workers per household,
        children: Mean children per household,
        age_of_head: Mean age of household head,
        cars: Mean vehicles per household,
        year_built: Mean year built of units,
        home_value: Mean home value,
        home_rent: Mean home rent
       },
     other:
       {
        children: Total children,
        persons_65plus: Total persons 65 years or older,
        square_meters_land: Area (m2),
        residential_unit_capacity: Maximum allowed units,
        employment_capacity: Maximum allowed jobs,
        du_spaces: Maximum allowed units after removing undevelopable areas,
        job_spaces: Maximum allowed jobs after removing undevelopable areas,
        du_spaces_acre: Maximum allowed units per acre after removing undevelopable areas,
        job_spaces_acre: Maximum allowed jobs per acre after removing undevelopable areas,
        vacant_residential_units: Total vacant units,
        vacant_job_spaces: Total vacant job spaces,
        vacant_du_spaces: Total vacant spaces for new units,
        density_hh: Total households per acre,
        density_jobs: Total jobs per acre,
        density_units: Total units per acre,
        ratio_jobs_to_units: Ratio of jobs to units,
        ratio_households_to_units: Ratio of households to units,
        home_rent: Home rent,
        home_value: Home value,
        density_units_90pct_plus: Block unit density is 90th percentile in the region or higher,
        density_units_10pct_low: Block unit density is 10th percentile in the region or lower,
        density_jobs_90pct_plus: Block job density is 90th percentile in the region or higher,
        density_jobs_10pct_low: Block job density is 10th percentile in the region or lower,
        units_before_1930: Total units built before 1930,
        units_after_2000: Total units built after 2000,
        prop_units_before_1930: Proportion of units built before 1930,
        prop_units_after_2000: Proportion of units built after 2000,
        st_equilib_prices: Normalized median unit values in the block group,
        st_equilib_rents: Normalized median unit rents in the block group,
        units_mf: Total multi family units,
        units_sf: Total single family units,
        units_own: Total owned units,
        units_rent: Total rented units,
        prop_units_mf: Proportion of units multi family,
        prop_units_sf: Proportion of units single family,
        prop_units_own: Proportion of units owned,
        prop_units_rent: Proportion of units rented,
        units_mf_own: Total owned multi family units,
        units_mf_rent: Total rented multi family units,
        units_sf_own: Total owned single family units,
        units_sf_rent: Total rented single family units,
        hh_sim_growth_year: Total simulated household growth,
        jobs_sim_growth_year: Total simulated job growth,
        units_sim_growth_year: Total simulated unit growth,
       }
    }
  custom_dict:
    {jobs_sector_id:
       {data_name: Total jobs,
        aggregation_name: sector id},
    households_income_segment:
      {data_name: Total households,
       aggregation_name: income segment}}
  year_vars:
    {hh_sim_growth_year: ["13_18", "18_19"],
     jobs_sim_growth_year: ["10_17", "17_18"],
     units_sim_growth_year: ["13_18", "18_19"]}
  prop_vars:
    {households: [tenure, income_segment],
     jobs: [agg_sector, sector_id],
     residential_units: [building_type]
}
