modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.21743088960647583
  - 0.3172251880168915
  - 0.7617506384849548
  - -0.8297982215881348
  - -0.8598440289497375
  - -0.0884835496544838
  - -0.00722050154581666
  - -0.00962873175740242
  - -0.41438281536102295
  - 0.4440433382987976
  - -0.6579479575157166
  - 0.7177495956420898
  - -1.897437572479248
  - -1.1400707960128784
  - 7.866868019104004
  - -0.9251362085342407
  - -2.8319003582000732
  - -9.802116394042969
  - 8.52466106414795
  - 0.05929472669959068
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06001_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
