modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -2.032597064971924
  - -1.3158174753189087
  - 0.6317452788352966
  - -1.3967251777648926
  - 0.25754138827323914
  - -0.4031859338283539
  - -0.0028258091770112514
  - -0.8890608549118042
  - 0.45340266823768616
  - 0.43717485666275024
  - -0.003206272143870592
  - 0.4287415146827698
  - 0.7526179552078247
  - -0.6190900206565857
  - 2.5504860877990723
  - 6.737866401672363
  - -11.518797874450684
  - 1.2974807024002075
  - 8.655818939208984
  - 1.6576234102249146
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06013_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06013")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
