modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.46193695068359375
  - 0.13158664107322693
  - -0.4074179232120514
  - -0.9019988775253296
  - -0.2009114921092987
  - -1.4335176944732666
  - -0.5977874994277954
  - -0.4816145896911621
  - -1.062336802482605
  - 0.1714787781238556
  - 0.11760389804840088
  - 1.402860403060913
  - 3.2097532749176025
  - 1.4352971315383911
  - 1.0951508283615112
  - -0.870840847492218
  - -1.5899553298950195
  - -0.20257987082004547
  - 1.5544915199279785
  - 5.4490180015563965
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06075_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
