modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.4006304442882538
  - -0.0399460569024086
  - 0.18519291281700134
  - 0.6717795133590698
  - -0.480644166469574
  - -0.1025397926568985
  - -0.49395301938056946
  - -0.9896828532218933
  - -0.9571360349655151
  - -0.502097487449646
  - 0.12546971440315247
  - 0.755366861820221
  - -2.2529683113098145
  - 0.8660576939582825
  - -1.3038742542266846
  - 4.782191753387451
  - -2.32412052154541
  - -0.8640362620353699
  - 2.413299083709717
  - 0.8850811719894409
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06085_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06085")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
