modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.2927786707878113
  - -0.1314709484577179
  - -0.22064168751239777
  - -0.15093818306922913
  - 0.025738773867487907
  - -0.25178444385528564
  - 1.8694243431091309
  - 0.0498923659324646
  - -0.02176654525101185
  - 0.36241045594215393
  - -0.012350115925073624
  - 0.09060508012771606
  - -0.20470407605171204
  - 0.14380568265914917
  - -0.6390735507011414
  - -0.06647002696990967
  - 0.8520941734313965
  - 0.366176038980484
  - 0.5735818147659302
  - 3.5821802616119385
  - -1.2681599855422974
  - -3.2292098999023438
  - 0.2512955963611603
  - -0.046608466655015945
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06085_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
