modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.05289163812994957
  - 0.008280182257294655
  - 0.15950848162174225
  - -0.19000683724880219
  - 0.009909844025969505
  - 0.13196246325969696
  - 0.23473265767097473
  - 0.044510819017887115
  - -0.19852416217327118
  - 0.5137225985527039
  - -0.007399529218673706
  - 0.19199135899543762
  - 0.053609225898981094
  - -0.23407456278800964
  - -0.013282383792102337
  - 0.8354381918907166
  - -0.08907655626535416
  - -3.5341169834136963
  - 1.3452885150909424
  - -1.2603459358215332
  - 2.381694793701172
  - 1.1391816139221191
  - 0.36178696155548096
  - -1.1716818809509277
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06001_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
