modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.007909014821052551
  - 0.09791985154151917
  - 0.16601336002349854
  - -0.20380158722400665
  - 0.192159041762352
  - 0.01630312018096447
  - 0.2235320806503296
  - 0.1148671880364418
  - -0.07978755980730057
  - 0.5743945837020874
  - -0.006042342633008957
  - 0.29544514417648315
  - -0.0025424128398299217
  - 0.015107684768736362
  - -0.023360958322882652
  - 2.427427291870117
  - -1.3226311206817627
  - -3.3569695949554443
  - -1.5206835269927979
  - 0.45982304215431213
  - 1.0923668146133423
  - -0.7187493443489075
  - 0.004491649568080902
  - 0.04742835834622383
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06013_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
