modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - -0.1629004180431366
  - 0.027755850926041603
  - 0.021889077499508858
  - -0.1536395400762558
  - -0.3175734877586365
  - -0.3935106694698334
  - -0.12856781482696533
  - 0.11245154589414597
  - 0.06388461589813232
  - 0.7514983415603638
  - -0.006486573256552219
  - 0.13519547879695892
  - 0.11905241012573242
  - -0.03902985528111458
  - 0.00010677475074771792
  - -0.657023012638092
  - -0.41224709153175354
  - -0.4111279547214508
  - 0.4799841344356537
  - -0.2935067117214203
  - -0.38714799284935
  - 1.1635081768035889
  - 0.1033412516117096
  - 0.4849991798400879
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06075_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
