modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.09757885336875916
  - 0.13039085268974304
  - 0.045411013066768646
  - 0.0014219697332009673
  - 0.1541084200143814
  - 0.12363763898611069
  - 0.12927018105983734
  - 0.17633336782455444
  - 0.11872367560863495
  - 0.5602206587791443
  - -0.008139006793498993
  - 0.19617000222206116
  - 0.014360737055540085
  - -0.10819750279188156
  - -0.07485894113779068
  - 2.2358455657958984
  - -0.056088440120220184
  - -2.894284248352051
  - -1.6136720180511475
  - 1.6145331859588623
  - 0.9089047312736511
  - -2.0550477504730225
  - 0.006573151797056198
  - -0.0555952750146389
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06013_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06013")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
