modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.4274425208568573
  - -0.2155972570180893
  - 0.3088735044002533
  - 0.0015824692090973258
  - 0.021971164271235466
  - 0.6159459352493286
  - -0.027169305831193924
  - 0.15345962345600128
  - -0.10173455625772476
  - 0.4294617176055908
  - -0.8318994641304016
  - 0.21332396566867828
  - 0.4083227515220642
  - -0.17407351732254028
  - 0.20191334187984467
  - 0.6580644249916077
  - 2.2013001441955566
  - -1.5405893325805664
  - -3.107469081878662
  - -2.0896358489990234
  - 3.004533290863037
  - -5.158609867095947
  - 0.004868319258093834
  - 0.719951331615448
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06041_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06041")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
