modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.13138518449759978
    - 0.36135864581052984
    - -0.156294175779125
    - -0.008900472901463041
    - -0.39370132042297723
    - -0.17518303108566252
    - 0.04062442617156788
    - 0.3248499130978966
    - 0.09835214539723822
    - -0.1084832206567151
    - 0.24980564488896725
    - 0.09640291201988474
    - -0.011879241178856713
    - 0.1304746935390421
    - -0.10829745684608946
    - 0.2023143518093123
    - -0.09072813667411733
    - -0.9460982707085294
    - -0.2698419764835242
    - 0.09228014666374744
    - -0.570005671309054
    - -0.07902829968881463
    - 0.930523903961364
    - 0.07517711418200007
    - 0.3888451002446935
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          23,235\nModel:\
        \         Multinomial Logit   Df Residuals:              23,210\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.093\nTime:       \
        \               19:10   Pseudo R-bar-squ.:          0.093\nAIC:          \
        \       194,049.581   Log-Likelihood:       -96,999.790\nBIC:            \
        \     194,250.916   LL-Null:             -107,001.129\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1314     0.001   -160.615    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3614   \
        \  0.011     33.552     0.000             \nst_bg_mean_children          \
        \            -0.1563     0.013    -11.978     0.000             \nst_bg_mean_year_built\
        \                    -0.0089     0.013     -0.702     0.483             \n\
        st_bg_median_value_13_acs                -0.3937     0.013    -29.650    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.1752   \
        \  0.017    -10.614     0.000             \nst_bg_prop_units_sf          \
        \             0.0406     0.013      3.119     0.002             \nst_bg_ratio_households_to_units\
        \           0.3248     0.008     41.540     0.000             \nst_bg_total_units\
        \                         0.0984     0.011      8.729     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1085     0.009    -11.820\
        \     0.000             \nst_density_units_90pct_plus               0.2498\
        \     0.009     27.858     0.000             \nst_pred_built_out_sf      \
        \                0.0964     0.007     14.307     0.000             \nst_pred_rich_owned_antique\
        \               -0.0119     0.012     -0.999     0.318             \nst_tracts_income_segment_1_hh\
        \             0.1305     0.010     13.189     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.1083     0.016     -6.761     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.2023     0.032      6.408     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.0907     0.059     -1.527     0.127             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.9461     0.081    -11.738     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.2698     0.084     -3.207     0.001             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.0923     0.085      1.089     0.276             \nst_zones_jobs_3_sum_5_min_sov\
        \            -0.5700     0.108     -5.269     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.0790     0.066     -1.206     0.228             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.9305     0.113      8.203     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \        0.0752     0.021      3.630     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.3888     0.073      5.293     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
