modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.11012894586707904
    - -0.18390107581370715
    - -0.4227139435489695
    - -0.050635159857892124
    - 0.030208516702439535
    - 0.34117763031175996
    - -0.16977030990477124
    - -0.03723604682298216
    - 0.2018690404039088
    - 0.056789606630251906
    - 1.0073999759925538
    - -0.03572882704495233
    - -0.2531832106533525
    - 0.06800500750938042
    - 0.05694568296972183
    - 0.012913767185000627
    - -0.21664233158681284
    - -0.013440854519744581
    - -1.4541914711731683
    - 0.8757734495480316
    - 0.6831098964133074
    - 0.7015273337321691
    - -1.4344331527939482
    - -0.7824329280722387
    - 0.36188389463417947
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          60,964\nModel:\
        \         Multinomial Logit   Df Residuals:              60,939\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.349\nTime:       \
        \               22:16   Pseudo R-bar-squ.:          0.349\nAIC:          \
        \       365,614.737   Log-Likelihood:      -182,782.369\nBIC:            \
        \     365,840.188   LL-Null:             -280,749.595\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1101     0.000   -424.520    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1839   \
        \  0.006    -28.655     0.000             \nst_bg_mean_children          \
        \            -0.4227     0.011    -38.588     0.000             \nst_bg_mean_year_built\
        \                    -0.0506     0.007     -6.834     0.000             \n\
        st_bg_median_value_13_acs                 0.0302     0.008      3.825    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.3412   \
        \  0.013     26.608     0.000             \nst_bg_prop_units_sf          \
        \            -0.1698     0.014    -12.519     0.000             \nst_bg_ratio_households_to_units\
        \          -0.0372     0.009     -4.246     0.000             \nst_bg_total_units\
        \                         0.2019     0.004     46.229     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0568     0.003     18.413\
        \     0.000             \nst_density_units_90pct_plus               1.0074\
        \     0.006    175.925     0.000             \nst_pred_built_out_sf      \
        \               -0.0357     0.009     -4.171     0.000             \nst_pred_rich_owned_antique\
        \               -0.2532     0.018    -13.692     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0680     0.003     22.375     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0569     0.006      9.341     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0129     0.004      3.064     0.002             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.2166     0.040     -5.388     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.0134     0.014     -0.959     0.337             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.4542     0.074    -19.570     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.8758     0.086     10.139     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.6831     0.058     11.709     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.7015     0.048     14.562     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -1.4344     0.084    -17.137     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.7824     0.016    -47.901     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.3619     0.047      7.753     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
