modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.14206337339393404
    - 0.2115667323785992
    - -0.17665997205869063
    - -0.023099876292966268
    - 0.045791765278076504
    - -0.39363726640836694
    - -0.015117070125685
    - 0.3958717140423084
    - 0.24289156944335183
    - -0.16538036689051885
    - 0.15048792557136223
    - 0.010801563991242115
    - 0.011079873615422061
    - -0.022379796556807444
    - 0.06531461489712193
    - 0.12811269215535967
    - -0.13005779005715637
    - -0.176111881915803
    - 0.1911780478730576
    - -0.7152725685001455
    - -2.1162469191644315
    - 0.09124743590104754
    - 1.7586250631482365
    - 1.8623839252658096
    - -0.8369711780035166
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          28,566\nModel:\
        \         Multinomial Logit   Df Residuals:              28,541\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.080\nTime:       \
        \               21:07   Pseudo R-bar-squ.:          0.080\nAIC:          \
        \       242,139.083   Log-Likelihood:      -121,044.542\nBIC:            \
        \     242,345.583   LL-Null:             -131,551.292\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1421     0.000   -296.006    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.2116   \
        \  0.017     12.568     0.000             \nst_bg_mean_children          \
        \            -0.1767     0.015    -11.981     0.000             \nst_bg_mean_year_built\
        \                    -0.0231     0.013     -1.738     0.082             \n\
        st_bg_median_value_13_acs                 0.0458     0.013      3.457    \
        \ 0.001             \nst_bg_prop_hh_rent                       -0.3936   \
        \  0.023    -17.224     0.000             \nst_bg_prop_units_sf          \
        \            -0.0151     0.020     -0.753     0.452             \nst_bg_ratio_households_to_units\
        \           0.3959     0.010     37.924     0.000             \nst_bg_total_units\
        \                         0.2429     0.011     22.817     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1654     0.008    -20.200\
        \     0.000             \nst_density_units_90pct_plus               0.1505\
        \     0.009     17.480     0.000             \nst_pred_built_out_sf      \
        \                0.0108     0.011      0.973     0.330             \nst_pred_rich_owned_antique\
        \                0.0111     0.004      2.906     0.004             \nst_tracts_income_segment_1_hh\
        \            -0.0224     0.013     -1.782     0.075             \nst_tracts_income_segment_6_hh\
        \             0.0653     0.009      7.226     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.1281     0.017      7.652     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.1301     0.100     -1.304     0.192             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.1761     0.062     -2.846     0.004             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.1912     0.111      1.724     0.085             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.7153     0.120     -5.976     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -2.1162     0.151    -14.050     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.0912     0.170      0.536     0.592             \nst_zones_jobs_5_sum_5_min_sov\
        \             1.7586     0.232      7.571     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \        1.8624     0.075     24.753     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.8370     0.143     -5.867     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
