modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.10994201263376725
    - -0.28053926190246775
    - -0.4070473481248745
    - -0.05798781669951132
    - -0.45183650179554485
    - -0.6045460285230113
    - -0.05299090057657022
    - 0.18498392041549086
    - 0.25227807482109105
    - -0.015955363711214008
    - 0.5123092836410537
    - 0.0689292907413733
    - 0.08084481606871512
    - -0.05779260299697807
    - 0.03961172113939069
    - -0.17596889262581955
    - -0.9470469480190138
    - 0.2426497148871691
    - -0.2680432193071279
    - -0.5578847633602971
    - -0.44333572556272227
    - 0.5111994168498607
    - -0.39127421965753784
    - -0.49586330750231505
    - 0.8790683684793213
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         16,764\nModel:\
        \         Multinomial Logit   Df Residuals:             16,739\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-12   Pseudo R-squ.:             0.162\nTime:          \
        \            21:21   Pseudo R-bar-squ.:         0.162\nAIC:              \
        \   129,388.447   Log-Likelihood:      -64,669.224\nBIC:                 129,581.622\
        \   LL-Null:             -77,201.073\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1099     0.001   -160.873    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.2805   \
        \  0.013    -20.889     0.000             \nst_bg_mean_children          \
        \            -0.4070     0.012    -33.667     0.000             \nst_bg_mean_year_built\
        \                    -0.0580     0.012     -4.911     0.000             \n\
        st_bg_median_value_13_acs                -0.4518     0.016    -27.449    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.6045   \
        \  0.022    -28.113     0.000             \nst_bg_prop_units_sf          \
        \            -0.0530     0.020     -2.686     0.007             \nst_bg_ratio_households_to_units\
        \           0.1850     0.017     11.167     0.000             \nst_bg_total_units\
        \                         0.2523     0.013     19.622     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0160     0.008     -1.878\
        \     0.060             \nst_density_units_90pct_plus               0.5123\
        \     0.006     79.381     0.000             \nst_pred_built_out_sf      \
        \                0.0689     0.006     11.297     0.000             \nst_pred_rich_owned_antique\
        \                0.0808     0.007     10.956     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0578     0.010     -6.044     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0396     0.019      2.093     0.036             \nst_zones_density_units_ave_5_min_sov\
        \     -0.1760     0.038     -4.665     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.9470     0.053    -17.772     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.2426     0.027      9.075     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.2680     0.113     -2.363     0.018             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.5579     0.091     -6.101     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -0.4433     0.121     -3.671     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.5112     0.107      4.799     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.3913     0.145     -2.698     0.007             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.4959     0.017    -28.942     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.8791     0.042     20.775     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
