modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1507756614943043
    - -0.1143219890528833
    - 0.1909386572728925
    - 0.01179831086035751
    - -0.23279533064680574
    - -0.33491112310084487
    - 0.043463017943514495
    - 0.5975391554743518
    - 0.0849698341113935
    - -0.09639836896718337
    - 0.22212096528627692
    - 0.06167067192416677
    - -0.018341170428389453
    - -0.03083343840144201
    - 0.121213733471332
    - 0.05724763131972958
    - 0.6276068231290188
    - -0.2597473793641895
    - -0.13750997550987162
    - -0.3606509979299547
    - 0.7495327563473911
    - 0.42953218476022537
    - -0.8410728109647428
    - -0.30552937708425953
    - -1.013869028497881
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         104,212\nModel:\
        \         Multinomial Logit   Df Residuals:             104,187\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.109\nTime:       \
        \               19:40   Pseudo R-bar-squ.:          0.109\nAIC:          \
        \       855,032.486   Log-Likelihood:      -427,491.243\nBIC:            \
        \     855,271.340   LL-Null:             -479,913.995\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1508     0.000   -531.229    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1143   \
        \  0.008    -14.909     0.000             \nst_bg_mean_children          \
        \             0.1909     0.005     36.120     0.000             \nst_bg_mean_year_built\
        \                     0.0118     0.005      2.279     0.023             \n\
        st_bg_median_value_13_acs                -0.2328     0.006    -35.947    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.3349   \
        \  0.010    -33.343     0.000             \nst_bg_prop_units_sf          \
        \             0.0435     0.009      5.031     0.000             \nst_bg_ratio_households_to_units\
        \           0.5975     0.010     62.117     0.000             \nst_bg_total_units\
        \                         0.0850     0.004     23.808     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0964     0.005    -17.737\
        \     0.000             \nst_density_units_90pct_plus               0.2221\
        \     0.004     49.757     0.000             \nst_pred_built_out_sf      \
        \                0.0617     0.003     23.588     0.000             \nst_pred_rich_owned_antique\
        \               -0.0183     0.007     -2.543     0.011             \nst_tracts_income_segment_1_hh\
        \            -0.0308     0.006     -5.492     0.000             \nst_tracts_income_segment_6_hh\
        \             0.1212     0.005     22.850     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0572     0.006      9.311     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.6276     0.032     19.732     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.2597     0.038     -6.764     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.1375     0.061     -2.260     0.024             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.3607     0.046     -7.804     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.7495     0.065     11.578     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.4295     0.028     15.214     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.8411     0.070    -11.950     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.3055     0.010    -29.898     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -1.0139     0.042    -23.892     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
