modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.10069497645696128
    - 0.29658243901637155
    - -0.29278067756705695
    - -0.014999441927510968
    - -0.006252636785094713
    - 0.5463209867930346
    - -0.16917318463600162
    - -0.03716751297295257
    - 0.1881477313884831
    - 0.06349699517961716
    - 0.9401281364162284
    - -0.006270256528941305
    - -0.17741438737769522
    - 0.08492546912916073
    - 0.01670267509913965
    - -0.004265214894795252
    - -0.33238832692115244
    - -0.10980697547467297
    - -1.5863256002721358
    - 1.0789492818547068
    - 0.7089692943409054
    - -0.1534547518859609
    - -0.6075205569391644
    - -0.2096327096939465
    - 0.45412403967224785
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          41,675\nModel:\
        \         Multinomial Logit   Df Residuals:              41,650\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.277\nTime:       \
        \               22:46   Pseudo R-bar-squ.:          0.277\nAIC:          \
        \       277,466.754   Log-Likelihood:      -138,708.377\nBIC:            \
        \     277,682.695   LL-Null:             -191,920.468\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1007     0.000   -242.750    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.2966   \
        \  0.007     44.802     0.000             \nst_bg_mean_children          \
        \            -0.2928     0.012    -24.640     0.000             \nst_bg_mean_year_built\
        \                    -0.0150     0.009     -1.677     0.093             \n\
        st_bg_median_value_13_acs                -0.0063     0.009     -0.678    \
        \ 0.498             \nst_bg_prop_hh_rent                        0.5463   \
        \  0.015     36.942     0.000             \nst_bg_prop_units_sf          \
        \            -0.1692     0.015    -10.943     0.000             \nst_bg_ratio_households_to_units\
        \          -0.0372     0.011     -3.533     0.000             \nst_bg_total_units\
        \                         0.1881     0.006     31.435     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0635     0.004     16.459\
        \     0.000             \nst_density_units_90pct_plus               0.9401\
        \     0.007    141.111     0.000             \nst_pred_built_out_sf      \
        \               -0.0063     0.008     -0.834     0.404             \nst_pred_rich_owned_antique\
        \               -0.1774     0.017    -10.553     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0849     0.003     25.603     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0167     0.008      2.109     0.035             \nst_zones_density_units_ave_5_min_sov\
        \     -0.0043     0.005     -0.838     0.402             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.3324     0.041     -8.036     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.1098     0.018     -6.180     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.5863     0.091    -17.365     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             1.0789     0.106     10.131     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.7090     0.074      9.574     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.1535     0.051     -3.036     0.002             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.6075     0.095     -6.419     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.2096     0.020    -10.394     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.4541     0.049      9.236     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
