modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.081819053655783
    - 0.20363405924739758
    - -0.01086540672680553
    - 0.0292676953880673
    - -0.1250891142502416
    - -0.1740913876772581
    - 0.17625857330096315
    - 0.7671493257784172
    - 0.019291149354001638
    - -0.112463848361674
    - 0.23815349684635168
    - 0.046494687272715544
    - 0.019467388023583665
    - -0.03832839171017599
    - 0.04789287759221907
    - 0.21355835657276745
    - -0.25947123506165665
    - 0.17596027229587102
    - 0.005632498216058675
    - -0.5349373322135372
    - 0.08373527318499814
    - 0.5029578067531868
    - -0.05471260486450382
    - -0.28658420283868985
    - 0.03636548915373309
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         130,502\nModel:\
        \         Multinomial Logit   Df Residuals:             130,477\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.128\nTime:       \
        \               21:47   Pseudo R-bar-squ.:          0.128\nAIC:          \
        \     1,048,100.443   Log-Likelihood:      -524,025.221\nBIC:            \
        \   1,048,344.921   LL-Null:             -600,983.920\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.0818     0.000   -361.600    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.2036   \
        \  0.005     39.554     0.000             \nst_bg_mean_children          \
        \            -0.0109     0.004     -2.534     0.011             \nst_bg_mean_year_built\
        \                     0.0293     0.005      5.441     0.000             \n\
        st_bg_median_value_13_acs                -0.1251     0.006    -21.883    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.1741   \
        \  0.007    -23.999     0.000             \nst_bg_prop_units_sf          \
        \             0.1763     0.007     26.006     0.000             \nst_bg_ratio_households_to_units\
        \           0.7671     0.008     90.428     0.000             \nst_bg_total_units\
        \                         0.0193     0.004      4.778     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1125     0.004    -30.238\
        \     0.000             \nst_density_units_90pct_plus               0.2382\
        \     0.003     74.609     0.000             \nst_pred_built_out_sf      \
        \                0.0465     0.002     20.793     0.000             \nst_pred_rich_owned_antique\
        \                0.0195     0.003      5.895     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0383     0.006     -6.527     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0479     0.004     11.126     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.2136     0.014     15.624     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.2595     0.013    -20.310     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.1760     0.016     11.066     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.0056     0.026      0.219     0.826             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.5349     0.035    -15.362     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.0837     0.037      2.249     0.025             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.5030     0.034     15.004     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.0547     0.038     -1.447     0.148             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.2866     0.007    -42.308     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.0364     0.022      1.691     0.091             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
