modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.09073160476255585
    - 0.44212712909480584
    - -0.24222143475234567
    - 0.06722864325747575
    - 0.19831166155871346
    - 0.5960762165052902
    - -0.08991454342737948
    - 0.28926994723849986
    - 0.191470311597435
    - 0.0655008069155603
    - 0.7021938466309791
    - -0.041722025388161096
    - -0.1566205067840457
    - 0.10213843665973797
    - 0.07061522924873433
    - -0.10073384060814607
    - 0.022345367044081185
    - -0.02799705416066661
    - 0.017262657520599023
    - -0.29455069475133755
    - 0.009972207007540004
    - 0.26173304954578414
    - -0.10632118037905411
    - 0.15344509758673233
    - 0.017485149969690396
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         15,245\nModel:\
        \         Multinomial Logit   Df Residuals:             15,220\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.340\nTime:          \
        \            22:49   Pseudo R-bar-squ.:         0.340\nAIC:              \
        \    92,679.496   Log-Likelihood:      -46,314.748\nBIC:                 \
        \ 92,870.297   LL-Null:             -70,205.819\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.0907     0.001   -157.160    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.4421   \
        \  0.017     26.599     0.000             \nst_bg_mean_children          \
        \            -0.2422     0.016    -15.278     0.000             \nst_bg_mean_year_built\
        \                     0.0672     0.019      3.619     0.000             \n\
        st_bg_median_value_13_acs                 0.1983     0.017     11.530    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5961   \
        \  0.023     26.274     0.000             \nst_bg_prop_units_sf          \
        \            -0.0899     0.023     -3.935     0.000             \nst_bg_ratio_households_to_units\
        \           0.2893     0.023     12.622     0.000             \nst_bg_total_units\
        \                         0.1915     0.013     14.632     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0655     0.006     10.259\
        \     0.000             \nst_density_units_90pct_plus               0.7022\
        \     0.006    111.027     0.000             \nst_pred_built_out_sf      \
        \               -0.0417     0.011     -3.875     0.000             \nst_pred_rich_owned_antique\
        \               -0.1566     0.015    -10.466     0.000             \nst_tracts_income_segment_1_hh\
        \             0.1021     0.021      4.958     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0706     0.013      5.326     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.1007     0.025     -4.067     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.0223     0.108      0.207     0.836             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.0280     0.069     -0.405     0.685             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.0173     0.129      0.134     0.894             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.2946     0.030     -9.864     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.0100     0.171      0.058     0.953             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.2617     0.129      2.030     0.042             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.1063     0.290     -0.367     0.714             \nst_zones_total_jobs_sum_20_min_sov\
        \        0.1534     0.037      4.122     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.0175     0.137      0.128     0.898             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
