modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.07998520832778541
    - -0.6249614645600122
    - -0.6010619025749665
    - -0.10998449895047435
    - -0.03497566302846522
    - -1.0284528225286427
    - -0.378980010162387
    - 0.5767159076458263
    - 0.1442058133056146
    - -0.07410258885628944
    - 0.38215922566567767
    - 0.03513409513973757
    - 0.012828574905708942
    - 0.3698863488933583
    - -0.0713256864260379
    - -0.3342918918095981
    - 0.18336270875574517
    - -0.4329283573133889
    - 0.6854763816849682
    - -0.22234157983585784
    - -1.0871153754310778
    - -0.5585088542326095
    - 0.9204205422343789
    - -0.07681203560428085
    - 0.43892435049263695
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,597\nModel:\
        \         Multinomial Logit   Df Residuals:              7,572\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.268\nTime:          \
        \            18:36   Pseudo R-bar-squ.:         0.267\nAIC:              \
        \    51,255.706   Log-Likelihood:      -25,602.853\nBIC:                 \
        \ 51,429.093   LL-Null:             -34,985.478\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.0800     0.001   -128.304    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.6250   \
        \  0.027    -23.148     0.000             \nst_bg_mean_children          \
        \            -0.6011     0.023    -26.220     0.000             \nst_bg_mean_year_built\
        \                    -0.1100     0.022     -5.043     0.000             \n\
        st_bg_median_value_13_acs                -0.0350     0.025     -1.397    \
        \ 0.162             \nst_bg_prop_hh_rent                       -1.0285   \
        \  0.032    -32.415     0.000             \nst_bg_prop_units_sf          \
        \            -0.3790     0.029    -13.154     0.000             \nst_bg_ratio_households_to_units\
        \           0.5767     0.040     14.457     0.000             \nst_bg_total_units\
        \                         0.1442     0.019      7.471     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0741     0.013     -5.597\
        \     0.000             \nst_density_units_90pct_plus               0.3822\
        \     0.009     40.812     0.000             \nst_pred_built_out_sf      \
        \                0.0351     0.008      4.592     0.000             \nst_pred_rich_owned_antique\
        \                0.0128     0.010      1.345     0.179             \nst_tracts_income_segment_1_hh\
        \             0.3699     0.028     13.364     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.0713     0.019     -3.783     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.3343     0.032    -10.610     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.1834     0.158      1.163     0.245             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.4329     0.098     -4.432     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.6855     0.179      3.835     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.2223     0.045     -4.889     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.0871     0.235     -4.628     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.5585     0.176     -3.168     0.002             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.9204     0.384      2.400     0.016             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.0768     0.054     -1.410     0.158             \nst_zones_total_units_sum_10_min_sov\
        \       0.4389     0.201      2.182     0.029             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
