modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.08769791073102097
    - -0.1544224867276047
    - -0.37656149348066764
    - -0.11210323977442173
    - 5.83506843107076e-05
    - 0.5622453364394795
    - 0.05497672340756609
    - 0.20052467166360308
    - 0.031042941998182035
    - 0.07177293964364487
    - 0.7957142395360608
    - 0.05613095527790556
    - -0.18308232727535598
    - -0.0351416111887473
    - 0.1118098523704346
    - 0.4239672757756616
    - -0.054820570784754434
    - 0.3105842287947891
    - 0.17910601290443978
    - -0.3609785233205295
    - 0.04397562510472146
    - -0.26044844561612523
    - 0.212459098023719
    - -0.25054742452345713
    - -0.24142737823893293
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          42,415\nModel:\
        \         Multinomial Logit   Df Residuals:              42,390\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.443\nTime:       \
        \               22:26   Pseudo R-bar-squ.:          0.443\nAIC:          \
        \       217,649.569   Log-Likelihood:      -108,799.785\nBIC:            \
        \     217,865.951   LL-Null:             -195,328.293\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.0877     0.000   -223.874    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1544   \
        \  0.008    -20.153     0.000             \nst_bg_mean_children          \
        \            -0.3766     0.008    -47.881     0.000             \nst_bg_mean_year_built\
        \                    -0.1121     0.011    -10.627     0.000             \n\
        st_bg_median_value_13_acs                 0.0001     0.010      0.006    \
        \ 0.995             \nst_bg_prop_hh_rent                        0.5622   \
        \  0.015     38.345     0.000             \nst_bg_prop_units_sf          \
        \             0.0550     0.015      3.690     0.000             \nst_bg_ratio_households_to_units\
        \           0.2005     0.013     15.964     0.000             \nst_bg_total_units\
        \                         0.0310     0.006      5.629     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0718     0.004     17.559\
        \     0.000             \nst_density_units_90pct_plus               0.7957\
        \     0.004    202.873     0.000             \nst_pred_built_out_sf      \
        \                0.0561     0.009      5.939     0.000             \nst_pred_rich_owned_antique\
        \               -0.1831     0.019     -9.611     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0351     0.007     -5.162     0.000             \nst_tracts_income_segment_6_hh\
        \             0.1118     0.009     12.596     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.4240     0.029     14.713     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.0548     0.026     -2.138     0.033             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.3106     0.028     11.241     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.1791     0.043      4.139     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.3610     0.064     -5.642     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.0440     0.076      0.582     0.561             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.2604     0.055     -4.719     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.2125     0.072      2.937     0.003             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.2505     0.014    -18.023     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.2414     0.043     -5.606     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
