modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1642526902935518
    - -0.14767340463042955
    - 0.10454876794285742
    - -0.03368551820998266
    - -0.379762209342815
    - 0.5961360202575159
    - 0.1958855858884516
    - 0.4340725204935628
    - 0.1463382473541187
    - 0.03213754703838952
    - 0.5751020669561456
    - 0.07843278504003863
    - -0.13046910912281054
    - -0.015509465646204203
    - 0.10735070000849731
    - 0.06973789653488169
    - 0.25637444135536197
    - -0.3238424425790964
    - -0.07878129364804481
    - -0.5417011516184861
    - 0.6385762571713768
    - 0.19305119145609062
    - -0.40156617482562235
    - -0.21622878196526074
    - -0.6882102311869351
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          66,877\nModel:\
        \         Multinomial Logit   Df Residuals:              66,852\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.247\nTime:       \
        \               23:21   Pseudo R-bar-squ.:          0.247\nAIC:          \
        \       463,720.951   Log-Likelihood:      -231,835.475\nBIC:            \
        \     463,948.716   LL-Null:             -307,979.967\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1643     0.000   -445.582    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1477   \
        \  0.009    -16.757     0.000             \nst_bg_mean_children          \
        \             0.1045     0.006     18.357     0.000             \nst_bg_mean_year_built\
        \                    -0.0337     0.007     -5.179     0.000             \n\
        st_bg_median_value_13_acs                -0.3798     0.009    -42.013    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5961   \
        \  0.011     53.111     0.000             \nst_bg_prop_units_sf          \
        \             0.1959     0.010     19.746     0.000             \nst_bg_ratio_households_to_units\
        \           0.4341     0.010     43.552     0.000             \nst_bg_total_units\
        \                         0.1463     0.006     26.150     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0321     0.004      7.273\
        \     0.000             \nst_density_units_90pct_plus               0.5751\
        \     0.003    177.597     0.000             \nst_pred_built_out_sf      \
        \                0.0784     0.004     20.688     0.000             \nst_pred_rich_owned_antique\
        \               -0.1305     0.020     -6.422     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0155     0.005     -2.881     0.004             \nst_tracts_income_segment_6_hh\
        \             0.1074     0.009     11.992     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0697     0.007     10.105     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.2564     0.041      6.296     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.3238     0.046     -6.972     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.0788     0.075     -1.046     0.296             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.5417     0.059     -9.105     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.6386     0.080      8.013     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.1931     0.035      5.463     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.4016     0.086     -4.692     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.2162     0.012    -18.375     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.6882     0.055    -12.624     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
