modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15859596935980783
    - 0.34033816533423733
    - -0.10497505769339767
    - 0.1412778826107233
    - -0.007709736502253716
    - 0.6500824699104057
    - 0.2128792960337242
    - 0.43398089384881816
    - 0.17571307232752298
    - 0.001719311791478141
    - 0.519543861105363
    - 0.0917310523613598
    - -0.1902097658852327
    - 0.012470049962480755
    - 0.03395472440108832
    - 0.1036878505503029
    - -1.803030202101772
    - 0.5919710013298215
    - 1.748615769919904
    - -1.1129663028394683
    - -2.9970526415400673
    - 0.9556769940137355
    - 0.6051648426812561
    - 2.2281094738038894
    - 0.8989211336545363
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          5,377\nModel:\
        \         Multinomial Logit   Df Residuals:              5,352\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-10   Pseudo R-squ.:             0.145\nTime:          \
        \            00:26   Pseudo R-bar-squ.:         0.144\nAIC:              \
        \    42,413.365   Log-Likelihood:      -21,181.683\nBIC:                 \
        \ 42,578.112   LL-Null:             -24,762.000\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1586     0.001   -133.968    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3403   \
        \  0.032     10.576     0.000             \nst_bg_mean_children          \
        \            -0.1050     0.029     -3.569     0.000             \nst_bg_mean_year_built\
        \                     0.1413     0.029      4.889     0.000             \n\
        st_bg_median_value_13_acs                -0.0077     0.028     -0.277    \
        \ 0.782             \nst_bg_prop_hh_rent                        0.6501   \
        \  0.049     13.206     0.000             \nst_bg_prop_units_sf          \
        \             0.2129     0.044      4.879     0.000             \nst_bg_ratio_households_to_units\
        \           0.4340     0.022     19.797     0.000             \nst_bg_total_units\
        \                         0.1757     0.024      7.326     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0017     0.012      0.147\
        \     0.884             \nst_density_units_90pct_plus               0.5195\
        \     0.011     46.205     0.000             \nst_pred_built_out_sf      \
        \                0.0917     0.033      2.814     0.005             \nst_pred_rich_owned_antique\
        \               -0.1902     0.022     -8.480     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0125     0.031      0.403     0.687             \nst_tracts_income_segment_6_hh\
        \             0.0340     0.023      1.502     0.133             \nst_zones_density_units_ave_5_min_sov\
        \      0.1037     0.037      2.802     0.005             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -1.8030     0.261     -6.911     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.5920     0.146      4.066     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             1.7486     0.243      7.187     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.1130     0.241     -4.621     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -2.9971     0.352     -8.525     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.9557     0.402      2.378     0.017             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.6052     0.570      1.062     0.288             \nst_zones_total_jobs_sum_20_min_sov\
        \        2.2281     0.223      9.976     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.8989     0.392      2.295     0.022             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
