modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.14379301734271907
    - 0.28018639018680375
    - -0.014480890106532762
    - 0.0871071033942518
    - -0.6342610749786186
    - 0.832274694557714
    - 0.1931819798893439
    - 0.6256093520564667
    - -0.15395815174186628
    - -0.03648787606982808
    - 0.5923082422497319
    - 0.09688116264335005
    - -0.028519097662990735
    - -0.05524407870371645
    - -0.2277816543509785
    - -0.15415117270596862
    - -0.8217665220786835
    - -1.2210081040176288
    - 0.2535244115310148
    - -1.0015733431658764
    - 1.1633203647990893
    - 1.155676393985925
    - -0.8712602164760005
    - -0.5014934001228649
    - 0.42631456903367054
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,244\nModel:\
        \         Multinomial Logit   Df Residuals:              7,219\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-10   Pseudo R-squ.:             0.230\nTime:          \
        \            00:41   Pseudo R-bar-squ.:         0.229\nAIC:              \
        \    51,446.330   Log-Likelihood:      -25,698.165\nBIC:                 \
        \ 51,618.528   LL-Null:             -33,359.853\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1438     0.001   -102.634    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.2802   \
        \  0.024     11.762     0.000             \nst_bg_mean_children          \
        \            -0.0145     0.020     -0.724     0.469             \nst_bg_mean_year_built\
        \                     0.0871     0.018      4.781     0.000             \n\
        st_bg_median_value_13_acs                -0.6343     0.046    -13.844    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.8323   \
        \  0.033     24.862     0.000             \nst_bg_prop_units_sf          \
        \             0.1932     0.027      7.134     0.000             \nst_bg_ratio_households_to_units\
        \           0.6256     0.029     21.385     0.000             \nst_bg_total_units\
        \                        -0.1540     0.020     -7.515     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0365     0.015     -2.445\
        \     0.014             \nst_density_units_90pct_plus               0.5923\
        \     0.010     59.529     0.000             \nst_pred_built_out_sf      \
        \                0.0969     0.012      8.407     0.000             \nst_pred_rich_owned_antique\
        \               -0.0285     0.051     -0.558     0.577             \nst_tracts_income_segment_1_hh\
        \            -0.0552     0.020     -2.719     0.007             \nst_tracts_income_segment_6_hh\
        \            -0.2278     0.069     -3.281     0.001             \nst_zones_density_units_ave_5_min_sov\
        \     -0.1542     0.071     -2.174     0.030             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.8218     0.092     -8.932     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -1.2210     0.113    -10.762     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.2535     0.174      1.460     0.144             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.0016     0.197     -5.079     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             1.1633     0.176      6.596     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             1.1557     0.183      6.321     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.8713     0.242     -3.595     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.5015     0.032    -15.506     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.4263     0.133      3.197     0.001             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
