modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12571090205147414
    - -0.10877397893160252
    - 0.2096289370953149
    - -0.04044083372559602
    - 0.10280570070935527
    - -0.698768561928747
    - -0.2528820782722877
    - 0.0659086551178831
    - 0.1180660065692083
    - -0.01698889705511601
    - 0.5926346189577223
    - 0.015687044883525552
    - 0.08541962440756837
    - -0.008395946843113586
    - 0.04771407006888398
    - -0.004933508276693087
    - -0.023846937042665793
    - -0.14508512384747288
    - -1.083360432381241
    - 0.8371492794545025
    - -1.0974564675345222
    - 0.9485476739045628
    - -0.23105922458373632
    - -0.7510154977794667
    - -0.3056813338890024
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          45,460\nModel:\
        \         Multinomial Logit   Df Residuals:              45,435\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.212\nTime:       \
        \               19:54   Pseudo R-bar-squ.:          0.212\nAIC:          \
        \       330,063.459   Log-Likelihood:      -165,006.729\nBIC:            \
        \     330,281.574   LL-Null:             -209,351.037\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1257     0.000   -361.919    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1088   \
        \  0.009    -11.452     0.000             \nst_bg_mean_children          \
        \             0.2096     0.010     21.001     0.000             \nst_bg_mean_year_built\
        \                    -0.0404     0.010     -4.147     0.000             \n\
        st_bg_median_value_13_acs                 0.1028     0.012      8.698    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.6988   \
        \  0.015    -47.998     0.000             \nst_bg_prop_units_sf          \
        \            -0.2529     0.013    -19.695     0.000             \nst_bg_ratio_households_to_units\
        \           0.0659     0.011      5.879     0.000             \nst_bg_total_units\
        \                         0.1181     0.007     17.535     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0170     0.004     -4.039\
        \     0.000             \nst_density_units_90pct_plus               0.5926\
        \     0.004    140.450     0.000             \nst_pred_built_out_sf      \
        \                0.0157     0.003      5.812     0.000             \nst_pred_rich_owned_antique\
        \                0.0854     0.003     24.712     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0084     0.006     -1.368     0.171             \nst_tracts_income_segment_6_hh\
        \             0.0477     0.008      6.130     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.0049     0.005     -1.033     0.301             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.0238     0.057     -0.421     0.674             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.1451     0.019     -7.443     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.0834     0.115     -9.452     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.8371     0.128      6.560     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.0975     0.089    -12.263     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.9485     0.071     13.330     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.2311     0.138     -1.676     0.094             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.7510     0.019    -39.226     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.3057     0.065     -4.705     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
