modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.14941894865284056
    - -0.38814433565233886
    - -0.30432860879776547
    - -0.15844296828073484
    - -0.050845594101652354
    - -0.5599689017192755
    - -0.1680636311071251
    - 0.6088627187201401
    - 0.27730001086930495
    - -0.10775496552526961
    - 0.3017475381382761
    - 0.07874471360766165
    - -0.05151111555456448
    - 0.09158416151896984
    - 0.49944903932581963
    - 0.4462690401517846
    - 2.2221334745178525
    - -0.7550602248459045
    - -2.6442319133488024
    - 0.9025178980956798
    - -7.935856696501426
    - 1.6179312534151835
    - 6.465813750381351
    - -0.5086034023611925
    - -0.7725897271344334
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,348\nModel:\
        \         Multinomial Logit   Df Residuals:              1,323\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.097\nTime:          \
        \            18:32   Pseudo R-bar-squ.:         0.093\nAIC:              \
        \    11,266.448   Log-Likelihood:       -5,608.224\nBIC:                 \
        \ 11,396.607   LL-Null:              -6,207.769\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1494     0.002   -80.857     0.000\
        \             \nst_bg_mean_age_of_head                   -0.3881     0.065\
        \    -5.995     0.000             \nst_bg_mean_children                  \
        \    -0.3043     0.061    -5.011     0.000             \nst_bg_mean_year_built\
        \                    -0.1584     0.060    -2.630     0.009             \n\
        st_bg_median_value_13_acs                -0.0508     0.072    -0.702     0.483\
        \             \nst_bg_prop_hh_rent                       -0.5600     0.082\
        \    -6.864     0.000             \nst_bg_prop_units_sf                  \
        \    -0.1681     0.070    -2.400     0.016             \nst_bg_ratio_households_to_units\
        \           0.6089     0.044    13.829     0.000             \nst_bg_total_units\
        \                         0.2773     0.061     4.535     0.000           \
        \  \nst_density_jobs_90pct_plus               -0.1078     0.037    -2.879\
        \     0.004             \nst_density_units_90pct_plus               0.3017\
        \     0.035     8.566     0.000             \nst_pred_built_out_sf       \
        \               0.0787     0.040     1.987     0.047             \nst_pred_rich_owned_antique\
        \               -0.0515     0.060    -0.861     0.389             \nst_tracts_income_segment_1_hh\
        \             0.0916     0.094     0.974     0.330             \nst_tracts_income_segment_6_hh\
        \             0.4994     0.144     3.461     0.001             \nst_zones_density_units_ave_5_min_sov\
        \      0.4463     0.109     4.104     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       2.2221     0.667     3.330     0.001             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.7551     0.436    -1.733     0.083             \nst_zones_jobs_1_sum_5_min_sov\
        \            -2.6442     0.663    -3.986     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.9025     0.846     1.067     0.286             \nst_zones_jobs_3_sum_5_min_sov\
        \            -7.9359     1.738    -4.566     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             1.6179     1.402     1.154     0.249             \nst_zones_jobs_5_sum_5_min_sov\
        \             6.4658     3.029     2.135     0.033             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.5086     0.554    -0.918     0.359             \nst_zones_total_units_sum_10_min_sov\
        \      -0.7726     0.943    -0.820     0.412             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
