modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1515863582169417
    - -0.08997862554987843
    - -0.329121850757473
    - -0.06335100708883942
    - -0.1860091469347913
    - 0.6006384934340083
    - 0.18082617382254337
    - 0.231853208314431
    - 0.1266122213285174
    - 0.06601312638388203
    - 0.609727559739046
    - 0.009285990441175927
    - -0.18643501039621602
    - 0.12779942888874518
    - -0.09829279690345587
    - 0.1489459889107691
    - -0.1463370936870557
    - -1.41302875832999
    - -0.5964662725585007
    - 0.20773019004438603
    - -1.212623403535866
    - 0.2050700584781648
    - 1.4427261122333657
    - -0.05994008455885061
    - 0.4308969631507283
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         10,202\nModel:\
        \         Multinomial Logit   Df Residuals:             10,177\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.242\nTime:          \
        \            22:30   Pseudo R-bar-squ.:         0.242\nAIC:              \
        \    71,241.018   Log-Likelihood:      -35,595.509\nBIC:                 \
        \ 71,421.777   LL-Null:             -46,981.946\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1516     0.001   -134.753    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.0900   \
        \  0.017     -5.152     0.000             \nst_bg_mean_children          \
        \            -0.3291     0.017    -19.114     0.000             \nst_bg_mean_year_built\
        \                    -0.0634     0.019     -3.285     0.001             \n\
        st_bg_median_value_13_acs                -0.1860     0.022     -8.322    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.6006   \
        \  0.027     22.621     0.000             \nst_bg_prop_units_sf          \
        \             0.1808     0.023      7.715     0.000             \nst_bg_ratio_households_to_units\
        \           0.2319     0.013     17.964     0.000             \nst_bg_total_units\
        \                         0.1266     0.018      6.929     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0660     0.009      7.002\
        \     0.000             \nst_density_units_90pct_plus               0.6097\
        \     0.008     74.198     0.000             \nst_pred_built_out_sf      \
        \                0.0093     0.014      0.670     0.503             \nst_pred_rich_owned_antique\
        \               -0.1864     0.041     -4.513     0.000             \nst_tracts_income_segment_1_hh\
        \             0.1278     0.015      8.520     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.0983     0.030     -3.289     0.001             \nst_zones_density_units_ave_5_min_sov\
        \      0.1489     0.044      3.351     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.1463     0.099     -1.484     0.138             \nst_zones_jobs_0_sum_5_min_sov\
        \            -1.4130     0.121    -11.648     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.5965     0.126     -4.740     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.2077     0.114      1.819     0.069             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.2126     0.158     -7.669     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.2051     0.096      2.143     0.032             \nst_zones_jobs_5_sum_5_min_sov\
        \             1.4427     0.175      8.267     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.0599     0.034     -1.753     0.080             \nst_zones_total_units_sum_10_min_sov\
        \       0.4309     0.113      3.827     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
