modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.16884180620218708
    - 0.04738691687632525
    - 0.25024344899547
    - -0.1683937043302854
    - -0.0897812356969749
    - -0.195122775551773
    - 0.24613642070606215
    - 0.4930496195956271
    - 0.35782952270733026
    - -0.1344782113581364
    - 0.13053502103243184
    - -0.004330020241912164
    - 0.04808095659852234
    - -0.08034692939119426
    - 0.5280201115789566
    - 0.4036637720318825
    - -1.8556551620574218
    - -1.3084885100098655
    - -1.6494969869880367
    - -0.5866472328114125
    - -7.2643122608044335
    - -4.637259171594503
    - 14.57850946187011
    - -1.1058950295435335
    - 2.79334673617395
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         10,327\nModel:\
        \         Multinomial Logit   Df Residuals:             10,302\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.091\nTime:          \
        \            19:47   Pseudo R-bar-squ.:         0.090\nAIC:              \
        \    86,524.136   Log-Likelihood:      -43,237.068\nBIC:                 \
        \ 86,705.199   LL-Null:             -47,557.593\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1688     0.001   -190.104    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.0474   \
        \  0.024      1.990     0.047             \nst_bg_mean_children          \
        \             0.2502     0.021     11.878     0.000             \nst_bg_mean_year_built\
        \                    -0.1684     0.019     -9.074     0.000             \n\
        st_bg_median_value_13_acs                -0.0898     0.026     -3.462    \
        \ 0.001             \nst_bg_prop_hh_rent                       -0.1951   \
        \  0.028     -6.896     0.000             \nst_bg_prop_units_sf          \
        \             0.2461     0.027      9.008     0.000             \nst_bg_ratio_households_to_units\
        \           0.4930     0.016     30.191     0.000             \nst_bg_total_units\
        \                         0.3578     0.022     16.476     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1345     0.016     -8.511\
        \     0.000             \nst_density_units_90pct_plus               0.1305\
        \     0.017      7.518     0.000             \nst_pred_built_out_sf      \
        \               -0.0043     0.015     -0.298     0.766             \nst_pred_rich_owned_antique\
        \                0.0481     0.017      2.909     0.004             \nst_tracts_income_segment_1_hh\
        \            -0.0803     0.031     -2.560     0.010             \nst_tracts_income_segment_6_hh\
        \             0.5280     0.048     10.899     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.4037     0.038     10.690     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -1.8557     0.252     -7.356     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -1.3085     0.151     -8.693     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.6495     0.248     -6.660     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.5866     0.302     -1.942     0.052             \nst_zones_jobs_3_sum_5_min_sov\
        \            -7.2643     0.667    -10.894     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -4.6373     0.498     -9.304     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            14.5785     1.161     12.553     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -1.1059     0.216     -5.123     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       2.7933     0.364      7.683     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
