modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1268320199412977
    - 0.3687083041113504
    - -0.20173951883733748
    - 0.021668131966273485
    - -0.058822885224233804
    - 0.6916010793005554
    - 0.150587254183245
    - 0.19288348021471335
    - 0.20620820625991784
    - 0.12697547805167547
    - 0.7866104326191543
    - 0.031029619457979385
    - -0.06628931783604815
    - -0.033675178279468136
    - -0.006010163217293072
    - 0.07766467566800264
    - 0.6275995045802202
    - 0.22203623813079312
    - -0.1123058818447262
    - 0.21682096483276012
    - 0.343218507792342
    - 0.3863255023910019
    - -1.1709068012027386
    - -0.22301611170675886
    - -0.19391178848637983
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          40,314\nModel:\
        \         Multinomial Logit   Df Residuals:              40,289\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.288\nTime:       \
        \               22:35   Pseudo R-bar-squ.:          0.288\nAIC:          \
        \       264,515.222   Log-Likelihood:      -132,232.611\nBIC:            \
        \     264,730.333   LL-Null:             -185,652.831\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1268     0.001   -207.794    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3687   \
        \  0.007     56.391     0.000             \nst_bg_mean_children          \
        \            -0.2017     0.008    -26.102     0.000             \nst_bg_mean_year_built\
        \                     0.0217     0.008      2.698     0.007             \n\
        st_bg_median_value_13_acs                -0.0588     0.011     -5.507    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.6916   \
        \  0.014     49.095     0.000             \nst_bg_prop_units_sf          \
        \             0.1506     0.014     10.597     0.000             \nst_bg_ratio_households_to_units\
        \           0.1929     0.011     17.711     0.000             \nst_bg_total_units\
        \                         0.2062     0.009     22.684     0.000          \
        \   \nst_density_jobs_90pct_plus                0.1270     0.004     31.657\
        \     0.000             \nst_density_units_90pct_plus               0.7866\
        \     0.004    194.689     0.000             \nst_pred_built_out_sf      \
        \                0.0310     0.008      4.004     0.000             \nst_pred_rich_owned_antique\
        \               -0.0663     0.012     -5.497     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0337     0.005     -7.021     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.0060     0.016     -0.379     0.705             \nst_zones_density_units_ave_5_min_sov\
        \      0.0777     0.023      3.339     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.6276     0.042     15.059     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.2220     0.018     12.247     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.1123     0.078     -1.434     0.152             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.2168     0.063      3.424     0.001             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.3432     0.085      4.058     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.3863     0.077      5.038     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -1.1709     0.104    -11.222     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.2230     0.013    -16.731     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.1939     0.030     -6.413     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
