modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12405923422660461
    - -0.38069561772233607
    - -0.5625315567401381
    - 0.03567919254992522
    - -0.14250682295664593
    - -0.8488294278535143
    - -0.2551648548802844
    - 0.22387272631535426
    - 0.19814182578392664
    - -0.14929563567072598
    - 0.34323619231887503
    - 0.04848475956565964
    - -0.014347162595958921
    - 0.19485364875860667
    - 0.02831267749571832
    - -0.008361635279075018
    - -1.3614770893668093
    - -0.28432943578141473
    - 0.89858150122814
    - -0.7445991135620935
    - -1.6801161119510892
    - 1.1943141219723175
    - 0.05569661609222465
    - 2.4339668370219325
    - -0.18171460142736914
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,765\nModel:\
        \         Multinomial Logit   Df Residuals:              2,740\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.094\nTime:          \
        \            18:32   Pseudo R-bar-squ.:         0.092\nAIC:              \
        \    23,121.439   Log-Likelihood:      -11,535.719\nBIC:                 \
        \ 23,269.559   LL-Null:             -12,733.296\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1241     0.001   -101.040    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.3807   \
        \  0.054     -7.045     0.000             \nst_bg_mean_children          \
        \            -0.5625     0.049    -11.399     0.000             \nst_bg_mean_year_built\
        \                     0.0357     0.042      0.853     0.393             \n\
        st_bg_median_value_13_acs                -0.1425     0.040     -3.557    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.8488   \
        \  0.066    -12.875     0.000             \nst_bg_prop_units_sf          \
        \            -0.2552     0.055     -4.636     0.000             \nst_bg_ratio_households_to_units\
        \           0.2239     0.031      7.251     0.000             \nst_bg_total_units\
        \                         0.1981     0.034      5.883     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1493     0.022     -6.829\
        \     0.000             \nst_density_units_90pct_plus               0.3432\
        \     0.020     17.490     0.000             \nst_pred_built_out_sf      \
        \                0.0485     0.037      1.328     0.184             \nst_pred_rich_owned_antique\
        \               -0.0143     0.015     -0.950     0.342             \nst_tracts_income_segment_1_hh\
        \             0.1949     0.043      4.566     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0283     0.031      0.926     0.355             \nst_zones_density_units_ave_5_min_sov\
        \     -0.0084     0.053     -0.158     0.874             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -1.3615     0.333     -4.090     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.2843     0.198     -1.437     0.151             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.8986     0.326      2.753     0.006             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.7446     0.336     -2.218     0.027             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.6801     0.490     -3.428     0.001             \nst_zones_jobs_4_sum_5_min_sov\
        \             1.1943     0.568      2.103     0.035             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.0557     0.772      0.072     0.943             \nst_zones_total_jobs_sum_20_min_sov\
        \        2.4340     0.256      9.523     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.1817     0.483     -0.377     0.707             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
