modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1324338010396964
    - 0.4043487987793894
    - -0.14202839117265736
    - -0.05125320041747
    - -0.15021548005498134
    - 0.7163509507341236
    - 0.03273612421111143
    - 0.3123425103438837
    - 0.15412939557938413
    - 0.10800045938512634
    - 0.7305023027377281
    - 0.06571962777914339
    - -0.2117087423415385
    - 0.07888592613962275
    - 0.18994017569518082
    - 0.006997624656094308
    - 0.15389636376904947
    - 0.11909897315514638
    - -1.1170803182263662
    - 0.5093381841028414
    - 0.19564718857262148
    - -0.028112074533764846
    - 0.40781321052191255
    - -0.013814172406869343
    - -0.5634955307918158
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         18,418\nModel:\
        \         Multinomial Logit   Df Residuals:             18,393\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.275\nTime:          \
        \            22:37   Pseudo R-bar-squ.:         0.275\nAIC:              \
        \   123,051.361   Log-Likelihood:      -61,500.680\nBIC:                 123,246.888\
        \   LL-Null:             -84,818.024\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1324     0.001   -181.130    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.4043   \
        \  0.012     33.345     0.000             \nst_bg_mean_children          \
        \            -0.1420     0.012    -12.223     0.000             \nst_bg_mean_year_built\
        \                    -0.0513     0.012     -4.109     0.000             \n\
        st_bg_median_value_13_acs                -0.1502     0.017     -8.688    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.7164   \
        \  0.018     39.226     0.000             \nst_bg_prop_units_sf          \
        \             0.0327     0.017      1.955     0.051             \nst_bg_ratio_households_to_units\
        \           0.3123     0.019     16.383     0.000             \nst_bg_total_units\
        \                         0.1541     0.011     13.622     0.000          \
        \   \nst_density_jobs_90pct_plus                0.1080     0.007     15.873\
        \     0.000             \nst_density_units_90pct_plus               0.7305\
        \     0.006    130.527     0.000             \nst_pred_built_out_sf      \
        \                0.0657     0.009      7.054     0.000             \nst_pred_rich_owned_antique\
        \               -0.2117     0.042     -5.054     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0789     0.011      7.376     0.000             \nst_tracts_income_segment_6_hh\
        \             0.1899     0.016     12.019     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0070     0.013      0.556     0.578             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.1539     0.080      1.918     0.055             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.1191     0.085      1.396     0.163             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.1171     0.153     -7.311     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.5093     0.123      4.147     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.1956     0.164      1.191     0.234             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.0281     0.067     -0.417     0.676             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.4078     0.183      2.228     0.026             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.0138     0.022     -0.635     0.526             \nst_zones_total_units_sum_10_min_sov\
        \      -0.5635     0.106     -5.329     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
