modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15878436197937484
    - -0.3655061772679054
    - 0.012194458482463503
    - 0.06354556591520269
    - -0.6687693584759031
    - 0.34447516870435935
    - 0.07142027057721294
    - 0.6220496937063406
    - -0.01637096355832529
    - -0.005028108831048666
    - 0.5546746297683193
    - 0.10792261430361197
    - -0.015646266563344564
    - 0.009775905696916009
    - -0.5576405536353953
    - 0.33861860639682057
    - -0.7060709038848809
    - -0.6501349733614481
    - 0.32614149808890297
    - -0.27402992462171105
    - 0.9796800910870778
    - 0.4030828919378054
    - -0.8448374984591248
    - -0.5972081323853797
    - 0.17601666221787604
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          29,758\nModel:\
        \         Multinomial Logit   Df Residuals:              29,733\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-10   Pseudo R-squ.:              0.267\nTime:       \
        \               00:14   Pseudo R-bar-squ.:          0.267\nAIC:          \
        \       200,965.494   Log-Likelihood:      -100,457.747\nBIC:            \
        \     201,173.015   LL-Null:             -137,040.654\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1588     0.001   -220.561    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.3655   \
        \  0.012    -29.446     0.000             \nst_bg_mean_children          \
        \             0.0122     0.010      1.282     0.200             \nst_bg_mean_year_built\
        \                     0.0635     0.008      7.498     0.000             \n\
        st_bg_median_value_13_acs                -0.6688     0.023    -29.678    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.3445   \
        \  0.015     22.394     0.000             \nst_bg_prop_units_sf          \
        \             0.0714     0.013      5.592     0.000             \nst_bg_ratio_households_to_units\
        \           0.6220     0.010     60.816     0.000             \nst_bg_total_units\
        \                        -0.0164     0.011     -1.485     0.137          \
        \   \nst_density_jobs_90pct_plus               -0.0050     0.008     -0.653\
        \     0.514             \nst_density_units_90pct_plus               0.5547\
        \     0.005    110.551     0.000             \nst_pred_built_out_sf      \
        \                0.1079     0.005     20.226     0.000             \nst_pred_rich_owned_antique\
        \               -0.0156     0.032     -0.487     0.626             \nst_tracts_income_segment_1_hh\
        \             0.0098     0.010      0.961     0.337             \nst_tracts_income_segment_6_hh\
        \            -0.5576     0.033    -17.061     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.3386     0.035      9.728     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.7061     0.046    -15.354     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.6501     0.057    -11.475     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.3261     0.091      3.569     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.2740     0.110     -2.480     0.013             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.9797     0.085     11.513     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.4031     0.103      3.906     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -0.8448     0.136     -6.217     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.5972     0.016    -37.350     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.1760     0.069      2.545     0.011             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
