modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.13335195851682785
    - -0.12778997077211535
    - -0.3439198764262482
    - -0.04089910120807318
    - -0.13331980648066133
    - 0.45985748834118656
    - 0.05259230071832541
    - 0.18894907531407812
    - 0.2196985953713007
    - 0.0863857643057592
    - 0.7753044570910578
    - 0.04997044162440007
    - -0.05916070865443845
    - -0.08386932396858089
    - 0.059891759470467175
    - 0.22248364559685804
    - -0.4320403595734647
    - 0.33761466621058894
    - 0.2439478008352872
    - -0.09284557564366461
    - 0.5572583609818033
    - 0.5115667222198325
    - -1.554713530052789
    - -0.468725622082452
    - 0.2122758858033072
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          49,209\nModel:\
        \         Multinomial Logit   Df Residuals:              49,184\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.347\nTime:       \
        \               22:02   Pseudo R-bar-squ.:          0.346\nAIC:          \
        \       296,231.505   Log-Likelihood:      -148,090.752\nBIC:            \
        \     296,451.601   LL-Null:             -226,615.820\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1334     0.000   -279.442    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.1278   \
        \  0.006    -21.073     0.000             \nst_bg_mean_children          \
        \            -0.3439     0.007    -48.817     0.000             \nst_bg_mean_year_built\
        \                    -0.0409     0.007     -5.822     0.000             \n\
        st_bg_median_value_13_acs                -0.1333     0.010    -13.070    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.4599   \
        \  0.014     33.781     0.000             \nst_bg_prop_units_sf          \
        \             0.0526     0.014      3.828     0.000             \nst_bg_ratio_households_to_units\
        \           0.1889     0.010     19.327     0.000             \nst_bg_total_units\
        \                         0.2197     0.008     28.082     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0864     0.004     23.268\
        \     0.000             \nst_density_units_90pct_plus               0.7753\
        \     0.004    205.034     0.000             \nst_pred_built_out_sf      \
        \                0.0500     0.008      6.393     0.000             \nst_pred_rich_owned_antique\
        \               -0.0592     0.012     -5.071     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0839     0.004    -20.219     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0599     0.015      4.032     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.2225     0.022     10.231     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.4320     0.040    -10.668     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.3376     0.017     20.143     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.2439     0.074      3.301     0.001             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.0928     0.059     -1.575     0.115             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.5573     0.078      7.167     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.5116     0.071      7.176     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -1.5547     0.094    -16.463     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.4687     0.012    -39.163     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.2123     0.029      7.345     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
