modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15059375602502106
    - -0.5010239720180679
    - -0.05573925807094115
    - 0.06413366754132252
    - -0.31772925521002127
    - -0.6029121297315635
    - -0.04987168682867468
    - 1.1096964871754533
    - -0.015263973774498863
    - -0.19540422959897125
    - 0.1571433356897807
    - 0.09191719146149904
    - 0.10330519182200416
    - -0.05247719487415719
    - -0.43037167367602613
    - -0.08978907724776454
    - -1.1819218890021437
    - -1.1924684050696814
    - -0.034692073479508215
    - -0.7860521010368977
    - 1.4420805164388495
    - 0.011223386182380368
    - 0.8308417380819758
    - -0.8204636181863801
    - 1.085270062747935
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          36,354\nModel:\
        \         Multinomial Logit   Df Residuals:              36,329\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.207\nTime:       \
        \               20:32   Pseudo R-bar-squ.:          0.207\nAIC:          \
        \       265,534.082   Log-Likelihood:      -132,742.041\nBIC:            \
        \     265,746.608   LL-Null:             -167,416.357\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1506     0.001   -228.853    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.5010   \
        \  0.012    -40.656     0.000             \nst_bg_mean_children          \
        \            -0.0557     0.009     -5.888     0.000             \nst_bg_mean_year_built\
        \                     0.0641     0.009      7.194     0.000             \n\
        st_bg_median_value_13_acs                -0.3177     0.020    -15.840    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.6029   \
        \  0.017    -35.426     0.000             \nst_bg_prop_units_sf          \
        \            -0.0499     0.014     -3.502     0.000             \nst_bg_ratio_households_to_units\
        \           1.1097     0.019     59.941     0.000             \nst_bg_total_units\
        \                        -0.0153     0.009     -1.615     0.106          \
        \   \nst_density_jobs_90pct_plus               -0.1954     0.011    -18.497\
        \     0.000             \nst_density_units_90pct_plus               0.1571\
        \     0.009     16.999     0.000             \nst_pred_built_out_sf      \
        \                0.0919     0.004     21.778     0.000             \nst_pred_rich_owned_antique\
        \                0.1033     0.014      7.372     0.000             \nst_tracts_income_segment_1_hh\
        \            -0.0525     0.010     -5.424     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.4304     0.026    -16.290     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.0898     0.031     -2.907     0.004             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -1.1819     0.042    -28.029     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -1.1925     0.052    -22.882     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.0347     0.070     -0.494     0.621             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.7861     0.084     -9.353     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             1.4421     0.078     18.398     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.0112     0.075      0.149     0.881             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.8308     0.127      6.528     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.8205     0.014    -57.189     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       1.0853     0.065     16.673     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
