modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1397869345060253
    - -0.2622459972991709
    - -0.3318384881904764
    - -0.007537664530779397
    - -0.12895806070416355
    - 0.5567271390524953
    - 0.10398260433987765
    - 0.3542668146007496
    - 0.17734948542415058
    - 0.11135599402743132
    - 0.7154906559427585
    - 0.06823024423387886
    - -0.11594647198727964
    - 0.058349321551777
    - 0.22758675985068913
    - 0.035159864924932865
    - 0.9475593936916341
    - 0.006733337921750144
    - -1.238204564617631
    - 0.3719660313940375
    - 0.631117956959894
    - -0.05771324136823102
    - 0.2946152417893851
    - -0.12716433016812698
    - -1.418668162759059
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         18,653\nModel:\
        \         Multinomial Logit   Df Residuals:             18,628\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.351\nTime:          \
        \            22:04   Pseudo R-bar-squ.:         0.350\nAIC:              \
        \   111,598.101   Log-Likelihood:      -55,774.051\nBIC:                 111,793.945\
        \   LL-Null:             -85,900.239\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1398     0.001   -230.599    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.2622   \
        \  0.015    -17.323     0.000             \nst_bg_mean_children          \
        \            -0.3318     0.012    -28.678     0.000             \nst_bg_mean_year_built\
        \                    -0.0075     0.013     -0.588     0.556             \n\
        st_bg_median_value_13_acs                -0.1290     0.018     -7.318    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5567   \
        \  0.021     27.061     0.000             \nst_bg_prop_units_sf          \
        \             0.1040     0.019      5.434     0.000             \nst_bg_ratio_households_to_units\
        \           0.3543     0.020     17.430     0.000             \nst_bg_total_units\
        \                         0.1773     0.011     15.907     0.000          \
        \   \nst_density_jobs_90pct_plus                0.1114     0.007     15.824\
        \     0.000             \nst_density_units_90pct_plus               0.7155\
        \     0.006    125.106     0.000             \nst_pred_built_out_sf      \
        \                0.0682     0.009      7.264     0.000             \nst_pred_rich_owned_antique\
        \               -0.1159     0.036     -3.181     0.001             \nst_tracts_income_segment_1_hh\
        \             0.0583     0.011      5.545     0.000             \nst_tracts_income_segment_6_hh\
        \             0.2276     0.015     14.943     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0352     0.011      3.100     0.002             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.9476     0.085     11.104     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.0067     0.089      0.076     0.940             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.2382     0.152     -8.122     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.3720     0.126      2.946     0.003             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.6311     0.168      3.764     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.0577     0.068     -0.848     0.396             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.2946     0.181      1.631     0.103             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.1272     0.023     -5.620     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -1.4187     0.113    -12.547     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
