modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1439333708050954
    - 0.5061516090637221
    - 0.13582070813407016
    - -0.29017533526451805
    - 0.08331550000001306
    - -0.2510721051954349
    - -0.2419067114326814
    - 0.41219912224456123
    - 0.36513997995337055
    - -0.14054960880994286
    - 0.22874982777461902
    - 0.06038545791399516
    - -0.07619235311984879
    - 0.22155561457882467
    - 0.5419701440264806
    - 0.1994943994445195
    - 0.2632072136309929
    - -0.18124492286439753
    - -1.755919431319213
    - -1.1626569323501217
    - -2.211150084396817
    - -3.0887322332688565
    - 7.376035561656529
    - 0.02460090451860727
    - 0.2136274542913526
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          4,961\nModel:\
        \         Multinomial Logit   Df Residuals:              4,936\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.078\nTime:          \
        \            18:53   Pseudo R-bar-squ.:         0.077\nAIC:              \
        \    42,183.356   Log-Likelihood:      -21,066.678\nBIC:                 \
        \ 42,346.090   LL-Null:             -22,846.249\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1439     0.001   -115.806    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.5062   \
        \  0.031     16.108     0.000             \nst_bg_mean_children          \
        \             0.1358     0.031      4.358     0.000             \nst_bg_mean_year_built\
        \                    -0.2902     0.030     -9.757     0.000             \n\
        st_bg_median_value_13_acs                 0.0833     0.036      2.313    \
        \ 0.021             \nst_bg_prop_hh_rent                       -0.2511   \
        \  0.039     -6.397     0.000             \nst_bg_prop_units_sf          \
        \            -0.2419     0.037     -6.469     0.000             \nst_bg_ratio_households_to_units\
        \           0.4122     0.018     22.921     0.000             \nst_bg_total_units\
        \                         0.3651     0.030     12.140     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1405     0.022     -6.272\
        \     0.000             \nst_density_units_90pct_plus               0.2287\
        \     0.022     10.469     0.000             \nst_pred_built_out_sf      \
        \                0.0604     0.029      2.089     0.037             \nst_pred_rich_owned_antique\
        \               -0.0762     0.027     -2.826     0.005             \nst_tracts_income_segment_1_hh\
        \             0.2216     0.049      4.530     0.000             \nst_tracts_income_segment_6_hh\
        \             0.5420     0.069      7.882     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.1995     0.052      3.837     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.2632     0.359      0.734     0.463             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.1812     0.218     -0.831     0.406             \nst_zones_jobs_1_sum_5_min_sov\
        \            -1.7559     0.365     -4.810     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.1627     0.431     -2.700     0.007             \nst_zones_jobs_3_sum_5_min_sov\
        \            -2.2112     0.932     -2.373     0.018             \nst_zones_jobs_4_sum_5_min_sov\
        \            -3.0887     0.717     -4.307     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             7.3760     1.612      4.574     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \        0.0246     0.307      0.080     0.936             \nst_zones_total_units_sum_10_min_sov\
        \       0.2136     0.509      0.420     0.674             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
