modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12111993919850012
    - 0.33068262200573745
    - -0.1999237534821859
    - 0.007453426097254983
    - -0.13087473039214798
    - -0.39536832977573355
    - -0.20164855843987847
    - 0.23743331000740772
    - 0.17965940143798048
    - -0.09455687719264885
    - 0.31215597505829246
    - 0.08723683081178503
    - -0.010092983259021845
    - 0.03389074593482446
    - 0.07856523101172345
    - 0.053870047137834214
    - -1.3518692227723064
    - -0.1549780648789764
    - 1.1249356545800617
    - -1.3675460216529423
    - -1.3425662827643368
    - 0.08736230966525627
    - 1.1548008437069226
    - 2.3584790005366076
    - 0.09594678612786345
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         12,901\nModel:\
        \         Multinomial Logit   Df Residuals:             12,876\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.060\nTime:          \
        \            18:52   Pseudo R-bar-squ.:         0.060\nAIC:              \
        \   111,717.714   Log-Likelihood:      -55,833.857\nBIC:                 111,904.340\
        \   LL-Null:             -59,411.301\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1211     0.001   -164.349    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.3307   \
        \  0.023     14.373     0.000             \nst_bg_mean_children          \
        \            -0.1999     0.022     -8.900     0.000             \nst_bg_mean_year_built\
        \                     0.0075     0.019      0.386     0.699             \n\
        st_bg_median_value_13_acs                -0.1309     0.019     -7.061    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.3954   \
        \  0.030    -12.982     0.000             \nst_bg_prop_units_sf          \
        \            -0.2016     0.027     -7.590     0.000             \nst_bg_ratio_households_to_units\
        \           0.2374     0.014     17.353     0.000             \nst_bg_total_units\
        \                         0.1797     0.015     11.729     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0946     0.010     -9.678\
        \     0.000             \nst_density_units_90pct_plus               0.3122\
        \     0.010     32.362     0.000             \nst_pred_built_out_sf      \
        \                0.0872     0.015      6.004     0.000             \nst_pred_rich_owned_antique\
        \               -0.0101     0.007     -1.537     0.124             \nst_tracts_income_segment_1_hh\
        \             0.0339     0.019      1.828     0.068             \nst_tracts_income_segment_6_hh\
        \             0.0786     0.014      5.764     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0539     0.024      2.245     0.025             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -1.3519     0.155     -8.707     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.1550     0.092     -1.689     0.091             \nst_zones_jobs_1_sum_5_min_sov\
        \             1.1249     0.159      7.055     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.3675     0.169     -8.092     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.3426     0.223     -6.024     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.0874     0.260      0.336     0.737             \nst_zones_jobs_5_sum_5_min_sov\
        \             1.1548     0.352      3.276     0.001             \nst_zones_total_jobs_sum_20_min_sov\
        \        2.3585     0.119     19.815     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.0959     0.225      0.427     0.669             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
