modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.10236981168615852
    - -0.22540359205996116
    - 0.06825361053946441
    - -0.012363594232214337
    - 0.0506044613256853
    - -0.5891897823379323
    - -0.12541294598219135
    - 0.6756086502172063
    - 0.10752000408380613
    - -0.1970431656019463
    - 0.21679300144960406
    - 0.04872390336800043
    - 0.026541540999478395
    - 0.12318852411028673
    - -0.05227586282759153
    - -0.21201865269667794
    - 0.6215319835390068
    - -0.22929037249210488
    - 0.538617977181816
    - -0.4608995862067377
    - -1.0507571298075333
    - -1.3141650393235849
    - 2.3815065223096727
    - -0.10021357297827402
    - -0.5572027007815051
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          59,641\nModel:\
        \         Multinomial Logit   Df Residuals:              59,616\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.260\nTime:       \
        \               20:07   Pseudo R-bar-squ.:          0.260\nAIC:          \
        \       406,418.654   Log-Likelihood:      -203,184.327\nBIC:            \
        \     406,643.556   LL-Null:             -274,656.955\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1024     0.000   -369.083    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.2254   \
        \  0.010    -21.949     0.000             \nst_bg_mean_children          \
        \             0.0683     0.007      9.473     0.000             \nst_bg_mean_year_built\
        \                    -0.0124     0.008     -1.509     0.131             \n\
        st_bg_median_value_13_acs                 0.0506     0.009      5.688    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.5892   \
        \  0.012    -48.184     0.000             \nst_bg_prop_units_sf          \
        \            -0.1254     0.011    -11.539     0.000             \nst_bg_ratio_households_to_units\
        \           0.6756     0.014     46.671     0.000             \nst_bg_total_units\
        \                         0.1075     0.007     15.857     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.1970     0.006    -32.724\
        \     0.000             \nst_density_units_90pct_plus               0.2168\
        \     0.004     57.145     0.000             \nst_pred_built_out_sf      \
        \                0.0487     0.002     20.237     0.000             \nst_pred_rich_owned_antique\
        \                0.0265     0.003     10.471     0.000             \nst_tracts_income_segment_1_hh\
        \             0.1232     0.010     12.358     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.0523     0.005     -9.553     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.2120     0.012    -18.146     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.6215     0.055     11.257     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.2293     0.034     -6.653     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             0.5386     0.060      9.042     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -0.4609     0.016    -28.069     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.0508     0.083    -12.690     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -1.3142     0.059    -22.261     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             2.3815     0.133     17.969     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.1002     0.020     -5.057     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.5572     0.072     -7.757     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
