modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.1268207519684883
    - -0.41074368231311215
    - -0.5108249012695057
    - -0.042423242693030654
    - -0.7032253815770164
    - 0.44769088789600087
    - 0.09292896648541171
    - 0.7207031519949781
    - -0.023473441973662586
    - 0.11552315534256839
    - 0.6910923772003372
    - 0.07664755717583462
    - -2.418668935335729
    - 0.0193960123533576
    - -0.5207111950623851
    - 0.2195592854781161
    - -0.7222762739573356
    - -0.06628378939385196
    - 1.8279210509813537
    - -1.3133081777187836
    - 0.44492737451548786
    - 1.159928603417958
    - -2.766813269205752
    - -0.439174648095232
    - 0.3668642428010277
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          6,740\nModel:\
        \         Multinomial Logit   Df Residuals:              6,715\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.309\nTime:          \
        \            22:29   Pseudo R-bar-squ.:         0.308\nAIC:              \
        \    42,967.688   Log-Likelihood:      -21,458.844\nBIC:                 \
        \ 43,138.083   LL-Null:             -31,038.847\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1268     0.001   -102.499    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.4107   \
        \  0.026    -15.755     0.000             \nst_bg_mean_children          \
        \            -0.5108     0.023    -22.579     0.000             \nst_bg_mean_year_built\
        \                    -0.0424     0.021     -2.026     0.043             \n\
        st_bg_median_value_13_acs                -0.7032     0.053    -13.295    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.4477   \
        \  0.035     12.642     0.000             \nst_bg_prop_units_sf          \
        \             0.0929     0.030      3.055     0.002             \nst_bg_ratio_households_to_units\
        \           0.7207     0.036     20.162     0.000             \nst_bg_total_units\
        \                        -0.0235     0.023     -1.005     0.315          \
        \   \nst_density_jobs_90pct_plus                0.1155     0.014      8.102\
        \     0.000             \nst_density_units_90pct_plus               0.6911\
        \     0.010     71.776     0.000             \nst_pred_built_out_sf      \
        \                0.0766     0.015      5.157     0.000             \nst_pred_rich_owned_antique\
        \               -2.4187     0.603     -4.009     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0194     0.022      0.871     0.384             \nst_tracts_income_segment_6_hh\
        \            -0.5207     0.086     -6.062     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.2196     0.077      2.856     0.004             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.7223     0.112     -6.470     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.0663     0.127     -0.521     0.602             \nst_zones_jobs_1_sum_5_min_sov\
        \             1.8279     0.221      8.263     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.3133     0.239     -5.502     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \             0.4449     0.204      2.178     0.029             \nst_zones_jobs_4_sum_5_min_sov\
        \             1.1599     0.219      5.302     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \            -2.7668     0.291     -9.515     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.4392     0.038    -11.433     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.3669     0.163      2.254     0.024             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
