modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.13070712376746946
    - 0.517290834651062
    - -0.021440760159206138
    - 0.07818901652674445
    - 0.12744336646365148
    - 0.5890430902410961
    - -0.06616451873517529
    - 0.3015472584675418
    - 0.20476967504817653
    - 0.03284503787913017
    - 0.5729465974358785
    - 0.17862880246117424
    - -0.1732851005113705
    - 0.06349874840322614
    - 0.03714550011314917
    - 0.2009189963816976
    - -3.7430643344936567
    - 0.7660038694652695
    - 2.3336758009393166
    - -1.4023100619975957
    - -2.2066269668984915
    - -1.2405668891149741
    - 2.5486522551732347
    - 2.6114559794747048
    - 2.294696100712355
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          9,293\nModel:\
        \         Multinomial Logit   Df Residuals:              9,268\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2021-09-09   Pseudo R-squ.:             0.169\nTime:          \
        \            22:40   Pseudo R-bar-squ.:         0.169\nAIC:              \
        \    71,142.865   Log-Likelihood:      -35,546.433\nBIC:                 \
        \ 71,321.291   LL-Null:             -42,795.847\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1307     0.001   -150.414    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.5173   \
        \  0.023     22.530     0.000             \nst_bg_mean_children          \
        \            -0.0214     0.023     -0.945     0.345             \nst_bg_mean_year_built\
        \                     0.0782     0.023      3.407     0.001             \n\
        st_bg_median_value_13_acs                 0.1274     0.021      6.033    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5890   \
        \  0.037     15.852     0.000             \nst_bg_prop_units_sf          \
        \            -0.0662     0.032     -2.046     0.041             \nst_bg_ratio_households_to_units\
        \           0.3015     0.017     17.453     0.000             \nst_bg_total_units\
        \                         0.2048     0.019     11.048     0.000          \
        \   \nst_density_jobs_90pct_plus                0.0328     0.008      3.953\
        \     0.000             \nst_density_units_90pct_plus               0.5729\
        \     0.008     69.616     0.000             \nst_pred_built_out_sf      \
        \                0.1786     0.019      9.460     0.000             \nst_pred_rich_owned_antique\
        \               -0.1733     0.016    -10.620     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0635     0.024      2.630     0.009             \nst_tracts_income_segment_6_hh\
        \             0.0371     0.017      2.236     0.025             \nst_zones_density_units_ave_5_min_sov\
        \      0.2009     0.028      7.057     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -3.7431     0.218    -17.166     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.7660     0.103      7.455     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \             2.3337     0.219     10.658     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \            -1.4023     0.211     -6.647     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -2.2066     0.277     -7.968     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -1.2406     0.349     -3.559     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             2.5487     0.482      5.284     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \        2.6115     0.185     14.089     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       2.2947     0.323      7.094     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
