modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.12212215765231922
    - 0.48935697006916923
    - -0.08702228318264449
    - -0.11669097810487394
    - -0.2606015378164676
    - -0.2026294346109528
    - -0.1458507990741842
    - 0.3491248436694073
    - 0.13110697259903123
    - -0.09656683043648129
    - 0.3714074990497691
    - 0.09273793884846285
    - -0.02897445006210781
    - 0.0825839253043918
    - 0.06692435504940811
    - 0.10180296319950953
    - 0.5667362493629478
    - 0.7962515749846175
    - -0.496314435384583
    - 0.4782546076766063
    - -1.4463752089074624
    - 0.39169523058135935
    - 1.0071097409290577
    - 0.13786680515093835
    - -1.041424665514445
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          37,995\nModel:\
        \         Multinomial Logit   Df Residuals:              37,970\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.106\nTime:       \
        \               18:49   Pseudo R-bar-squ.:          0.106\nAIC:          \
        \       312,855.477   Log-Likelihood:      -156,402.738\nBIC:            \
        \     313,069.107   LL-Null:             -174,973.441\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1221     0.000   -244.526    \
        \ 0.000             \nst_bg_mean_age_of_head                    0.4894   \
        \  0.009     54.963     0.000             \nst_bg_mean_children          \
        \            -0.0870     0.009    -10.028     0.000             \nst_bg_mean_year_built\
        \                    -0.1167     0.009    -13.588     0.000             \n\
        st_bg_median_value_13_acs                -0.2606     0.011    -24.147    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.2026   \
        \  0.014    -14.403     0.000             \nst_bg_prop_units_sf          \
        \            -0.1459     0.010    -13.926     0.000             \nst_bg_ratio_households_to_units\
        \           0.3491     0.015     24.017     0.000             \nst_bg_total_units\
        \                         0.1311     0.007     19.590     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0966     0.008    -12.350\
        \     0.000             \nst_density_units_90pct_plus               0.3714\
        \     0.006     67.206     0.000             \nst_pred_built_out_sf      \
        \                0.0927     0.004     21.397     0.000             \nst_pred_rich_owned_antique\
        \               -0.0290     0.011     -2.733     0.006             \nst_tracts_income_segment_1_hh\
        \             0.0826     0.008      9.845     0.000             \nst_tracts_income_segment_6_hh\
        \             0.0669     0.009      7.156     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.1018     0.010      9.743     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.5667     0.052     10.963     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \             0.7963     0.061     13.037     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.4963     0.099     -5.001     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.4783     0.080      6.008     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -1.4464     0.106    -13.581     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \             0.3917     0.046      8.533     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             1.0071     0.118      8.501     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \        0.1379     0.017      8.252     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -1.0414     0.069    -15.092     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
