modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.17496099713197905
    - -0.014566738103935667
    - 0.17723704321754216
    - 0.013085043429905302
    - -0.23475665754280858
    - 0.5415135941904705
    - 0.1787960452965705
    - 0.4204468501611155
    - 0.04659608532560908
    - -0.048666741288496164
    - 0.5111099037364066
    - 0.0595651576701755
    - -0.23050281536223155
    - 0.05384470305449828
    - -0.11523657658415119
    - -0.0178493835592754
    - 0.0564015069700124
    - -0.6032947554258697
    - -0.8496976500220965
    - 0.3945741476513406
    - -0.4036938736549456
    - -0.0805107858044816
    - 0.8328049691546107
    - -0.06787032450432412
    - -0.12640270525300823
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          38,158\nModel:\
        \         Multinomial Logit   Df Residuals:              38,133\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-10   Pseudo R-squ.:              0.234\nTime:       \
        \               00:17   Pseudo R-bar-squ.:          0.234\nAIC:          \
        \       269,163.975   Log-Likelihood:      -134,556.988\nBIC:            \
        \     269,377.712   LL-Null:             -175,724.084\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1750     0.001   -254.031    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.0146   \
        \  0.010     -1.487     0.137             \nst_bg_mean_children          \
        \             0.1772     0.008     23.185     0.000             \nst_bg_mean_year_built\
        \                     0.0131     0.010      1.280     0.201             \n\
        st_bg_median_value_13_acs                -0.2348     0.012    -20.033    \
        \ 0.000             \nst_bg_prop_hh_rent                        0.5415   \
        \  0.013     41.294     0.000             \nst_bg_prop_units_sf          \
        \             0.1788     0.011     15.590     0.000             \nst_bg_ratio_households_to_units\
        \           0.4204     0.008     52.646     0.000             \nst_bg_total_units\
        \                         0.0466     0.008      5.578     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.0487     0.006     -8.620\
        \     0.000             \nst_density_units_90pct_plus               0.5111\
        \     0.005    112.259     0.000             \nst_pred_built_out_sf      \
        \                0.0596     0.006     10.101     0.000             \nst_pred_rich_owned_antique\
        \               -0.2305     0.029     -7.962     0.000             \nst_tracts_income_segment_1_hh\
        \             0.0538     0.007      7.208     0.000             \nst_tracts_income_segment_6_hh\
        \            -0.1152     0.016     -7.131     0.000             \nst_zones_density_units_ave_5_min_sov\
        \     -0.0178     0.022     -0.804     0.422             \nst_zones_income_6_hh_sum_10_min_sov\
        \       0.0564     0.052      1.093     0.274             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.6033     0.065     -9.306     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.8497     0.056    -15.117     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.3946     0.057      6.935     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -0.4037     0.084     -4.830     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.0805     0.051     -1.592     0.111             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.8328     0.089      9.336     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.0679     0.018     -3.785     0.000             \nst_zones_total_units_sum_10_min_sov\
        \      -0.1264     0.059     -2.139     0.032             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
