modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.15625490992004873
    - -0.28124202377541896
    - 0.0944204447879129
    - 0.030864650434180275
    - -0.1851024870329226
    - -0.5099826044508315
    - 0.16132264971583613
    - 0.4280697190220006
    - 0.0936292328789554
    - -0.20252815571241245
    - 0.09124784052477841
    - 0.0374669131955045
    - 0.027983006358587584
    - 0.021550334304552613
    - -0.06248258009453455
    - 0.07627424789416651
    - -0.30636368785611756
    - -0.5898329869791954
    - -0.6963464453655657
    - 0.60048746096175
    - -0.4969109034843431
    - -0.39155078422071704
    - 0.6500564933772126
    - -0.14866548050004835
    - 0.3750203195031645
    max_iter: null
    mct_intx_ops:
        aggregations:
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
            sov_school: min
            sov_work: min
        extra_alts_cols:
        - zone_id
        rename_cols:
            sov_school: min_school_sov
            sov_work: min_work_sov
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: min_work_sov.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: min_school_sov.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_sov
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
    model_expression: mandatory_activity_dummy:mandatory_sov + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          38,405\nModel:\
        \         Multinomial Logit   Df Residuals:              38,380\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2021-09-09   Pseudo R-squ.:              0.160\nTime:       \
        \               20:36   Pseudo R-bar-squ.:          0.160\nAIC:          \
        \       297,217.031   Log-Likelihood:      -148,583.515\nBIC:            \
        \     297,430.929   LL-Null:             -176,861.561\n============================================================================================\n\
        \                                            coef   std err          z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_sov   -0.1563     0.001   -236.544    \
        \ 0.000             \nst_bg_mean_age_of_head                   -0.2812   \
        \  0.010    -27.710     0.000             \nst_bg_mean_children          \
        \             0.0944     0.009     10.472     0.000             \nst_bg_mean_year_built\
        \                     0.0309     0.010      3.025     0.002             \n\
        st_bg_median_value_13_acs                -0.1851     0.011    -16.311    \
        \ 0.000             \nst_bg_prop_hh_rent                       -0.5100   \
        \  0.015    -34.154     0.000             \nst_bg_prop_units_sf          \
        \             0.1613     0.012     12.949     0.000             \nst_bg_ratio_households_to_units\
        \           0.4281     0.008     56.640     0.000             \nst_bg_total_units\
        \                         0.0936     0.007     12.594     0.000          \
        \   \nst_density_jobs_90pct_plus               -0.2025     0.009    -23.389\
        \     0.000             \nst_density_units_90pct_plus               0.0912\
        \     0.009     10.692     0.000             \nst_pred_built_out_sf      \
        \                0.0375     0.005      7.209     0.000             \nst_pred_rich_owned_antique\
        \                0.0280     0.009      3.039     0.002             \nst_tracts_income_segment_1_hh\
        \             0.0216     0.008      2.689     0.007             \nst_tracts_income_segment_6_hh\
        \            -0.0625     0.013     -4.949     0.000             \nst_zones_density_units_ave_5_min_sov\
        \      0.0763     0.023      3.262     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \      -0.3064     0.048     -6.386     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \            -0.5898     0.067     -8.868     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \            -0.6963     0.059    -11.835     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \             0.6005     0.065      9.270     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \            -0.4969     0.087     -5.743     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \            -0.3916     0.055     -7.113     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \             0.6501     0.085      7.681     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \       -0.1487     0.016     -9.145     0.000             \nst_zones_total_units_sum_10_min_sov\
        \       0.3750     0.061      6.159     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
